// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.protobuf.FeatureSet in google/protobuf/descriptor.proto
package com.google.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnclosingType;
import com.squareup.wire.WireEnum;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.AssertionError;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * ===================================================================
 * Features
 * TODO Enums in C++ gencode (and potentially other languages) are
 * not well scoped.  This means that each of the feature enums below can clash
 * with each other.  The short names we've chosen maximize call-site
 * readability, but leave us very open to this scenario.  A future feature will
 * be designed and implemented to handle this, hopefully before we ever hit a
 * conflict here.
 */
public final class FeatureSet extends Message<FeatureSet, FeatureSet.Builder> {
  public static final ProtoAdapter<FeatureSet> ADAPTER = new ProtoAdapter_FeatureSet();

  private static final long serialVersionUID = 0L;

  public static final FieldPresence DEFAULT_FIELD_PRESENCE = FieldPresence.FIELD_PRESENCE_UNKNOWN;

  public static final EnumType DEFAULT_ENUM_TYPE = EnumType.ENUM_TYPE_UNKNOWN;

  public static final RepeatedFieldEncoding DEFAULT_REPEATED_FIELD_ENCODING = RepeatedFieldEncoding.REPEATED_FIELD_ENCODING_UNKNOWN;

  public static final Utf8Validation DEFAULT_UTF8_VALIDATION = Utf8Validation.UTF8_VALIDATION_UNKNOWN;

  public static final MessageEncoding DEFAULT_MESSAGE_ENCODING = MessageEncoding.MESSAGE_ENCODING_UNKNOWN;

  public static final JsonFormat DEFAULT_JSON_FORMAT = JsonFormat.JSON_FORMAT_UNKNOWN;

  public static final EnforceNamingStyle DEFAULT_ENFORCE_NAMING_STYLE = EnforceNamingStyle.ENFORCE_NAMING_STYLE_UNKNOWN;

  public static final VisibilityFeature.DefaultSymbolVisibility DEFAULT_DEFAULT_SYMBOL_VISIBILITY = VisibilityFeature.DefaultSymbolVisibility.DEFAULT_SYMBOL_VISIBILITY_UNKNOWN;

  public static final ProtoLimitsFeature.EnforceProtoLimits DEFAULT_ENFORCE_PROTO_LIMITS = ProtoLimitsFeature.EnforceProtoLimits.PROTO_LIMITS_UNKNOWN;

  @WireField(
      tag = 1,
      adapter = "com.google.protobuf.FeatureSet$FieldPresence#ADAPTER"
  )
  public final FieldPresence field_presence;

  @WireField(
      tag = 2,
      adapter = "com.google.protobuf.FeatureSet$EnumType#ADAPTER"
  )
  public final EnumType enum_type;

  @WireField(
      tag = 3,
      adapter = "com.google.protobuf.FeatureSet$RepeatedFieldEncoding#ADAPTER"
  )
  public final RepeatedFieldEncoding repeated_field_encoding;

  @WireField(
      tag = 4,
      adapter = "com.google.protobuf.FeatureSet$Utf8Validation#ADAPTER"
  )
  public final Utf8Validation utf8_validation;

  @WireField(
      tag = 5,
      adapter = "com.google.protobuf.FeatureSet$MessageEncoding#ADAPTER"
  )
  public final MessageEncoding message_encoding;

  @WireField(
      tag = 6,
      adapter = "com.google.protobuf.FeatureSet$JsonFormat#ADAPTER"
  )
  public final JsonFormat json_format;

  @WireField(
      tag = 7,
      adapter = "com.google.protobuf.FeatureSet$EnforceNamingStyle#ADAPTER"
  )
  public final EnforceNamingStyle enforce_naming_style;

  @WireField(
      tag = 8,
      adapter = "com.google.protobuf.FeatureSet$VisibilityFeature$DefaultSymbolVisibility#ADAPTER"
  )
  public final VisibilityFeature.DefaultSymbolVisibility default_symbol_visibility;

  @WireField(
      tag = 9,
      adapter = "com.google.protobuf.FeatureSet$ProtoLimitsFeature$EnforceProtoLimits#ADAPTER"
  )
  public final ProtoLimitsFeature.EnforceProtoLimits enforce_proto_limits;

  public FeatureSet(FieldPresence field_presence, EnumType enum_type,
      RepeatedFieldEncoding repeated_field_encoding, Utf8Validation utf8_validation,
      MessageEncoding message_encoding, JsonFormat json_format,
      EnforceNamingStyle enforce_naming_style,
      VisibilityFeature.DefaultSymbolVisibility default_symbol_visibility,
      ProtoLimitsFeature.EnforceProtoLimits enforce_proto_limits) {
    this(field_presence, enum_type, repeated_field_encoding, utf8_validation, message_encoding, json_format, enforce_naming_style, default_symbol_visibility, enforce_proto_limits, ByteString.EMPTY);
  }

  public FeatureSet(FieldPresence field_presence, EnumType enum_type,
      RepeatedFieldEncoding repeated_field_encoding, Utf8Validation utf8_validation,
      MessageEncoding message_encoding, JsonFormat json_format,
      EnforceNamingStyle enforce_naming_style,
      VisibilityFeature.DefaultSymbolVisibility default_symbol_visibility,
      ProtoLimitsFeature.EnforceProtoLimits enforce_proto_limits, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.field_presence = field_presence;
    this.enum_type = enum_type;
    this.repeated_field_encoding = repeated_field_encoding;
    this.utf8_validation = utf8_validation;
    this.message_encoding = message_encoding;
    this.json_format = json_format;
    this.enforce_naming_style = enforce_naming_style;
    this.default_symbol_visibility = default_symbol_visibility;
    this.enforce_proto_limits = enforce_proto_limits;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.field_presence = field_presence;
    builder.enum_type = enum_type;
    builder.repeated_field_encoding = repeated_field_encoding;
    builder.utf8_validation = utf8_validation;
    builder.message_encoding = message_encoding;
    builder.json_format = json_format;
    builder.enforce_naming_style = enforce_naming_style;
    builder.default_symbol_visibility = default_symbol_visibility;
    builder.enforce_proto_limits = enforce_proto_limits;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof FeatureSet)) return false;
    FeatureSet o = (FeatureSet) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(field_presence, o.field_presence)
        && Internal.equals(enum_type, o.enum_type)
        && Internal.equals(repeated_field_encoding, o.repeated_field_encoding)
        && Internal.equals(utf8_validation, o.utf8_validation)
        && Internal.equals(message_encoding, o.message_encoding)
        && Internal.equals(json_format, o.json_format)
        && Internal.equals(enforce_naming_style, o.enforce_naming_style)
        && Internal.equals(default_symbol_visibility, o.default_symbol_visibility)
        && Internal.equals(enforce_proto_limits, o.enforce_proto_limits);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (field_presence != null ? field_presence.hashCode() : 0);
      result = result * 37 + (enum_type != null ? enum_type.hashCode() : 0);
      result = result * 37 + (repeated_field_encoding != null ? repeated_field_encoding.hashCode() : 0);
      result = result * 37 + (utf8_validation != null ? utf8_validation.hashCode() : 0);
      result = result * 37 + (message_encoding != null ? message_encoding.hashCode() : 0);
      result = result * 37 + (json_format != null ? json_format.hashCode() : 0);
      result = result * 37 + (enforce_naming_style != null ? enforce_naming_style.hashCode() : 0);
      result = result * 37 + (default_symbol_visibility != null ? default_symbol_visibility.hashCode() : 0);
      result = result * 37 + (enforce_proto_limits != null ? enforce_proto_limits.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (field_presence != null) builder.append(", field_presence=").append(field_presence);
    if (enum_type != null) builder.append(", enum_type=").append(enum_type);
    if (repeated_field_encoding != null) builder.append(", repeated_field_encoding=").append(repeated_field_encoding);
    if (utf8_validation != null) builder.append(", utf8_validation=").append(utf8_validation);
    if (message_encoding != null) builder.append(", message_encoding=").append(message_encoding);
    if (json_format != null) builder.append(", json_format=").append(json_format);
    if (enforce_naming_style != null) builder.append(", enforce_naming_style=").append(enforce_naming_style);
    if (default_symbol_visibility != null) builder.append(", default_symbol_visibility=").append(default_symbol_visibility);
    if (enforce_proto_limits != null) builder.append(", enforce_proto_limits=").append(enforce_proto_limits);
    return builder.replace(0, 2, "FeatureSet{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<FeatureSet, Builder> {
    public FieldPresence field_presence;

    public EnumType enum_type;

    public RepeatedFieldEncoding repeated_field_encoding;

    public Utf8Validation utf8_validation;

    public MessageEncoding message_encoding;

    public JsonFormat json_format;

    public EnforceNamingStyle enforce_naming_style;

    public VisibilityFeature.DefaultSymbolVisibility default_symbol_visibility;

    public ProtoLimitsFeature.EnforceProtoLimits enforce_proto_limits;

    public Builder() {
    }

    public Builder field_presence(FieldPresence field_presence) {
      this.field_presence = field_presence;
      return this;
    }

    public Builder enum_type(EnumType enum_type) {
      this.enum_type = enum_type;
      return this;
    }

    public Builder repeated_field_encoding(RepeatedFieldEncoding repeated_field_encoding) {
      this.repeated_field_encoding = repeated_field_encoding;
      return this;
    }

    public Builder utf8_validation(Utf8Validation utf8_validation) {
      this.utf8_validation = utf8_validation;
      return this;
    }

    public Builder message_encoding(MessageEncoding message_encoding) {
      this.message_encoding = message_encoding;
      return this;
    }

    public Builder json_format(JsonFormat json_format) {
      this.json_format = json_format;
      return this;
    }

    public Builder enforce_naming_style(EnforceNamingStyle enforce_naming_style) {
      this.enforce_naming_style = enforce_naming_style;
      return this;
    }

    public Builder default_symbol_visibility(
        VisibilityFeature.DefaultSymbolVisibility default_symbol_visibility) {
      this.default_symbol_visibility = default_symbol_visibility;
      return this;
    }

    public Builder enforce_proto_limits(
        ProtoLimitsFeature.EnforceProtoLimits enforce_proto_limits) {
      this.enforce_proto_limits = enforce_proto_limits;
      return this;
    }

    @Override
    public FeatureSet build() {
      return new FeatureSet(field_presence, enum_type, repeated_field_encoding, utf8_validation, message_encoding, json_format, enforce_naming_style, default_symbol_visibility, enforce_proto_limits, super.buildUnknownFields());
    }
  }

  public enum FieldPresence implements WireEnum {
    FIELD_PRESENCE_UNKNOWN(0),

    EXPLICIT(1),

    IMPLICIT(2),

    LEGACY_REQUIRED(3);

    public static final ProtoAdapter<FieldPresence> ADAPTER = new ProtoAdapter_FieldPresence();

    private final int value;

    FieldPresence(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static FieldPresence fromValue(int value) {
      switch (value) {
        case 0: return FIELD_PRESENCE_UNKNOWN;
        case 1: return EXPLICIT;
        case 2: return IMPLICIT;
        case 3: return LEGACY_REQUIRED;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_FieldPresence extends EnumAdapter<FieldPresence> {
      ProtoAdapter_FieldPresence() {
        super(FieldPresence.class, Syntax.PROTO_2, FieldPresence.FIELD_PRESENCE_UNKNOWN);
      }

      @Override
      protected FieldPresence fromValue(int value) {
        return FieldPresence.fromValue(value);
      }
    }
  }

  public enum EnumType implements WireEnum {
    ENUM_TYPE_UNKNOWN(0),

    OPEN(1),

    CLOSED(2);

    public static final ProtoAdapter<EnumType> ADAPTER = new ProtoAdapter_EnumType();

    private final int value;

    EnumType(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static EnumType fromValue(int value) {
      switch (value) {
        case 0: return ENUM_TYPE_UNKNOWN;
        case 1: return OPEN;
        case 2: return CLOSED;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_EnumType extends EnumAdapter<EnumType> {
      ProtoAdapter_EnumType() {
        super(EnumType.class, Syntax.PROTO_2, EnumType.ENUM_TYPE_UNKNOWN);
      }

      @Override
      protected EnumType fromValue(int value) {
        return EnumType.fromValue(value);
      }
    }
  }

  public enum RepeatedFieldEncoding implements WireEnum {
    REPEATED_FIELD_ENCODING_UNKNOWN(0),

    PACKED(1),

    EXPANDED(2);

    public static final ProtoAdapter<RepeatedFieldEncoding> ADAPTER = new ProtoAdapter_RepeatedFieldEncoding();

    private final int value;

    RepeatedFieldEncoding(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static RepeatedFieldEncoding fromValue(int value) {
      switch (value) {
        case 0: return REPEATED_FIELD_ENCODING_UNKNOWN;
        case 1: return PACKED;
        case 2: return EXPANDED;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_RepeatedFieldEncoding extends EnumAdapter<RepeatedFieldEncoding> {
      ProtoAdapter_RepeatedFieldEncoding() {
        super(RepeatedFieldEncoding.class, Syntax.PROTO_2, RepeatedFieldEncoding.REPEATED_FIELD_ENCODING_UNKNOWN);
      }

      @Override
      protected RepeatedFieldEncoding fromValue(int value) {
        return RepeatedFieldEncoding.fromValue(value);
      }
    }
  }

  public enum Utf8Validation implements WireEnum {
    UTF8_VALIDATION_UNKNOWN(0),

    VERIFY(2),

    NONE(3);

    public static final ProtoAdapter<Utf8Validation> ADAPTER = new ProtoAdapter_Utf8Validation();

    private final int value;

    Utf8Validation(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static Utf8Validation fromValue(int value) {
      switch (value) {
        case 0: return UTF8_VALIDATION_UNKNOWN;
        case 2: return VERIFY;
        case 3: return NONE;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_Utf8Validation extends EnumAdapter<Utf8Validation> {
      ProtoAdapter_Utf8Validation() {
        super(Utf8Validation.class, Syntax.PROTO_2, Utf8Validation.UTF8_VALIDATION_UNKNOWN);
      }

      @Override
      protected Utf8Validation fromValue(int value) {
        return Utf8Validation.fromValue(value);
      }
    }
  }

  public enum MessageEncoding implements WireEnum {
    MESSAGE_ENCODING_UNKNOWN(0),

    LENGTH_PREFIXED(1),

    DELIMITED(2);

    public static final ProtoAdapter<MessageEncoding> ADAPTER = new ProtoAdapter_MessageEncoding();

    private final int value;

    MessageEncoding(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static MessageEncoding fromValue(int value) {
      switch (value) {
        case 0: return MESSAGE_ENCODING_UNKNOWN;
        case 1: return LENGTH_PREFIXED;
        case 2: return DELIMITED;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_MessageEncoding extends EnumAdapter<MessageEncoding> {
      ProtoAdapter_MessageEncoding() {
        super(MessageEncoding.class, Syntax.PROTO_2, MessageEncoding.MESSAGE_ENCODING_UNKNOWN);
      }

      @Override
      protected MessageEncoding fromValue(int value) {
        return MessageEncoding.fromValue(value);
      }
    }
  }

  public enum JsonFormat implements WireEnum {
    JSON_FORMAT_UNKNOWN(0),

    ALLOW(1),

    LEGACY_BEST_EFFORT(2);

    public static final ProtoAdapter<JsonFormat> ADAPTER = new ProtoAdapter_JsonFormat();

    private final int value;

    JsonFormat(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static JsonFormat fromValue(int value) {
      switch (value) {
        case 0: return JSON_FORMAT_UNKNOWN;
        case 1: return ALLOW;
        case 2: return LEGACY_BEST_EFFORT;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_JsonFormat extends EnumAdapter<JsonFormat> {
      ProtoAdapter_JsonFormat() {
        super(JsonFormat.class, Syntax.PROTO_2, JsonFormat.JSON_FORMAT_UNKNOWN);
      }

      @Override
      protected JsonFormat fromValue(int value) {
        return JsonFormat.fromValue(value);
      }
    }
  }

  public enum EnforceNamingStyle implements WireEnum {
    ENFORCE_NAMING_STYLE_UNKNOWN(0),

    STYLE2024(1),

    STYLE_LEGACY(2),

    STYLE2026(3);

    public static final ProtoAdapter<EnforceNamingStyle> ADAPTER = new ProtoAdapter_EnforceNamingStyle();

    private final int value;

    EnforceNamingStyle(int value) {
      this.value = value;
    }

    /**
     * Return the constant for {@code value} or null.
     */
    public static EnforceNamingStyle fromValue(int value) {
      switch (value) {
        case 0: return ENFORCE_NAMING_STYLE_UNKNOWN;
        case 1: return STYLE2024;
        case 2: return STYLE_LEGACY;
        case 3: return STYLE2026;
        default: return null;
      }
    }

    @Override
    public int getValue() {
      return value;
    }

    private static final class ProtoAdapter_EnforceNamingStyle extends EnumAdapter<EnforceNamingStyle> {
      ProtoAdapter_EnforceNamingStyle() {
        super(EnforceNamingStyle.class, Syntax.PROTO_2, EnforceNamingStyle.ENFORCE_NAMING_STYLE_UNKNOWN);
      }

      @Override
      protected EnforceNamingStyle fromValue(int value) {
        return EnforceNamingStyle.fromValue(value);
      }
    }
  }

  /**
   * <b>NOTE:</b> This type only exists to maintain class structure for its nested types and is not an actual message.
   */
  @WireEnclosingType
  public static final class VisibilityFeature {
    private VisibilityFeature() {
      throw new AssertionError();
    }

    public enum DefaultSymbolVisibility implements WireEnum {
      DEFAULT_SYMBOL_VISIBILITY_UNKNOWN(0),

      /**
       * Default pre-EDITION_2024, all UNSET visibility are export.
       */
      EXPORT_ALL(1),

      /**
       * All top-level symbols default to export, nested default to local.
       */
      EXPORT_TOP_LEVEL(2),

      /**
       * All symbols default to local.
       */
      LOCAL_ALL(3),

      /**
       * All symbols local by default. Nested types cannot be exported.
       * With special case caveat for message { enum {} reserved 1 to max; }
       * This is the recommended setting for new protos.
       */
      STRICT(4);

      public static final ProtoAdapter<DefaultSymbolVisibility> ADAPTER = new ProtoAdapter_DefaultSymbolVisibility();

      private final int value;

      DefaultSymbolVisibility(int value) {
        this.value = value;
      }

      /**
       * Return the constant for {@code value} or null.
       */
      public static DefaultSymbolVisibility fromValue(int value) {
        switch (value) {
          case 0: return DEFAULT_SYMBOL_VISIBILITY_UNKNOWN;
          case 1: return EXPORT_ALL;
          case 2: return EXPORT_TOP_LEVEL;
          case 3: return LOCAL_ALL;
          case 4: return STRICT;
          default: return null;
        }
      }

      @Override
      public int getValue() {
        return value;
      }

      private static final class ProtoAdapter_DefaultSymbolVisibility extends EnumAdapter<DefaultSymbolVisibility> {
        ProtoAdapter_DefaultSymbolVisibility() {
          super(DefaultSymbolVisibility.class, Syntax.PROTO_2, DefaultSymbolVisibility.DEFAULT_SYMBOL_VISIBILITY_UNKNOWN);
        }

        @Override
        protected DefaultSymbolVisibility fromValue(int value) {
          return DefaultSymbolVisibility.fromValue(value);
        }
      }
    }
  }

  /**
   * <b>NOTE:</b> This type only exists to maintain class structure for its nested types and is not an actual message.
   */
  @WireEnclosingType
  public static final class ProtoLimitsFeature {
    private ProtoLimitsFeature() {
      throw new AssertionError();
    }

    public enum EnforceProtoLimits implements WireEnum {
      PROTO_LIMITS_UNKNOWN(0),

      /**
       * Default pre-EDITION_2026: there are no limit enforcement at the protoc
       * level. Practical limits still exist, but they will tend to fail while
       * compiling protoc-generated code, and these limits tend to be language
       * or toolchain specific.
       */
      LEGACY_NO_EXPLICIT_LIMITS(1),

      /**
       * A set of limits enforced by Edition 2026 by default. For a detailed
       * list of all the limits please consult the Edition 2026 documentation.
       */
      PROTO_LIMITS2026(2);

      public static final ProtoAdapter<EnforceProtoLimits> ADAPTER = new ProtoAdapter_EnforceProtoLimits();

      private final int value;

      EnforceProtoLimits(int value) {
        this.value = value;
      }

      /**
       * Return the constant for {@code value} or null.
       */
      public static EnforceProtoLimits fromValue(int value) {
        switch (value) {
          case 0: return PROTO_LIMITS_UNKNOWN;
          case 1: return LEGACY_NO_EXPLICIT_LIMITS;
          case 2: return PROTO_LIMITS2026;
          default: return null;
        }
      }

      @Override
      public int getValue() {
        return value;
      }

      private static final class ProtoAdapter_EnforceProtoLimits extends EnumAdapter<EnforceProtoLimits> {
        ProtoAdapter_EnforceProtoLimits() {
          super(EnforceProtoLimits.class, Syntax.PROTO_2, EnforceProtoLimits.PROTO_LIMITS_UNKNOWN);
        }

        @Override
        protected EnforceProtoLimits fromValue(int value) {
          return EnforceProtoLimits.fromValue(value);
        }
      }
    }
  }

  private static final class ProtoAdapter_FeatureSet extends ProtoAdapter<FeatureSet> {
    public ProtoAdapter_FeatureSet() {
      super(FieldEncoding.LENGTH_DELIMITED, FeatureSet.class, "type.googleapis.com/google.protobuf.FeatureSet", Syntax.PROTO_2, null, "google/protobuf/descriptor.proto");
    }

    @Override
    public int encodedSize(FeatureSet value) {
      int result = 0;
      result += FieldPresence.ADAPTER.encodedSizeWithTag(1, value.field_presence);
      result += EnumType.ADAPTER.encodedSizeWithTag(2, value.enum_type);
      result += RepeatedFieldEncoding.ADAPTER.encodedSizeWithTag(3, value.repeated_field_encoding);
      result += Utf8Validation.ADAPTER.encodedSizeWithTag(4, value.utf8_validation);
      result += MessageEncoding.ADAPTER.encodedSizeWithTag(5, value.message_encoding);
      result += JsonFormat.ADAPTER.encodedSizeWithTag(6, value.json_format);
      result += EnforceNamingStyle.ADAPTER.encodedSizeWithTag(7, value.enforce_naming_style);
      result += VisibilityFeature.DefaultSymbolVisibility.ADAPTER.encodedSizeWithTag(8, value.default_symbol_visibility);
      result += ProtoLimitsFeature.EnforceProtoLimits.ADAPTER.encodedSizeWithTag(9, value.enforce_proto_limits);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, FeatureSet value) throws IOException {
      FieldPresence.ADAPTER.encodeWithTag(writer, 1, value.field_presence);
      EnumType.ADAPTER.encodeWithTag(writer, 2, value.enum_type);
      RepeatedFieldEncoding.ADAPTER.encodeWithTag(writer, 3, value.repeated_field_encoding);
      Utf8Validation.ADAPTER.encodeWithTag(writer, 4, value.utf8_validation);
      MessageEncoding.ADAPTER.encodeWithTag(writer, 5, value.message_encoding);
      JsonFormat.ADAPTER.encodeWithTag(writer, 6, value.json_format);
      EnforceNamingStyle.ADAPTER.encodeWithTag(writer, 7, value.enforce_naming_style);
      VisibilityFeature.DefaultSymbolVisibility.ADAPTER.encodeWithTag(writer, 8, value.default_symbol_visibility);
      ProtoLimitsFeature.EnforceProtoLimits.ADAPTER.encodeWithTag(writer, 9, value.enforce_proto_limits);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, FeatureSet value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoLimitsFeature.EnforceProtoLimits.ADAPTER.encodeWithTag(writer, 9, value.enforce_proto_limits);
      VisibilityFeature.DefaultSymbolVisibility.ADAPTER.encodeWithTag(writer, 8, value.default_symbol_visibility);
      EnforceNamingStyle.ADAPTER.encodeWithTag(writer, 7, value.enforce_naming_style);
      JsonFormat.ADAPTER.encodeWithTag(writer, 6, value.json_format);
      MessageEncoding.ADAPTER.encodeWithTag(writer, 5, value.message_encoding);
      Utf8Validation.ADAPTER.encodeWithTag(writer, 4, value.utf8_validation);
      RepeatedFieldEncoding.ADAPTER.encodeWithTag(writer, 3, value.repeated_field_encoding);
      EnumType.ADAPTER.encodeWithTag(writer, 2, value.enum_type);
      FieldPresence.ADAPTER.encodeWithTag(writer, 1, value.field_presence);
    }

    @Override
    public FeatureSet decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.field_presence(FieldPresence.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 2: {
            try {
              builder.enum_type(EnumType.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 3: {
            try {
              builder.repeated_field_encoding(RepeatedFieldEncoding.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 4: {
            try {
              builder.utf8_validation(Utf8Validation.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 5: {
            try {
              builder.message_encoding(MessageEncoding.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 6: {
            try {
              builder.json_format(JsonFormat.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 7: {
            try {
              builder.enforce_naming_style(EnforceNamingStyle.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 8: {
            try {
              builder.default_symbol_visibility(VisibilityFeature.DefaultSymbolVisibility.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 9: {
            try {
              builder.enforce_proto_limits(ProtoLimitsFeature.EnforceProtoLimits.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public FeatureSet redact(FeatureSet value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
