// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.kotlin.requiredextension.magnitude in squareup/proto3/kotlin/requiredextension/required_extension.proto
package com.squareup.wire.proto3.kotlin.requiredextension;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Syntax is proto3 so cannot write optional nor required.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface MagnitudeOption {
  int value();
}
