// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto2.java.interop.InteropUint64 in squareup/proto2/java/interop/interop_test.proto
package squareup.proto2.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class InteropUint64 extends Message<InteropUint64, InteropUint64.Builder> {
  public static final ProtoAdapter<InteropUint64> ADAPTER = new ProtoAdapter_InteropUint64();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_VALUE = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long value;

  public InteropUint64(Long value) {
    this(value, ByteString.EMPTY);
  }

  public InteropUint64(Long value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropUint64)) return false;
    InteropUint64 o = (InteropUint64) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (value != null ? value.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (value != null) builder.append(", value=").append(value);
    return builder.replace(0, 2, "InteropUint64{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropUint64, Builder> {
    public Long value;

    public Builder() {
    }

    public Builder value(Long value) {
      this.value = value;
      return this;
    }

    @Override
    public InteropUint64 build() {
      return new InteropUint64(value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropUint64 extends ProtoAdapter<InteropUint64> {
    public ProtoAdapter_InteropUint64() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropUint64.class, "type.googleapis.com/squareup.proto2.java.interop.InteropUint64", Syntax.PROTO_2, null, "squareup/proto2/java/interop/interop_test.proto");
    }

    @Override
    public int encodedSize(InteropUint64 value) {
      int result = 0;
      result += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.value);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropUint64 value) throws IOException {
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropUint64 value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.value);
    }

    @Override
    public InteropUint64 decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.value(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropUint64 redact(InteropUint64 value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
