// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto2.java.interop.InteropJsonName in squareup/proto2/java/interop/interop_test.proto
package squareup.proto2.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class InteropJsonName extends Message<InteropJsonName, InteropJsonName.Builder> {
  public static final ProtoAdapter<InteropJsonName> ADAPTER = new ProtoAdapter_InteropJsonName();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_A = "";

  public static final String DEFAULT_PUBLIC_ = "";

  public static final String DEFAULT_CAMEL_CASE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      jsonName = "one"
  )
  public final String a;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      declaredName = "public",
      jsonName = "two"
  )
  public final String public_;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      jsonName = "three"
  )
  public final String camel_case;

  public InteropJsonName(String a, String public_, String camel_case) {
    this(a, public_, camel_case, ByteString.EMPTY);
  }

  public InteropJsonName(String a, String public_, String camel_case, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.a = a;
    this.public_ = public_;
    this.camel_case = camel_case;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.a = a;
    builder.public_ = public_;
    builder.camel_case = camel_case;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropJsonName)) return false;
    InteropJsonName o = (InteropJsonName) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(a, o.a)
        && Internal.equals(public_, o.public_)
        && Internal.equals(camel_case, o.camel_case);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (a != null ? a.hashCode() : 0);
      result = result * 37 + (public_ != null ? public_.hashCode() : 0);
      result = result * 37 + (camel_case != null ? camel_case.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (a != null) builder.append(", a=").append(Internal.sanitize(a));
    if (public_ != null) builder.append(", public=").append(Internal.sanitize(public_));
    if (camel_case != null) builder.append(", camel_case=").append(Internal.sanitize(camel_case));
    return builder.replace(0, 2, "InteropJsonName{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropJsonName, Builder> {
    public String a;

    public String public_;

    public String camel_case;

    public Builder() {
    }

    public Builder a(String a) {
      this.a = a;
      return this;
    }

    public Builder public_(String public_) {
      this.public_ = public_;
      return this;
    }

    public Builder camel_case(String camel_case) {
      this.camel_case = camel_case;
      return this;
    }

    @Override
    public InteropJsonName build() {
      return new InteropJsonName(a, public_, camel_case, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropJsonName extends ProtoAdapter<InteropJsonName> {
    public ProtoAdapter_InteropJsonName() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropJsonName.class, "type.googleapis.com/squareup.proto2.java.interop.InteropJsonName", Syntax.PROTO_2, null, "squareup/proto2/java/interop/interop_test.proto");
    }

    @Override
    public int encodedSize(InteropJsonName value) {
      int result = 0;
      result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.a);
      result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.public_);
      result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.camel_case);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropJsonName value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.a);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.public_);
      ProtoAdapter.STRING.encodeWithTag(writer, 3, value.camel_case);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropJsonName value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.STRING.encodeWithTag(writer, 3, value.camel_case);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.public_);
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.a);
    }

    @Override
    public InteropJsonName decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.a(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.public_(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.camel_case(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropJsonName redact(InteropJsonName value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
