// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto2.java.interop.InteropMessage in squareup/proto2/java/interop/interop_message.proto
package squareup.proto2.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Map;
import okio.ByteString;
import squareup.proto2.java.interop.type.EnumProto2;
import squareup.proto2.java.interop.type.MessageProto2;
import squareup.proto3.java.interop.type.EnumProto3;
import squareup.proto3.java.interop.type.MessageProto3;

public final class InteropMessage extends Message<InteropMessage, InteropMessage.Builder> {
  public static final ProtoAdapter<InteropMessage> ADAPTER = new ProtoAdapter_InteropMessage();

  private static final long serialVersionUID = 0L;

  public static final EnumProto2 DEFAULT_OPT_PROTO2_ENUM = EnumProto2.UNKNOWN;

  public static final EnumProto3 DEFAULT_OPT_PROTO3_ENUM = EnumProto3.UNKNOWN;

  public static final EnumProto2 DEFAULT_REQ_PROTO2_ENUM = EnumProto2.UNKNOWN;

  public static final EnumProto3 DEFAULT_REQ_PROTO3_ENUM = EnumProto3.UNKNOWN;

  public static final EnumProto2 DEFAULT_EXT_OPT_PROTO2_ENUM = EnumProto2.UNKNOWN;

  public static final EnumProto3 DEFAULT_EXT_OPT_PROTO3_ENUM = EnumProto3.UNKNOWN;

  public static final EnumProto2 DEFAULT_ONEOF_PROTO2_ENUM = EnumProto2.UNKNOWN;

  public static final EnumProto3 DEFAULT_ONEOF_PROTO3_ENUM = EnumProto3.UNKNOWN;

  @WireField(
      tag = 1,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER"
  )
  public final EnumProto2 opt_proto2_enum;

  @WireField(
      tag = 2,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER"
  )
  public final MessageProto2 opt_proto2_message;

  @WireField(
      tag = 3,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER"
  )
  public final EnumProto3 opt_proto3_enum;

  @WireField(
      tag = 4,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER"
  )
  public final MessageProto3 opt_proto3_message;

  @WireField(
      tag = 101,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final EnumProto2 req_proto2_enum;

  @WireField(
      tag = 102,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final MessageProto2 req_proto2_message;

  @WireField(
      tag = 103,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final EnumProto3 req_proto3_enum;

  @WireField(
      tag = 104,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      label = WireField.Label.REQUIRED
  )
  public final MessageProto3 req_proto3_message;

  @WireField(
      tag = 201,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<EnumProto2> rep_proto2_enum;

  @WireField(
      tag = 202,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<MessageProto2> rep_proto2_message;

  @WireField(
      tag = 203,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<EnumProto3> rep_proto3_enum;

  @WireField(
      tag = 204,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<MessageProto3> rep_proto3_message;

  @WireField(
      tag = 301,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER",
      label = WireField.Label.PACKED
  )
  public final List<EnumProto2> pack_proto2_enum;

  @WireField(
      tag = 303,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.PACKED
  )
  public final List<EnumProto3> pack_proto3_enum;

  @WireField(
      tag = 501,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER"
  )
  public final Map<String, EnumProto2> map_string_proto2_enum;

  @WireField(
      tag = 502,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER"
  )
  public final Map<String, MessageProto2> map_string_proto2_message;

  @WireField(
      tag = 503,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER"
  )
  public final Map<String, EnumProto3> map_string_proto3_enum;

  @WireField(
      tag = 504,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER"
  )
  public final Map<String, MessageProto3> map_string_proto3_message;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1001,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER"
  )
  public final EnumProto2 ext_opt_proto2_enum;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1002,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER"
  )
  public final MessageProto2 ext_opt_proto2_message;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1003,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER"
  )
  public final EnumProto3 ext_opt_proto3_enum;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1004,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER"
  )
  public final MessageProto3 ext_opt_proto3_message;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1101,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<EnumProto2> ext_rep_proto2_enum;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1102,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<MessageProto2> ext_rep_proto2_message;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1103,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<EnumProto3> ext_rep_proto3_enum;

  /**
   * Extension source: squareup/proto2/java/interop/interop_message.proto
   */
  @WireField(
      tag = 1104,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<MessageProto3> ext_rep_proto3_message;

  @WireField(
      tag = 601,
      adapter = "squareup.proto2.java.interop.type.EnumProto2#ADAPTER",
      oneofName = "choice"
  )
  public final EnumProto2 oneof_proto2_enum;

  @WireField(
      tag = 602,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      oneofName = "choice"
  )
  public final MessageProto2 oneof_proto2_message;

  @WireField(
      tag = 603,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      oneofName = "choice"
  )
  public final EnumProto3 oneof_proto3_enum;

  @WireField(
      tag = 604,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      oneofName = "choice"
  )
  public final MessageProto3 oneof_proto3_message;

  public InteropMessage(Builder builder, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (Internal.countNonNull(builder.oneof_proto2_enum, builder.oneof_proto2_message, builder.oneof_proto3_enum, builder.oneof_proto3_message) > 1) {
      throw new IllegalArgumentException("at most one of builder.oneof_proto2_enum, builder.oneof_proto2_message, builder.oneof_proto3_enum, builder.oneof_proto3_message may be non-null");
    }
    this.opt_proto2_enum = builder.opt_proto2_enum;
    this.opt_proto2_message = builder.opt_proto2_message;
    this.opt_proto3_enum = builder.opt_proto3_enum;
    this.opt_proto3_message = builder.opt_proto3_message;
    this.req_proto2_enum = builder.req_proto2_enum;
    this.req_proto2_message = builder.req_proto2_message;
    this.req_proto3_enum = builder.req_proto3_enum;
    this.req_proto3_message = builder.req_proto3_message;
    this.rep_proto2_enum = Internal.immutableCopyOf("rep_proto2_enum", builder.rep_proto2_enum);
    this.rep_proto2_message = Internal.immutableCopyOf("rep_proto2_message", builder.rep_proto2_message);
    this.rep_proto3_enum = Internal.immutableCopyOf("rep_proto3_enum", builder.rep_proto3_enum);
    this.rep_proto3_message = Internal.immutableCopyOf("rep_proto3_message", builder.rep_proto3_message);
    this.pack_proto2_enum = Internal.immutableCopyOf("pack_proto2_enum", builder.pack_proto2_enum);
    this.pack_proto3_enum = Internal.immutableCopyOf("pack_proto3_enum", builder.pack_proto3_enum);
    this.map_string_proto2_enum = Internal.immutableCopyOf("map_string_proto2_enum", builder.map_string_proto2_enum);
    this.map_string_proto2_message = Internal.immutableCopyOf("map_string_proto2_message", builder.map_string_proto2_message);
    this.map_string_proto3_enum = Internal.immutableCopyOf("map_string_proto3_enum", builder.map_string_proto3_enum);
    this.map_string_proto3_message = Internal.immutableCopyOf("map_string_proto3_message", builder.map_string_proto3_message);
    this.ext_opt_proto2_enum = builder.ext_opt_proto2_enum;
    this.ext_opt_proto2_message = builder.ext_opt_proto2_message;
    this.ext_opt_proto3_enum = builder.ext_opt_proto3_enum;
    this.ext_opt_proto3_message = builder.ext_opt_proto3_message;
    this.ext_rep_proto2_enum = Internal.immutableCopyOf("ext_rep_proto2_enum", builder.ext_rep_proto2_enum);
    this.ext_rep_proto2_message = Internal.immutableCopyOf("ext_rep_proto2_message", builder.ext_rep_proto2_message);
    this.ext_rep_proto3_enum = Internal.immutableCopyOf("ext_rep_proto3_enum", builder.ext_rep_proto3_enum);
    this.ext_rep_proto3_message = Internal.immutableCopyOf("ext_rep_proto3_message", builder.ext_rep_proto3_message);
    this.oneof_proto2_enum = builder.oneof_proto2_enum;
    this.oneof_proto2_message = builder.oneof_proto2_message;
    this.oneof_proto3_enum = builder.oneof_proto3_enum;
    this.oneof_proto3_message = builder.oneof_proto3_message;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.opt_proto2_enum = opt_proto2_enum;
    builder.opt_proto2_message = opt_proto2_message;
    builder.opt_proto3_enum = opt_proto3_enum;
    builder.opt_proto3_message = opt_proto3_message;
    builder.req_proto2_enum = req_proto2_enum;
    builder.req_proto2_message = req_proto2_message;
    builder.req_proto3_enum = req_proto3_enum;
    builder.req_proto3_message = req_proto3_message;
    builder.rep_proto2_enum = Internal.copyOf(rep_proto2_enum);
    builder.rep_proto2_message = Internal.copyOf(rep_proto2_message);
    builder.rep_proto3_enum = Internal.copyOf(rep_proto3_enum);
    builder.rep_proto3_message = Internal.copyOf(rep_proto3_message);
    builder.pack_proto2_enum = Internal.copyOf(pack_proto2_enum);
    builder.pack_proto3_enum = Internal.copyOf(pack_proto3_enum);
    builder.map_string_proto2_enum = Internal.copyOf(map_string_proto2_enum);
    builder.map_string_proto2_message = Internal.copyOf(map_string_proto2_message);
    builder.map_string_proto3_enum = Internal.copyOf(map_string_proto3_enum);
    builder.map_string_proto3_message = Internal.copyOf(map_string_proto3_message);
    builder.ext_opt_proto2_enum = ext_opt_proto2_enum;
    builder.ext_opt_proto2_message = ext_opt_proto2_message;
    builder.ext_opt_proto3_enum = ext_opt_proto3_enum;
    builder.ext_opt_proto3_message = ext_opt_proto3_message;
    builder.ext_rep_proto2_enum = Internal.copyOf(ext_rep_proto2_enum);
    builder.ext_rep_proto2_message = Internal.copyOf(ext_rep_proto2_message);
    builder.ext_rep_proto3_enum = Internal.copyOf(ext_rep_proto3_enum);
    builder.ext_rep_proto3_message = Internal.copyOf(ext_rep_proto3_message);
    builder.oneof_proto2_enum = oneof_proto2_enum;
    builder.oneof_proto2_message = oneof_proto2_message;
    builder.oneof_proto3_enum = oneof_proto3_enum;
    builder.oneof_proto3_message = oneof_proto3_message;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropMessage)) return false;
    InteropMessage o = (InteropMessage) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(opt_proto2_enum, o.opt_proto2_enum)
        && Internal.equals(opt_proto2_message, o.opt_proto2_message)
        && Internal.equals(opt_proto3_enum, o.opt_proto3_enum)
        && Internal.equals(opt_proto3_message, o.opt_proto3_message)
        && req_proto2_enum.equals(o.req_proto2_enum)
        && req_proto2_message.equals(o.req_proto2_message)
        && req_proto3_enum.equals(o.req_proto3_enum)
        && req_proto3_message.equals(o.req_proto3_message)
        && rep_proto2_enum.equals(o.rep_proto2_enum)
        && rep_proto2_message.equals(o.rep_proto2_message)
        && rep_proto3_enum.equals(o.rep_proto3_enum)
        && rep_proto3_message.equals(o.rep_proto3_message)
        && pack_proto2_enum.equals(o.pack_proto2_enum)
        && pack_proto3_enum.equals(o.pack_proto3_enum)
        && map_string_proto2_enum.equals(o.map_string_proto2_enum)
        && map_string_proto2_message.equals(o.map_string_proto2_message)
        && map_string_proto3_enum.equals(o.map_string_proto3_enum)
        && map_string_proto3_message.equals(o.map_string_proto3_message)
        && Internal.equals(ext_opt_proto2_enum, o.ext_opt_proto2_enum)
        && Internal.equals(ext_opt_proto2_message, o.ext_opt_proto2_message)
        && Internal.equals(ext_opt_proto3_enum, o.ext_opt_proto3_enum)
        && Internal.equals(ext_opt_proto3_message, o.ext_opt_proto3_message)
        && ext_rep_proto2_enum.equals(o.ext_rep_proto2_enum)
        && ext_rep_proto2_message.equals(o.ext_rep_proto2_message)
        && ext_rep_proto3_enum.equals(o.ext_rep_proto3_enum)
        && ext_rep_proto3_message.equals(o.ext_rep_proto3_message)
        && Internal.equals(oneof_proto2_enum, o.oneof_proto2_enum)
        && Internal.equals(oneof_proto2_message, o.oneof_proto2_message)
        && Internal.equals(oneof_proto3_enum, o.oneof_proto3_enum)
        && Internal.equals(oneof_proto3_message, o.oneof_proto3_message);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (opt_proto2_enum != null ? opt_proto2_enum.hashCode() : 0);
      result = result * 37 + (opt_proto2_message != null ? opt_proto2_message.hashCode() : 0);
      result = result * 37 + (opt_proto3_enum != null ? opt_proto3_enum.hashCode() : 0);
      result = result * 37 + (opt_proto3_message != null ? opt_proto3_message.hashCode() : 0);
      result = result * 37 + req_proto2_enum.hashCode();
      result = result * 37 + req_proto2_message.hashCode();
      result = result * 37 + req_proto3_enum.hashCode();
      result = result * 37 + req_proto3_message.hashCode();
      result = result * 37 + rep_proto2_enum.hashCode();
      result = result * 37 + rep_proto2_message.hashCode();
      result = result * 37 + rep_proto3_enum.hashCode();
      result = result * 37 + rep_proto3_message.hashCode();
      result = result * 37 + pack_proto2_enum.hashCode();
      result = result * 37 + pack_proto3_enum.hashCode();
      result = result * 37 + map_string_proto2_enum.hashCode();
      result = result * 37 + map_string_proto2_message.hashCode();
      result = result * 37 + map_string_proto3_enum.hashCode();
      result = result * 37 + map_string_proto3_message.hashCode();
      result = result * 37 + (ext_opt_proto2_enum != null ? ext_opt_proto2_enum.hashCode() : 0);
      result = result * 37 + (ext_opt_proto2_message != null ? ext_opt_proto2_message.hashCode() : 0);
      result = result * 37 + (ext_opt_proto3_enum != null ? ext_opt_proto3_enum.hashCode() : 0);
      result = result * 37 + (ext_opt_proto3_message != null ? ext_opt_proto3_message.hashCode() : 0);
      result = result * 37 + ext_rep_proto2_enum.hashCode();
      result = result * 37 + ext_rep_proto2_message.hashCode();
      result = result * 37 + ext_rep_proto3_enum.hashCode();
      result = result * 37 + ext_rep_proto3_message.hashCode();
      result = result * 37 + (oneof_proto2_enum != null ? oneof_proto2_enum.hashCode() : 0);
      result = result * 37 + (oneof_proto2_message != null ? oneof_proto2_message.hashCode() : 0);
      result = result * 37 + (oneof_proto3_enum != null ? oneof_proto3_enum.hashCode() : 0);
      result = result * 37 + (oneof_proto3_message != null ? oneof_proto3_message.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (opt_proto2_enum != null) builder.append(", opt_proto2_enum=").append(opt_proto2_enum);
    if (opt_proto2_message != null) builder.append(", opt_proto2_message=").append(opt_proto2_message);
    if (opt_proto3_enum != null) builder.append(", opt_proto3_enum=").append(opt_proto3_enum);
    if (opt_proto3_message != null) builder.append(", opt_proto3_message=").append(opt_proto3_message);
    builder.append(", req_proto2_enum=").append(req_proto2_enum);
    builder.append(", req_proto2_message=").append(req_proto2_message);
    builder.append(", req_proto3_enum=").append(req_proto3_enum);
    builder.append(", req_proto3_message=").append(req_proto3_message);
    if (!rep_proto2_enum.isEmpty()) builder.append(", rep_proto2_enum=").append(rep_proto2_enum);
    if (!rep_proto2_message.isEmpty()) builder.append(", rep_proto2_message=").append(rep_proto2_message);
    if (!rep_proto3_enum.isEmpty()) builder.append(", rep_proto3_enum=").append(rep_proto3_enum);
    if (!rep_proto3_message.isEmpty()) builder.append(", rep_proto3_message=").append(rep_proto3_message);
    if (!pack_proto2_enum.isEmpty()) builder.append(", pack_proto2_enum=").append(pack_proto2_enum);
    if (!pack_proto3_enum.isEmpty()) builder.append(", pack_proto3_enum=").append(pack_proto3_enum);
    if (!map_string_proto2_enum.isEmpty()) builder.append(", map_string_proto2_enum=").append(map_string_proto2_enum);
    if (!map_string_proto2_message.isEmpty()) builder.append(", map_string_proto2_message=").append(map_string_proto2_message);
    if (!map_string_proto3_enum.isEmpty()) builder.append(", map_string_proto3_enum=").append(map_string_proto3_enum);
    if (!map_string_proto3_message.isEmpty()) builder.append(", map_string_proto3_message=").append(map_string_proto3_message);
    if (ext_opt_proto2_enum != null) builder.append(", ext_opt_proto2_enum=").append(ext_opt_proto2_enum);
    if (ext_opt_proto2_message != null) builder.append(", ext_opt_proto2_message=").append(ext_opt_proto2_message);
    if (ext_opt_proto3_enum != null) builder.append(", ext_opt_proto3_enum=").append(ext_opt_proto3_enum);
    if (ext_opt_proto3_message != null) builder.append(", ext_opt_proto3_message=").append(ext_opt_proto3_message);
    if (!ext_rep_proto2_enum.isEmpty()) builder.append(", ext_rep_proto2_enum=").append(ext_rep_proto2_enum);
    if (!ext_rep_proto2_message.isEmpty()) builder.append(", ext_rep_proto2_message=").append(ext_rep_proto2_message);
    if (!ext_rep_proto3_enum.isEmpty()) builder.append(", ext_rep_proto3_enum=").append(ext_rep_proto3_enum);
    if (!ext_rep_proto3_message.isEmpty()) builder.append(", ext_rep_proto3_message=").append(ext_rep_proto3_message);
    if (oneof_proto2_enum != null) builder.append(", oneof_proto2_enum=").append(oneof_proto2_enum);
    if (oneof_proto2_message != null) builder.append(", oneof_proto2_message=").append(oneof_proto2_message);
    if (oneof_proto3_enum != null) builder.append(", oneof_proto3_enum=").append(oneof_proto3_enum);
    if (oneof_proto3_message != null) builder.append(", oneof_proto3_message=").append(oneof_proto3_message);
    return builder.replace(0, 2, "InteropMessage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropMessage, Builder> {
    public EnumProto2 opt_proto2_enum;

    public MessageProto2 opt_proto2_message;

    public EnumProto3 opt_proto3_enum;

    public MessageProto3 opt_proto3_message;

    public EnumProto2 req_proto2_enum;

    public MessageProto2 req_proto2_message;

    public EnumProto3 req_proto3_enum;

    public MessageProto3 req_proto3_message;

    public List<EnumProto2> rep_proto2_enum;

    public List<MessageProto2> rep_proto2_message;

    public List<EnumProto3> rep_proto3_enum;

    public List<MessageProto3> rep_proto3_message;

    public List<EnumProto2> pack_proto2_enum;

    public List<EnumProto3> pack_proto3_enum;

    public Map<String, EnumProto2> map_string_proto2_enum;

    public Map<String, MessageProto2> map_string_proto2_message;

    public Map<String, EnumProto3> map_string_proto3_enum;

    public Map<String, MessageProto3> map_string_proto3_message;

    public EnumProto2 ext_opt_proto2_enum;

    public MessageProto2 ext_opt_proto2_message;

    public EnumProto3 ext_opt_proto3_enum;

    public MessageProto3 ext_opt_proto3_message;

    public List<EnumProto2> ext_rep_proto2_enum;

    public List<MessageProto2> ext_rep_proto2_message;

    public List<EnumProto3> ext_rep_proto3_enum;

    public List<MessageProto3> ext_rep_proto3_message;

    public EnumProto2 oneof_proto2_enum;

    public MessageProto2 oneof_proto2_message;

    public EnumProto3 oneof_proto3_enum;

    public MessageProto3 oneof_proto3_message;

    public Builder() {
      rep_proto2_enum = Internal.newMutableList();
      rep_proto2_message = Internal.newMutableList();
      rep_proto3_enum = Internal.newMutableList();
      rep_proto3_message = Internal.newMutableList();
      pack_proto2_enum = Internal.newMutableList();
      pack_proto3_enum = Internal.newMutableList();
      map_string_proto2_enum = Internal.newMutableMap();
      map_string_proto2_message = Internal.newMutableMap();
      map_string_proto3_enum = Internal.newMutableMap();
      map_string_proto3_message = Internal.newMutableMap();
      ext_rep_proto2_enum = Internal.newMutableList();
      ext_rep_proto2_message = Internal.newMutableList();
      ext_rep_proto3_enum = Internal.newMutableList();
      ext_rep_proto3_message = Internal.newMutableList();
    }

    public Builder opt_proto2_enum(EnumProto2 opt_proto2_enum) {
      this.opt_proto2_enum = opt_proto2_enum;
      return this;
    }

    public Builder opt_proto2_message(MessageProto2 opt_proto2_message) {
      this.opt_proto2_message = opt_proto2_message;
      return this;
    }

    public Builder opt_proto3_enum(EnumProto3 opt_proto3_enum) {
      this.opt_proto3_enum = opt_proto3_enum;
      return this;
    }

    public Builder opt_proto3_message(MessageProto3 opt_proto3_message) {
      this.opt_proto3_message = opt_proto3_message;
      return this;
    }

    public Builder req_proto2_enum(EnumProto2 req_proto2_enum) {
      this.req_proto2_enum = req_proto2_enum;
      return this;
    }

    public Builder req_proto2_message(MessageProto2 req_proto2_message) {
      this.req_proto2_message = req_proto2_message;
      return this;
    }

    public Builder req_proto3_enum(EnumProto3 req_proto3_enum) {
      this.req_proto3_enum = req_proto3_enum;
      return this;
    }

    public Builder req_proto3_message(MessageProto3 req_proto3_message) {
      this.req_proto3_message = req_proto3_message;
      return this;
    }

    public Builder rep_proto2_enum(List<EnumProto2> rep_proto2_enum) {
      Internal.checkElementsNotNull(rep_proto2_enum);
      this.rep_proto2_enum = rep_proto2_enum;
      return this;
    }

    public Builder rep_proto2_message(List<MessageProto2> rep_proto2_message) {
      Internal.checkElementsNotNull(rep_proto2_message);
      this.rep_proto2_message = rep_proto2_message;
      return this;
    }

    public Builder rep_proto3_enum(List<EnumProto3> rep_proto3_enum) {
      Internal.checkElementsNotNull(rep_proto3_enum);
      this.rep_proto3_enum = rep_proto3_enum;
      return this;
    }

    public Builder rep_proto3_message(List<MessageProto3> rep_proto3_message) {
      Internal.checkElementsNotNull(rep_proto3_message);
      this.rep_proto3_message = rep_proto3_message;
      return this;
    }

    public Builder pack_proto2_enum(List<EnumProto2> pack_proto2_enum) {
      Internal.checkElementsNotNull(pack_proto2_enum);
      this.pack_proto2_enum = pack_proto2_enum;
      return this;
    }

    public Builder pack_proto3_enum(List<EnumProto3> pack_proto3_enum) {
      Internal.checkElementsNotNull(pack_proto3_enum);
      this.pack_proto3_enum = pack_proto3_enum;
      return this;
    }

    public Builder map_string_proto2_enum(Map<String, EnumProto2> map_string_proto2_enum) {
      Internal.checkElementsNotNull(map_string_proto2_enum);
      this.map_string_proto2_enum = map_string_proto2_enum;
      return this;
    }

    public Builder map_string_proto2_message(Map<String, MessageProto2> map_string_proto2_message) {
      Internal.checkElementsNotNull(map_string_proto2_message);
      this.map_string_proto2_message = map_string_proto2_message;
      return this;
    }

    public Builder map_string_proto3_enum(Map<String, EnumProto3> map_string_proto3_enum) {
      Internal.checkElementsNotNull(map_string_proto3_enum);
      this.map_string_proto3_enum = map_string_proto3_enum;
      return this;
    }

    public Builder map_string_proto3_message(Map<String, MessageProto3> map_string_proto3_message) {
      Internal.checkElementsNotNull(map_string_proto3_message);
      this.map_string_proto3_message = map_string_proto3_message;
      return this;
    }

    public Builder ext_opt_proto2_enum(EnumProto2 ext_opt_proto2_enum) {
      this.ext_opt_proto2_enum = ext_opt_proto2_enum;
      return this;
    }

    public Builder ext_opt_proto2_message(MessageProto2 ext_opt_proto2_message) {
      this.ext_opt_proto2_message = ext_opt_proto2_message;
      return this;
    }

    public Builder ext_opt_proto3_enum(EnumProto3 ext_opt_proto3_enum) {
      this.ext_opt_proto3_enum = ext_opt_proto3_enum;
      return this;
    }

    public Builder ext_opt_proto3_message(MessageProto3 ext_opt_proto3_message) {
      this.ext_opt_proto3_message = ext_opt_proto3_message;
      return this;
    }

    public Builder ext_rep_proto2_enum(List<EnumProto2> ext_rep_proto2_enum) {
      Internal.checkElementsNotNull(ext_rep_proto2_enum);
      this.ext_rep_proto2_enum = ext_rep_proto2_enum;
      return this;
    }

    public Builder ext_rep_proto2_message(List<MessageProto2> ext_rep_proto2_message) {
      Internal.checkElementsNotNull(ext_rep_proto2_message);
      this.ext_rep_proto2_message = ext_rep_proto2_message;
      return this;
    }

    public Builder ext_rep_proto3_enum(List<EnumProto3> ext_rep_proto3_enum) {
      Internal.checkElementsNotNull(ext_rep_proto3_enum);
      this.ext_rep_proto3_enum = ext_rep_proto3_enum;
      return this;
    }

    public Builder ext_rep_proto3_message(List<MessageProto3> ext_rep_proto3_message) {
      Internal.checkElementsNotNull(ext_rep_proto3_message);
      this.ext_rep_proto3_message = ext_rep_proto3_message;
      return this;
    }

    public Builder oneof_proto2_enum(EnumProto2 oneof_proto2_enum) {
      this.oneof_proto2_enum = oneof_proto2_enum;
      this.oneof_proto2_message = null;
      this.oneof_proto3_enum = null;
      this.oneof_proto3_message = null;
      return this;
    }

    public Builder oneof_proto2_message(MessageProto2 oneof_proto2_message) {
      this.oneof_proto2_message = oneof_proto2_message;
      this.oneof_proto2_enum = null;
      this.oneof_proto3_enum = null;
      this.oneof_proto3_message = null;
      return this;
    }

    public Builder oneof_proto3_enum(EnumProto3 oneof_proto3_enum) {
      this.oneof_proto3_enum = oneof_proto3_enum;
      this.oneof_proto2_enum = null;
      this.oneof_proto2_message = null;
      this.oneof_proto3_message = null;
      return this;
    }

    public Builder oneof_proto3_message(MessageProto3 oneof_proto3_message) {
      this.oneof_proto3_message = oneof_proto3_message;
      this.oneof_proto2_enum = null;
      this.oneof_proto2_message = null;
      this.oneof_proto3_enum = null;
      return this;
    }

    @Override
    public InteropMessage build() {
      if (req_proto2_enum == null
          || req_proto2_message == null
          || req_proto3_enum == null
          || req_proto3_message == null) {
        throw Internal.missingRequiredFields(req_proto2_enum, "req_proto2_enum",
            req_proto2_message, "req_proto2_message",
            req_proto3_enum, "req_proto3_enum",
            req_proto3_message, "req_proto3_message");
      }
      return new InteropMessage(this, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropMessage extends ProtoAdapter<InteropMessage> {
    private ProtoAdapter<Map<String, EnumProto2>> map_string_proto2_enum;

    private ProtoAdapter<Map<String, MessageProto2>> map_string_proto2_message;

    private ProtoAdapter<Map<String, EnumProto3>> map_string_proto3_enum;

    private ProtoAdapter<Map<String, MessageProto3>> map_string_proto3_message;

    public ProtoAdapter_InteropMessage() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropMessage.class, "type.googleapis.com/squareup.proto2.java.interop.InteropMessage", Syntax.PROTO_2, null, "squareup/proto2/java/interop/interop_message.proto");
    }

    @Override
    public int encodedSize(InteropMessage value) {
      int result = 0;
      result += EnumProto2.ADAPTER.encodedSizeWithTag(1, value.opt_proto2_enum);
      result += MessageProto2.ADAPTER.encodedSizeWithTag(2, value.opt_proto2_message);
      result += EnumProto3.ADAPTER.encodedSizeWithTag(3, value.opt_proto3_enum);
      result += MessageProto3.ADAPTER.encodedSizeWithTag(4, value.opt_proto3_message);
      result += EnumProto2.ADAPTER.encodedSizeWithTag(101, value.req_proto2_enum);
      result += MessageProto2.ADAPTER.encodedSizeWithTag(102, value.req_proto2_message);
      result += EnumProto3.ADAPTER.encodedSizeWithTag(103, value.req_proto3_enum);
      result += MessageProto3.ADAPTER.encodedSizeWithTag(104, value.req_proto3_message);
      result += EnumProto2.ADAPTER.asRepeated().encodedSizeWithTag(201, value.rep_proto2_enum);
      result += MessageProto2.ADAPTER.asRepeated().encodedSizeWithTag(202, value.rep_proto2_message);
      result += EnumProto3.ADAPTER.asRepeated().encodedSizeWithTag(203, value.rep_proto3_enum);
      result += MessageProto3.ADAPTER.asRepeated().encodedSizeWithTag(204, value.rep_proto3_message);
      result += EnumProto2.ADAPTER.asPacked().encodedSizeWithTag(301, value.pack_proto2_enum);
      result += EnumProto3.ADAPTER.asPacked().encodedSizeWithTag(303, value.pack_proto3_enum);
      result += map_string_proto2_enumAdapter().encodedSizeWithTag(501, value.map_string_proto2_enum);
      result += map_string_proto2_messageAdapter().encodedSizeWithTag(502, value.map_string_proto2_message);
      result += map_string_proto3_enumAdapter().encodedSizeWithTag(503, value.map_string_proto3_enum);
      result += map_string_proto3_messageAdapter().encodedSizeWithTag(504, value.map_string_proto3_message);
      result += EnumProto2.ADAPTER.encodedSizeWithTag(1001, value.ext_opt_proto2_enum);
      result += MessageProto2.ADAPTER.encodedSizeWithTag(1002, value.ext_opt_proto2_message);
      result += EnumProto3.ADAPTER.encodedSizeWithTag(1003, value.ext_opt_proto3_enum);
      result += MessageProto3.ADAPTER.encodedSizeWithTag(1004, value.ext_opt_proto3_message);
      result += EnumProto2.ADAPTER.asRepeated().encodedSizeWithTag(1101, value.ext_rep_proto2_enum);
      result += MessageProto2.ADAPTER.asRepeated().encodedSizeWithTag(1102, value.ext_rep_proto2_message);
      result += EnumProto3.ADAPTER.asRepeated().encodedSizeWithTag(1103, value.ext_rep_proto3_enum);
      result += MessageProto3.ADAPTER.asRepeated().encodedSizeWithTag(1104, value.ext_rep_proto3_message);
      result += EnumProto2.ADAPTER.encodedSizeWithTag(601, value.oneof_proto2_enum);
      result += MessageProto2.ADAPTER.encodedSizeWithTag(602, value.oneof_proto2_message);
      result += EnumProto3.ADAPTER.encodedSizeWithTag(603, value.oneof_proto3_enum);
      result += MessageProto3.ADAPTER.encodedSizeWithTag(604, value.oneof_proto3_message);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropMessage value) throws IOException {
      EnumProto2.ADAPTER.encodeWithTag(writer, 1, value.opt_proto2_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 2, value.opt_proto2_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 3, value.opt_proto3_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 4, value.opt_proto3_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 101, value.req_proto2_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 102, value.req_proto2_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 103, value.req_proto3_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 104, value.req_proto3_message);
      EnumProto2.ADAPTER.asRepeated().encodeWithTag(writer, 201, value.rep_proto2_enum);
      MessageProto2.ADAPTER.asRepeated().encodeWithTag(writer, 202, value.rep_proto2_message);
      EnumProto3.ADAPTER.asRepeated().encodeWithTag(writer, 203, value.rep_proto3_enum);
      MessageProto3.ADAPTER.asRepeated().encodeWithTag(writer, 204, value.rep_proto3_message);
      EnumProto2.ADAPTER.asPacked().encodeWithTag(writer, 301, value.pack_proto2_enum);
      EnumProto3.ADAPTER.asPacked().encodeWithTag(writer, 303, value.pack_proto3_enum);
      map_string_proto2_enumAdapter().encodeWithTag(writer, 501, value.map_string_proto2_enum);
      map_string_proto2_messageAdapter().encodeWithTag(writer, 502, value.map_string_proto2_message);
      map_string_proto3_enumAdapter().encodeWithTag(writer, 503, value.map_string_proto3_enum);
      map_string_proto3_messageAdapter().encodeWithTag(writer, 504, value.map_string_proto3_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 1001, value.ext_opt_proto2_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 1002, value.ext_opt_proto2_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 1003, value.ext_opt_proto3_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 1004, value.ext_opt_proto3_message);
      EnumProto2.ADAPTER.asRepeated().encodeWithTag(writer, 1101, value.ext_rep_proto2_enum);
      MessageProto2.ADAPTER.asRepeated().encodeWithTag(writer, 1102, value.ext_rep_proto2_message);
      EnumProto3.ADAPTER.asRepeated().encodeWithTag(writer, 1103, value.ext_rep_proto3_enum);
      MessageProto3.ADAPTER.asRepeated().encodeWithTag(writer, 1104, value.ext_rep_proto3_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 601, value.oneof_proto2_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 602, value.oneof_proto2_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 603, value.oneof_proto3_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 604, value.oneof_proto3_message);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropMessage value) throws IOException {
      writer.writeBytes(value.unknownFields());
      MessageProto3.ADAPTER.encodeWithTag(writer, 604, value.oneof_proto3_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 603, value.oneof_proto3_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 602, value.oneof_proto2_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 601, value.oneof_proto2_enum);
      MessageProto3.ADAPTER.asRepeated().encodeWithTag(writer, 1104, value.ext_rep_proto3_message);
      EnumProto3.ADAPTER.asRepeated().encodeWithTag(writer, 1103, value.ext_rep_proto3_enum);
      MessageProto2.ADAPTER.asRepeated().encodeWithTag(writer, 1102, value.ext_rep_proto2_message);
      EnumProto2.ADAPTER.asRepeated().encodeWithTag(writer, 1101, value.ext_rep_proto2_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 1004, value.ext_opt_proto3_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 1003, value.ext_opt_proto3_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 1002, value.ext_opt_proto2_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 1001, value.ext_opt_proto2_enum);
      map_string_proto3_messageAdapter().encodeWithTag(writer, 504, value.map_string_proto3_message);
      map_string_proto3_enumAdapter().encodeWithTag(writer, 503, value.map_string_proto3_enum);
      map_string_proto2_messageAdapter().encodeWithTag(writer, 502, value.map_string_proto2_message);
      map_string_proto2_enumAdapter().encodeWithTag(writer, 501, value.map_string_proto2_enum);
      EnumProto3.ADAPTER.asPacked().encodeWithTag(writer, 303, value.pack_proto3_enum);
      EnumProto2.ADAPTER.asPacked().encodeWithTag(writer, 301, value.pack_proto2_enum);
      MessageProto3.ADAPTER.asRepeated().encodeWithTag(writer, 204, value.rep_proto3_message);
      EnumProto3.ADAPTER.asRepeated().encodeWithTag(writer, 203, value.rep_proto3_enum);
      MessageProto2.ADAPTER.asRepeated().encodeWithTag(writer, 202, value.rep_proto2_message);
      EnumProto2.ADAPTER.asRepeated().encodeWithTag(writer, 201, value.rep_proto2_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 104, value.req_proto3_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 103, value.req_proto3_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 102, value.req_proto2_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 101, value.req_proto2_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 4, value.opt_proto3_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 3, value.opt_proto3_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 2, value.opt_proto2_message);
      EnumProto2.ADAPTER.encodeWithTag(writer, 1, value.opt_proto2_enum);
    }

    @Override
    public InteropMessage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.opt_proto2_enum(EnumProto2.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 2: builder.opt_proto2_message(Internal.decodeMessageOrMerge(MessageProto2.ADAPTER, reader, builder.opt_proto2_message)); break;
          case 3: {
            try {
              builder.opt_proto3_enum(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 4: builder.opt_proto3_message(Internal.decodeMessageOrMerge(MessageProto3.ADAPTER, reader, builder.opt_proto3_message)); break;
          case 101: {
            try {
              builder.req_proto2_enum(EnumProto2.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 102: builder.req_proto2_message(Internal.decodeMessageOrMerge(MessageProto2.ADAPTER, reader, builder.req_proto2_message)); break;
          case 103: {
            try {
              builder.req_proto3_enum(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 104: builder.req_proto3_message(Internal.decodeMessageOrMerge(MessageProto3.ADAPTER, reader, builder.req_proto3_message)); break;
          case 201: {
            try {
              builder.rep_proto2_enum.add(EnumProto2.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 202: builder.rep_proto2_message.add(MessageProto2.ADAPTER.decode(reader)); break;
          case 203: {
            try {
              builder.rep_proto3_enum.add(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 204: builder.rep_proto3_message.add(MessageProto3.ADAPTER.decode(reader)); break;
          case 301: {
            try {
              EnumProto2.ADAPTER.tryDecode(reader, builder.pack_proto2_enum);
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 303: {
            try {
              EnumProto3.ADAPTER.tryDecode(reader, builder.pack_proto3_enum);
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 501: builder.map_string_proto2_enum.putAll(map_string_proto2_enumAdapter().decode(reader)); break;
          case 502: builder.map_string_proto2_message.putAll(map_string_proto2_messageAdapter().decode(reader)); break;
          case 503: builder.map_string_proto3_enum.putAll(map_string_proto3_enumAdapter().decode(reader)); break;
          case 504: builder.map_string_proto3_message.putAll(map_string_proto3_messageAdapter().decode(reader)); break;
          case 601: {
            try {
              builder.oneof_proto2_enum(EnumProto2.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 602: builder.oneof_proto2_message(Internal.decodeMessageOrMerge(MessageProto2.ADAPTER, reader, builder.oneof_proto2_message)); break;
          case 603: {
            try {
              builder.oneof_proto3_enum(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 604: builder.oneof_proto3_message(Internal.decodeMessageOrMerge(MessageProto3.ADAPTER, reader, builder.oneof_proto3_message)); break;
          case 1001: {
            try {
              builder.ext_opt_proto2_enum(EnumProto2.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 1002: builder.ext_opt_proto2_message(Internal.decodeMessageOrMerge(MessageProto2.ADAPTER, reader, builder.ext_opt_proto2_message)); break;
          case 1003: {
            try {
              builder.ext_opt_proto3_enum(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 1004: builder.ext_opt_proto3_message(Internal.decodeMessageOrMerge(MessageProto3.ADAPTER, reader, builder.ext_opt_proto3_message)); break;
          case 1101: {
            try {
              builder.ext_rep_proto2_enum.add(EnumProto2.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 1102: builder.ext_rep_proto2_message.add(MessageProto2.ADAPTER.decode(reader)); break;
          case 1103: {
            try {
              builder.ext_rep_proto3_enum.add(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 1104: builder.ext_rep_proto3_message.add(MessageProto3.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropMessage redact(InteropMessage value) {
      Builder builder = value.newBuilder();
      if (builder.opt_proto2_message != null) builder.opt_proto2_message = MessageProto2.ADAPTER.redact(builder.opt_proto2_message);
      if (builder.opt_proto3_message != null) builder.opt_proto3_message = MessageProto3.ADAPTER.redact(builder.opt_proto3_message);
      builder.req_proto2_message = MessageProto2.ADAPTER.redact(builder.req_proto2_message);
      builder.req_proto3_message = MessageProto3.ADAPTER.redact(builder.req_proto3_message);
      Internal.redactElements(builder.rep_proto2_message, MessageProto2.ADAPTER);
      Internal.redactElements(builder.rep_proto3_message, MessageProto3.ADAPTER);
      Internal.redactElements(builder.map_string_proto2_message, MessageProto2.ADAPTER);
      Internal.redactElements(builder.map_string_proto3_message, MessageProto3.ADAPTER);
      if (builder.ext_opt_proto2_message != null) builder.ext_opt_proto2_message = MessageProto2.ADAPTER.redact(builder.ext_opt_proto2_message);
      if (builder.ext_opt_proto3_message != null) builder.ext_opt_proto3_message = MessageProto3.ADAPTER.redact(builder.ext_opt_proto3_message);
      Internal.redactElements(builder.ext_rep_proto2_message, MessageProto2.ADAPTER);
      Internal.redactElements(builder.ext_rep_proto3_message, MessageProto3.ADAPTER);
      if (builder.oneof_proto2_message != null) builder.oneof_proto2_message = MessageProto2.ADAPTER.redact(builder.oneof_proto2_message);
      if (builder.oneof_proto3_message != null) builder.oneof_proto3_message = MessageProto3.ADAPTER.redact(builder.oneof_proto3_message);
      builder.clearUnknownFields();
      return builder.build();
    }

    private ProtoAdapter<Map<String, EnumProto2>> map_string_proto2_enumAdapter() {
      ProtoAdapter<Map<String, EnumProto2>> result = map_string_proto2_enum;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, EnumProto2.ADAPTER);
        map_string_proto2_enum = result;
      }
      return result;
    }

    private ProtoAdapter<Map<String, MessageProto2>> map_string_proto2_messageAdapter() {
      ProtoAdapter<Map<String, MessageProto2>> result = map_string_proto2_message;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, MessageProto2.ADAPTER);
        map_string_proto2_message = result;
      }
      return result;
    }

    private ProtoAdapter<Map<String, EnumProto3>> map_string_proto3_enumAdapter() {
      ProtoAdapter<Map<String, EnumProto3>> result = map_string_proto3_enum;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, EnumProto3.ADAPTER);
        map_string_proto3_enum = result;
      }
      return result;
    }

    private ProtoAdapter<Map<String, MessageProto3>> map_string_proto3_messageAdapter() {
      ProtoAdapter<Map<String, MessageProto3>> result = map_string_proto3_message;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, MessageProto3.ADAPTER);
        map_string_proto3_message = result;
      }
      return result;
    }
  }
}
