// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto2.java.interop.SubInteropRepeatedUint in squareup/proto2/java/interop/interop_test.proto
package squareup.proto2.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class SubInteropRepeatedUint extends Message<SubInteropRepeatedUint, SubInteropRepeatedUint.Builder> {
  public static final ProtoAdapter<SubInteropRepeatedUint> ADAPTER = new ProtoAdapter_SubInteropRepeatedUint();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.PACKED
  )
  public final List<Integer> repeated_values;

  public SubInteropRepeatedUint(List<Integer> repeated_values) {
    this(repeated_values, ByteString.EMPTY);
  }

  public SubInteropRepeatedUint(List<Integer> repeated_values, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.repeated_values = Internal.immutableCopyOf("repeated_values", repeated_values);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.repeated_values = Internal.copyOf(repeated_values);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SubInteropRepeatedUint)) return false;
    SubInteropRepeatedUint o = (SubInteropRepeatedUint) other;
    return unknownFields().equals(o.unknownFields())
        && repeated_values.equals(o.repeated_values);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + repeated_values.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!repeated_values.isEmpty()) builder.append(", repeated_values=").append(repeated_values);
    return builder.replace(0, 2, "SubInteropRepeatedUint{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SubInteropRepeatedUint, Builder> {
    public List<Integer> repeated_values;

    public Builder() {
      repeated_values = Internal.newMutableList();
    }

    public Builder repeated_values(List<Integer> repeated_values) {
      Internal.checkElementsNotNull(repeated_values);
      this.repeated_values = repeated_values;
      return this;
    }

    @Override
    public SubInteropRepeatedUint build() {
      return new SubInteropRepeatedUint(repeated_values, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SubInteropRepeatedUint extends ProtoAdapter<SubInteropRepeatedUint> {
    public ProtoAdapter_SubInteropRepeatedUint() {
      super(FieldEncoding.LENGTH_DELIMITED, SubInteropRepeatedUint.class, "type.googleapis.com/squareup.proto2.java.interop.SubInteropRepeatedUint", Syntax.PROTO_2, null, "squareup/proto2/java/interop/interop_test.proto");
    }

    @Override
    public int encodedSize(SubInteropRepeatedUint value) {
      int result = 0;
      result += ProtoAdapter.UINT32.asPacked().encodedSizeWithTag(1, value.repeated_values);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, SubInteropRepeatedUint value) throws IOException {
      ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 1, value.repeated_values);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, SubInteropRepeatedUint value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 1, value.repeated_values);
    }

    @Override
    public SubInteropRepeatedUint decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: ProtoAdapter.UINT32.tryDecode(reader, builder.repeated_values); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public SubInteropRepeatedUint redact(SubInteropRepeatedUint value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
