// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.options.poem.Poem in poem.proto
package squareup.options.poem;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Deprecated;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;
import squareup.options.misc.MessageExportEnabledOption;
import squareup.options.misc.RelevantOption;

@MessageExportEnabledOption(false)
public final class Poem extends Message<Poem, Poem.Builder> {
  public static final ProtoAdapter<Poem> ADAPTER = new ProtoAdapter_Poem();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_TITLE = "";

  public static final Style DEFAULT_STYLE = Style.LONG;

  public static final Boolean DEFAULT_ABOUT_LOVE = true;

  public static final String DEFAULT_SIGNATURE = "BQ";

  @RelevantOption(true)
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String title;

  @WireField(
      tag = 2,
      adapter = "squareup.options.poem.Style#ADAPTER"
  )
  public final Style style;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean about_love;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.PACKED
  )
  @Deprecated
  public final List<Integer> path;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String signature;

  public Poem(String title, Style style, Boolean about_love, List<Integer> path, String signature) {
    this(title, style, about_love, path, signature, ByteString.EMPTY);
  }

  public Poem(String title, Style style, Boolean about_love, List<Integer> path, String signature,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.title = title;
    this.style = style;
    this.about_love = about_love;
    this.path = Internal.immutableCopyOf("path", path);
    this.signature = signature;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.title = title;
    builder.style = style;
    builder.about_love = about_love;
    builder.path = Internal.copyOf(path);
    builder.signature = signature;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Poem)) return false;
    Poem o = (Poem) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(title, o.title)
        && Internal.equals(style, o.style)
        && Internal.equals(about_love, o.about_love)
        && path.equals(o.path)
        && Internal.equals(signature, o.signature);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (title != null ? title.hashCode() : 0);
      result = result * 37 + (style != null ? style.hashCode() : 0);
      result = result * 37 + (about_love != null ? about_love.hashCode() : 0);
      result = result * 37 + path.hashCode();
      result = result * 37 + (signature != null ? signature.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (title != null) builder.append(", title=").append(Internal.sanitize(title));
    if (style != null) builder.append(", style=").append(style);
    if (about_love != null) builder.append(", about_love=").append(about_love);
    if (!path.isEmpty()) builder.append(", path=").append(path);
    if (signature != null) builder.append(", signature=").append(Internal.sanitize(signature));
    return builder.replace(0, 2, "Poem{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Poem, Builder> {
    public String title;

    public Style style;

    public Boolean about_love;

    public List<Integer> path;

    public String signature;

    public Builder() {
      path = Internal.newMutableList();
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder style(Style style) {
      this.style = style;
      return this;
    }

    public Builder about_love(Boolean about_love) {
      this.about_love = about_love;
      return this;
    }

    @Deprecated
    public Builder path(List<Integer> path) {
      Internal.checkElementsNotNull(path);
      this.path = path;
      return this;
    }

    public Builder signature(String signature) {
      this.signature = signature;
      return this;
    }

    @Override
    public Poem build() {
      return new Poem(title, style, about_love, path, signature, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Poem extends ProtoAdapter<Poem> {
    public ProtoAdapter_Poem() {
      super(FieldEncoding.LENGTH_DELIMITED, Poem.class, "type.googleapis.com/squareup.options.poem.Poem", Syntax.PROTO_2, null, "poem.proto");
    }

    @Override
    public int encodedSize(Poem value) {
      int result = 0;
      result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.title);
      result += Style.ADAPTER.encodedSizeWithTag(2, value.style);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.about_love);
      result += ProtoAdapter.INT32.asPacked().encodedSizeWithTag(4, value.path);
      result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.signature);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, Poem value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.title);
      Style.ADAPTER.encodeWithTag(writer, 2, value.style);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.about_love);
      ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 4, value.path);
      ProtoAdapter.STRING.encodeWithTag(writer, 5, value.signature);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, Poem value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.STRING.encodeWithTag(writer, 5, value.signature);
      ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 4, value.path);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.about_love);
      Style.ADAPTER.encodeWithTag(writer, 2, value.style);
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.title);
    }

    @Override
    public Poem decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.title(ProtoAdapter.STRING.decode(reader)); break;
          case 2: {
            try {
              builder.style(Style.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 3: builder.about_love(ProtoAdapter.BOOL.decode(reader)); break;
          case 4: ProtoAdapter.INT32.tryDecode(reader, builder.path); break;
          case 5: builder.signature(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public Poem redact(Poem value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
