// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.options.poem.Style in poem.proto
package squareup.options.poem;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;
import squareup.options.misc.TextAlignmentOption;

public enum Style implements WireEnum {
  @TextAlignmentOption(3)
  SHORT(1),

  @TextAlignmentOption(4)
  LONG(2);

  public static final ProtoAdapter<Style> ADAPTER = new ProtoAdapter_Style();

  private final int value;

  Style(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static Style fromValue(int value) {
    switch (value) {
      case 1: return SHORT;
      case 2: return LONG;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_Style extends EnumAdapter<Style> {
    ProtoAdapter_Style() {
      super(Style.class, Syntax.PROTO_2, null);
    }

    @Override
    protected Style fromValue(int value) {
      return Style.fromValue(value);
    }
  }
}
