/*
 * Copyright (C) 2013 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.squareup.wire;

import com.squareup.wire.schema.CoreLoader;
import com.squareup.wire.schema.CustomTarget;
import com.squareup.wire.schema.EventListenersKt;
import com.squareup.wire.schema.JavaTarget;
import com.squareup.wire.schema.Location;
import com.squareup.wire.schema.PruningRules;
import com.squareup.wire.schema.Target;
import com.squareup.wire.schema.WireLoggersKt;
import com.squareup.wire.schema.WireRun;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import okio.BufferedSource;
import okio.FileSystem;
import okio.Okio;
import okio.Path;

/**
 * Command line interface to the Wire Java generator.
 *
 * <p>Usage
 *
 * <pre>{@code
 * java WireCompiler --proto_path=<path>
 *   [--java_out=<path>]
 *   [--custom_out=<path>]
 *   [--schema_handler_factory_class=<class_name>]
 *   [--files=<protos.include>]
 *   [--includes=<message_name>[,<message_name>...]]
 *   [--excludes=<message_name>[,<message_name>...]]
 *   [--android]
 *   [--android-annotations]
 *   [--compact]
 *   [--custom_option=<key>,<value>]
 *   [file [file...]]
 * }</pre>
 *
 * <p>{@code --java_out} should provide the folder where the files generated by the Java code
 * generator should be placed.
 *
 * <p>{@code --event_listener_factory_class} should be used if you want to add a {@link
 * com.squareup.wire.schema.EventListener}. The factory class itself should be included in your
 * classpath.
 *
 * <p>{@code --logger_factory_class} should be used if you want a custom {@link WireLogger} to be
 * called. The factory class itself should be included in your classpath.
 *
 * <p>{@code --schema_handler_factory_class} should be used if you want a custom {@link
 * com.squareup.wire.schema.SchemaHandler} to be called. The factory class itself should be
 * included in your classpath. If set, {@code custom_out} should also be provided and will passed
 * to the factory's handler as a location to where it will be able to write files.
 *
 * <p>If the {@code --includes} flag is present, its argument must be a comma-separated list of
 * fully-qualified message or enum names. The output will be limited to those messages and enums
 * that are (transitive) dependencies of the listed names. The {@code --excludes} flag excludes
 * types, and takes precedence over {@code --includes}.
 *
 * <p>The {@code --dry_run} flag causes the compiler to just emit the names of the source files
 * that would be generated to stdout.
 *
 * <p>The {@code --android} flag will cause all messages to implement the {@code Parcelable}
 * interface. This implies {@code --android-annotations} as well.
 *
 * <p>The {@code --android-annotations} flag will add the {@code Nullable} annotation to optional
 * fields.
 *
 * <p>The {@code --opaque_types} takes a list of qualified named Protobuf types separated by a
 * ','. All types in the list will be evaluated as being of type {@code bytes}. On code generation,
 * the fields of such types will be using the platform equivalent of {@code bytes}, like {@code
 * okio.ByteString} for the JVM. Note that scalar types cannot be opaqued. The opaque step will
 * happen before the tree shaking one.
 *
 * <p>The {@code --compact} flag will emit code that uses reflection for reading, writing, and
 * toString methods which are normally implemented with code generation.
 *
 * <p>The {@code --custom_option} flag will be passed onto the custom {@link
 * com.squareup.wire.schema.SchemaHandler} if set. The flag can be used as many times as needed and
 * all key/value pairs will be aggregated into a map.
 *
 * <p>Port note: the Kotlin and Swift code generators are excluded from this port (DEC-6), so the
 * {@code --kotlin_out}, {@code --swift_out}, and related flags are rejected instead of being
 * honored.
 */
public final class WireCompiler {
  final FileSystem fs;
  private final WireLogger log;
  private final List<String> protoPaths;
  private final String javaOut;
  private final String customOut;
  private final String schemaHandlerFactoryClass;
  private final List<String> sourceFileNames;
  private final List<String> treeShakingRoots;
  private final List<String> treeShakingRubbish;
  private final boolean rejectUnusedRootsOrPrunes;
  private final Map<String, WireRun.Module> modules;
  final boolean emitAndroid;
  final boolean emitAndroidAnnotations;
  private final boolean emitCompact;
  private final boolean emitDeclaredOptions;
  private final boolean emitAppliedOptions;
  private final boolean permitPackageCycles;
  private final boolean loadExhaustively;
  private final boolean javaExclusive;
  private final List<String> eventListenerFactoryClasses;
  private final Map<String, String> customOptions;
  private final List<String> opaqueTypes;

  WireCompiler(
      FileSystem fs,
      WireLogger log,
      List<String> protoPaths,
      String javaOut,
      String customOut,
      String schemaHandlerFactoryClass,
      List<String> sourceFileNames,
      List<String> treeShakingRoots,
      List<String> treeShakingRubbish,
      boolean rejectUnusedRootsOrPrunes,
      Map<String, WireRun.Module> modules,
      boolean emitAndroid,
      boolean emitAndroidAnnotations,
      boolean emitCompact,
      boolean emitDeclaredOptions,
      boolean emitAppliedOptions,
      boolean permitPackageCycles,
      boolean loadExhaustively,
      boolean javaExclusive,
      List<String> eventListenerFactoryClasses,
      Map<String, String> customOptions,
      List<String> opaqueTypes) {
    this.fs = fs;
    this.log = log;
    this.protoPaths = protoPaths;
    this.javaOut = javaOut;
    this.customOut = customOut;
    this.schemaHandlerFactoryClass = schemaHandlerFactoryClass;
    this.sourceFileNames = sourceFileNames;
    this.treeShakingRoots = treeShakingRoots;
    this.treeShakingRubbish = treeShakingRubbish;
    this.rejectUnusedRootsOrPrunes = rejectUnusedRootsOrPrunes;
    this.modules = modules;
    this.emitAndroid = emitAndroid;
    this.emitAndroidAnnotations = emitAndroidAnnotations;
    this.emitCompact = emitCompact;
    this.emitDeclaredOptions = emitDeclaredOptions;
    this.emitAppliedOptions = emitAppliedOptions;
    this.permitPackageCycles = permitPackageCycles;
    this.loadExhaustively = loadExhaustively;
    this.javaExclusive = javaExclusive;
    this.eventListenerFactoryClasses = eventListenerFactoryClasses;
    this.customOptions = customOptions;
    this.opaqueTypes = opaqueTypes;
  }

  public void compile() throws IOException {
    WireRun wireRun = createRun();
    wireRun.execute(fs, log);
  }

  public WireRun createRun() throws IOException {
    List<Target> targets = new ArrayList<>();
    if (javaOut != null) {
      targets.add(new JavaTarget(
          Collections.singletonList("*"),
          Collections.emptyList(),
          javaExclusive,
          javaOut,
          emitAndroid,
          emitAndroidAnnotations,
          emitCompact,
          emitDeclaredOptions,
          emitAppliedOptions,
          false /* buildersOnly */));
    }
    if (customOut != null || schemaHandlerFactoryClass != null) {
      if (customOut == null || schemaHandlerFactoryClass == null) {
        throw new IllegalArgumentException(
            "Both custom_out and schema_handler_factory_class need to be set");
      }
      targets.add(new CustomTarget(
          Collections.singletonList("*"),
          Collections.emptyList(),
          true /* exclusive */,
          customOut,
          customOptions,
          CustomTarget.newSchemaHandler(schemaHandlerFactoryClass)));
    }

    List<Path> sources = new ArrayList<>();
    for (String protoPath : protoPaths) {
      sources.add(Path.get(protoPath));
    }

    List<Location> allDirectories = new ArrayList<>();
    for (Path source : sources) {
      allDirectories.add(Location.get(source.toString()));
    }
    List<Location> sourcePath;
    List<Location> protoPath;

    if (!sourceFileNames.isEmpty()) {
      sourcePath = new ArrayList<>();
      for (String sourceFileName : sourceFileNames) {
        sourcePath.add(locationOfProto(sources, sourceFileName));
      }
      protoPath = allDirectories;
    } else {
      sourcePath = allDirectories;
      protoPath = Collections.emptyList();
    }

    List<com.squareup.wire.schema.EventListener> eventListeners = new ArrayList<>();
    for (String eventListenerFactoryClass : eventListenerFactoryClasses) {
      eventListeners.add(
          EventListenersKt.newEventListenerFactory(eventListenerFactoryClass).create());
    }

    return new WireRun(
        sourcePath,
        protoPath,
        treeShakingRoots,
        treeShakingRubbish,
        Collections.emptyList() /* moves */,
        null /* sinceVersion */,
        null /* untilVersion */,
        null /* onlyVersion */,
        targets,
        modules,
        permitPackageCycles,
        loadExhaustively,
        false /* escapeKotlinKeywords */,
        eventListeners,
        rejectUnusedRootsOrPrunes,
        opaqueTypes);
  }

  /** Searches {@code sources} trying to resolve {@code proto}. Returns the location if found. */
  private Location locationOfProto(List<Path> sources, String proto) throws IOException {
    // We cache ZIP openings because they are expensive.
    Map<Path, FileSystem> sourceToZipFileSystem = new LinkedHashMap<>();
    for (Path source : sources) {
      if (isRegularFile(source)) {
        sourceToZipFileSystem.put(source, fs.openZip(source));
      }
    }

    Path directoryEntry = null;
    for (Path source : sources) {
      FileSystem zip = sourceToZipFileSystem.get(source);
      boolean exists = zip != null
          ? zip.exists(Path.get("/").div(proto))
          : fs.exists(source.div(proto));
      if (exists) {
        directoryEntry = source;
        break;
      }
    }

    if (directoryEntry == null) {
      if (CoreLoader.isWireRuntimeProto(proto)) {
        return Location.get(CoreLoader.WIRE_RUNTIME_JAR, proto);
      }
      throw new FileNotFoundException("Failed to locate " + proto + " in " + sources);
    }

    return Location.get(directoryEntry.toString(), proto);
  }

  private boolean isRegularFile(Path path) throws IOException {
    return fs.metadataOrNull(path) != null
        && Boolean.TRUE.equals(fs.metadataOrNull(path).isRegularFile);
  }

  public static final String CODE_GENERATED_BY_WIRE =
      "Code generated by Wire protocol buffer compiler, do not edit.";

  private static final String PROTO_PATH_FLAG = "--proto_path=";
  private static final String JAVA_OUT_FLAG = "--java_out=";
  private static final String CUSTOM_OUT_FLAG = "--custom_out=";
  private static final String SCHEMA_HANDLER_FACTORY_CLASS_FLAG = "--schema_handler_factory_class=";
  private static final String FILES_FLAG = "--files=";
  private static final String INCLUDES_FLAG = "--includes=";
  private static final String EXCLUDES_FLAG = "--excludes=";
  private static final String MANIFEST_FLAG = "--experimental-module-manifest=";
  private static final String EVENT_LISTENER_FACTORY_CLASS_FLAG = "--event_listener_factory_class=";
  private static final String LOGGER_FACTORY_CLASS_FLAG = "--logger_factory_class=";
  private static final String ANDROID = "--android";
  private static final String ANDROID_ANNOTATIONS = "--android-annotations";
  private static final String COMPACT = "--compact";
  private static final String SKIP_DECLARED_OPTIONS = "--skip_declared_options";
  private static final String SKIP_APPLIED_OPTIONS = "--skip_applied_options";
  private static final String PERMIT_PACKAGE_CYCLES_OPTIONS = "--permit_package_cycles";
  private static final String LOAD_EXHAUSTIVELY = "--load_exhaustively";
  private static final String DRY_RUN = "--dry_run";
  private static final String NO_JAVA_EXCLUSIVE = "--no_java_exclusive";
  private static final String CUSTOM_OPTION_FLAG = "--custom_option=";
  private static final String OPAQUE_TYPES_FLAG = "--opaque_types=";
  private static final String IGNORE_UNUSED_ROOTS_AND_PRUNES = "--ignore_unused_roots_and_prunes";

  public Map<String, String> getCustomOptions() {
    return customOptions;
  }

  public String getCustomOut() {
    return customOut;
  }

  public boolean getEmitAppliedOptions() {
    return emitAppliedOptions;
  }

  public boolean getEmitCompact() {
    return emitCompact;
  }

  public boolean getEmitDeclaredOptions() {
    return emitDeclaredOptions;
  }

  public List<String> getEventListenerFactoryClasses() {
    return eventListenerFactoryClasses;
  }

  public boolean getJavaExclusive() {
    return javaExclusive;
  }

  public String getJavaOut() {
    return javaOut;
  }

  public boolean getLoadExhaustively() {
    return loadExhaustively;
  }

  public WireLogger getLog() {
    return log;
  }

  public Map<String, WireRun.Module> getModules() {
    return modules;
  }

  public List<String> getOpaqueTypes() {
    return opaqueTypes;
  }

  public boolean getPermitPackageCycles() {
    return permitPackageCycles;
  }

  public List<String> getProtoPaths() {
    return protoPaths;
  }

  public boolean getRejectUnusedRootsOrPrunes() {
    return rejectUnusedRootsOrPrunes;
  }

  public String getSchemaHandlerFactoryClass() {
    return schemaHandlerFactoryClass;
  }

  public List<String> getSourceFileNames() {
    return sourceFileNames;
  }

  public List<String> getTreeShakingRoots() {
    return treeShakingRoots;
  }

  public List<String> getTreeShakingRubbish() {
    return treeShakingRubbish;
  }

  public static void main(String[] args) {
    try {
      WireCompiler wireCompiler = forArgs(args);
      wireCompiler.compile();
    } catch (WireException | IOException e) {
      System.err.print("Fatal: ");
      e.printStackTrace(System.err);
      System.exit(1);
    }
  }

  public static WireCompiler forArgs(java.nio.file.FileSystem fileSystem, WireLogger logger,
      String... args) throws WireException {
    return forArgs(FileSystem.asOkioFileSystem(fileSystem), logger, args);
  }

  public static WireCompiler forArgs(String... args) throws WireException {
    return forArgs(FileSystem.SYSTEM, new ConsoleWireLogger(), args);
  }

  static WireCompiler forArgs(FileSystem fileSystem, WireLogger logger, String... args)
      throws WireException {
    List<String> sourceFileNames = new ArrayList<>();
    List<String> treeShakingRoots = new ArrayList<>();
    List<String> treeShakingRubbish = new ArrayList<>();
    List<String> protoPaths = new ArrayList<>();
    Map<String, WireRun.Module> modules = Collections.emptyMap();
    String javaOut = null;
    String customOut = null;
    List<String> eventListenerFactoryClasses = new ArrayList<>();
    String loggerFactoryClass = null;
    String schemaHandlerFactoryClass = null;
    boolean emitAndroid = false;
    boolean emitAndroidAnnotations = false;
    boolean emitCompact = false;
    boolean emitDeclaredOptions = true;
    boolean emitAppliedOptions = true;
    boolean permitPackageCycles = false;
    boolean loadExhaustively = false;
    boolean javaExclusive = true;
    boolean dryRun = false;
    Map<String, String> customOptions = new LinkedHashMap<>();
    boolean rejectUnusedRootsOrPrunes = true;
    List<String> opaqueTypes = new ArrayList<>();

    for (String arg : args) {
      if (arg.startsWith(PROTO_PATH_FLAG)) {
        protoPaths.add(arg.substring(PROTO_PATH_FLAG.length()));

      } else if (arg.startsWith(JAVA_OUT_FLAG)) {
        if (javaOut != null) throw new IllegalStateException("java_out already set");
        javaOut = arg.substring(JAVA_OUT_FLAG.length());

      } else if (arg.startsWith(CUSTOM_OUT_FLAG)) {
        customOut = arg.substring(CUSTOM_OUT_FLAG.length());

      } else if (arg.startsWith(LOGGER_FACTORY_CLASS_FLAG)) {
        loggerFactoryClass = arg.substring(LOGGER_FACTORY_CLASS_FLAG.length());

      } else if (arg.startsWith(EVENT_LISTENER_FACTORY_CLASS_FLAG)) {
        eventListenerFactoryClasses.add(
            arg.substring(EVENT_LISTENER_FACTORY_CLASS_FLAG.length()));

      } else if (arg.startsWith(SCHEMA_HANDLER_FACTORY_CLASS_FLAG)) {
        schemaHandlerFactoryClass = arg.substring(SCHEMA_HANDLER_FACTORY_CLASS_FLAG.length());

      } else if (arg.startsWith(CUSTOM_OPTION_FLAG)) {
        String[] keyValue = arg.substring(CUSTOM_OPTION_FLAG.length()).split(",", 2);
        customOptions.put(keyValue[0], keyValue[1]);

      } else if (arg.startsWith(OPAQUE_TYPES_FLAG)) {
        String[] types = arg.substring(OPAQUE_TYPES_FLAG.length()).split(",");
        for (String type : types) {
          if (!type.isEmpty()) opaqueTypes.add(type);
        }

      } else if (arg.startsWith(FILES_FLAG)) {
        Path files = Path.get(arg.substring(FILES_FLAG.length()));
        try (BufferedSource source = Okio.buffer(fileSystem.source(files))) {
          for (String line; (line = source.readUtf8Line()) != null; ) {
            sourceFileNames.add(line);
          }
        } catch (IOException ex) {
          // Upstream reports the missing-file case as WireException and lets other IO failures
          // escape; this port cannot throw checked IOException from forArgs, so both land here.
          throw new WireException("Error processing argument " + arg, ex);
        }

      } else if (arg.startsWith(INCLUDES_FLAG)) {
        Collections.addAll(treeShakingRoots,
            arg.substring(INCLUDES_FLAG.length()).split(","));

      } else if (arg.startsWith(EXCLUDES_FLAG)) {
        Collections.addAll(treeShakingRubbish,
            arg.substring(EXCLUDES_FLAG.length()).split(","));

      } else if (arg.startsWith(MANIFEST_FLAG)) {
        String yaml = readUtf8(fileSystem, Path.get(arg.substring(MANIFEST_FLAG.length())));
        modules = parseManifestModules(yaml);

      } else if (arg.equals(NO_JAVA_EXCLUSIVE)) {
        javaExclusive = false;

      } else if (arg.equals(ANDROID)) {
        emitAndroid = true;

      } else if (arg.equals(ANDROID_ANNOTATIONS)) {
        emitAndroidAnnotations = true;

      } else if (arg.equals(COMPACT)) {
        emitCompact = true;

      } else if (arg.equals(DRY_RUN)) {
        dryRun = true;

      } else if (arg.equals(SKIP_DECLARED_OPTIONS)) {
        emitDeclaredOptions = false;

      } else if (arg.equals(SKIP_APPLIED_OPTIONS)) {
        emitAppliedOptions = false;

      } else if (arg.equals(PERMIT_PACKAGE_CYCLES_OPTIONS)) {
        permitPackageCycles = true;

      } else if (arg.equals(LOAD_EXHAUSTIVELY)) {
        loadExhaustively = true;

      } else if (arg.equals(IGNORE_UNUSED_ROOTS_AND_PRUNES)) {
        rejectUnusedRootsOrPrunes = false;

      } else if (isKotlinOrSwiftFlag(arg)) {
        throw new IllegalArgumentException(
            "Argument '" + arg + "' targets the Kotlin or Swift code generators, which are not"
                + " included in this port (DEC-6).");

      } else if (arg.startsWith("--")) {
        throw new IllegalArgumentException("Unknown argument '" + arg + "'.");

      } else {
        sourceFileNames.add(arg);
      }
    }

    if (javaOut == null && customOut == null) {
      throw new WireException(
          "Nothing to do! Specify " + JAVA_OUT_FLAG + " or " + CUSTOM_OUT_FLAG);
    }

    if (treeShakingRoots.isEmpty()) {
      treeShakingRoots.add("*");
    }

    return new WireCompiler(
        dryRun ? new DryRunFileSystem(fileSystem) : fileSystem,
        loggerFactoryClass != null
            ? WireLoggersKt.newLoggerFactory(loggerFactoryClass).create()
            : logger,
        protoPaths,
        javaOut,
        customOut,
        schemaHandlerFactoryClass,
        sourceFileNames,
        treeShakingRoots,
        treeShakingRubbish,
        rejectUnusedRootsOrPrunes,
        modules,
        emitAndroid,
        emitAndroidAnnotations,
        emitCompact,
        emitDeclaredOptions,
        emitAppliedOptions,
        permitPackageCycles,
        loadExhaustively,
        javaExclusive,
        eventListenerFactoryClasses,
        customOptions,
        opaqueTypes);
  }

  /**
   * True for the flags upstream WireCompiler accepts for its Kotlin and Swift targets. This port
   * ships neither generator, so the flags are reported as unsupported rather than silently
   * ignored.
   */
  private static boolean isKotlinOrSwiftFlag(String arg) {
    return arg.startsWith("--kotlin_")
        || arg.startsWith("--swift_")
        || arg.equals("--no_kotlin_exclusive")
        || arg.equals("--no_swift_exclusive")
        || arg.equals("--java_interop")
        || arg.equals("--emit_proto_reader_32");
  }

  private static String readUtf8(FileSystem fileSystem, Path path) throws WireException {
    try (BufferedSource source = Okio.buffer(fileSystem.source(path))) {
      return source.readUtf8();
    } catch (IOException ex) {
      throw new WireException("Error processing " + path, ex);
    }
  }

  /**
   * Parses the module manifest YAML. Upstream uses kotlinx.serialization with kaml; both are
   * banned here, so this accepts the same documented shape: a top-level map of module names to
   * maps whose keys are {@code dependencies}, {@code roots}, and {@code prunes}, each holding a
   * list of strings, written either inline ({@code [a, b]}) or as block list items
   * ({@code "- a"} lines indented under the key).
   */
  /** Upstream's {@code internal} Manifest.kt parseManifestModules; package-private here. */
  static Map<String, WireRun.Module> parseManifestModules(String yaml) {
    Set<String> defaultRoots = Collections.singleton("*");
    Set<String> defaultPrunes = Collections.emptySet();

    Map<String, Map<String, List<String>>> modules = new LinkedHashMap<>();
    String currentModule = null;
    List<String> currentList = null;

    String[] lines = yaml.split("\n", -1);
    for (int i = 0; i < lines.length; i++) {
      String line = stripComment(lines[i]);
      if (line.trim().isEmpty()) continue;
      int indent = line.length() - line.replaceFirst("^\\s+", "").length();
      String trimmed = line.trim();

      if (indent == 0 && !trimmed.startsWith("- ")) {
        // Upstream's kaml accepts the inline empty-module form `name: {}` (asserted by the
        // adopted upstream ManifestParseTest and WireCompilerTest manifest cases).
        boolean inlineEmptyModule = trimmed.endsWith(": {}");
        if (!trimmed.endsWith(":") && !inlineEmptyModule) {
          throw manifestError(i, "expected 'module:' but was '" + trimmed + "'");
        }
        currentModule = inlineEmptyModule
            ? trimmed.substring(0, trimmed.length() - 4)
            : trimmed.substring(0, trimmed.length() - 1);
        if (currentModule.isEmpty()) throw manifestError(i, "empty module name");
        modules.put(currentModule, new LinkedHashMap<>());
        currentList = null;
      } else if (currentModule == null) {
        throw manifestError(i, "indented line outside any module");
      } else if (trimmed.startsWith("- ")) {
        if (currentList == null) throw manifestError(i, "list item outside any list");
        currentList.add(trimmed.substring(2).trim());
      } else {
        int colon = trimmed.indexOf(':');
        if (colon == -1) {
          throw manifestError(i, "expected 'key:' but was '" + trimmed + "'");
        }
        String key = trimmed.substring(0, colon).trim();
        String inlineValue = trimmed.substring(colon + 1).trim();
        if (!key.equals("dependencies") && !key.equals("roots") && !key.equals("prunes")) {
          // Upstream's kaml parser rejects unknown keys with "Unknown property 'x'"; the exact
          // fragment is asserted by the adopted upstream ManifestParseTest, so this port's
          // hand-rolled parser reproduces it (2026-10-02, TASK-16).
          throw manifestError(i, "Unknown property '" + key + "'");
        }
        List<String> list = new ArrayList<>();
        modules.get(currentModule).put(key, list);
        if (inlineValue.isEmpty()) {
          // Block list: the '- item' lines follow indented under this key.
          currentList = list;
        } else if (inlineValue.equals("{}")) {
          currentList = null; // An empty module.
        } else if (inlineValue.startsWith("[") && inlineValue.endsWith("]")) {
          String inner = inlineValue.substring(1, inlineValue.length() - 1).trim();
          if (!inner.isEmpty()) {
            for (String item : inner.split(",")) {
              list.add(item.trim());
            }
          }
          currentList = null;
        } else {
          throw manifestError(i, "unsupported value '" + inlineValue + "'");
        }
      }
    }

    Map<String, WireRun.Module> result = new LinkedHashMap<>();
    for (Map.Entry<String, Map<String, List<String>>> entry : modules.entrySet()) {
      Map<String, List<String>> fields = entry.getValue();
      Set<String> dependencies = new java.util.LinkedHashSet<>(
          fields.getOrDefault("dependencies", Collections.emptyList()));
      List<String> roots = fields.getOrDefault("roots",
          Collections.singletonList("*"));
      List<String> prunes = fields.getOrDefault("prunes", Collections.emptyList());
      Set<String> rootSet = new java.util.LinkedHashSet<>(roots);
      Set<String> pruneSet = new java.util.LinkedHashSet<>(prunes);
      PruningRules pruningRules = !rootSet.equals(defaultRoots) || !pruneSet.equals(defaultPrunes)
          ? new PruningRules.Builder().addRoot(rootSet).prune(pruneSet).build()
          : null;
      result.put(entry.getKey(), new WireRun.Module(dependencies, pruningRules));
    }
    return result;
  }

  private static String stripComment(String line) {
    int hash = line.indexOf('#');
    return hash == -1 ? line : line.substring(0, hash);
  }

  private static IllegalArgumentException manifestError(int lineNumber, String message) {
    return new IllegalArgumentException(
        "Invalid module manifest at line " + (lineNumber + 1) + ": " + message);
  }

  /** Kotlin companion mirror: Java may write {@code WireCompiler.Companion.m(...)}. */
  public static final Companion Companion = new Companion();

  public static final class Companion {
    private Companion() {
    }

    public WireCompiler forArgs(String... args) throws WireException {
      return WireCompiler.forArgs(args);
    }

    public WireCompiler forArgs(java.nio.file.FileSystem fileSystem, WireLogger logger,
        String... args) throws WireException {
      return WireCompiler.forArgs(fileSystem, logger, args);
    }

    public void main(String[] args) {
      WireCompiler.main(args);
    }
  }
}
