// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.java.interop.type.EnumProto3 in squareup/proto3/java/interop/type/interop_types.proto
package squareup.proto3.java.interop.type;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum EnumProto3 implements WireEnum {
  UNKNOWN(0),

  A(1);

  public static final ProtoAdapter<EnumProto3> ADAPTER = new ProtoAdapter_EnumProto3();

  private final int value;

  EnumProto3(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static EnumProto3 fromValue(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return A;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_EnumProto3 extends EnumAdapter<EnumProto3> {
    ProtoAdapter_EnumProto3() {
      super(EnumProto3.class, Syntax.PROTO_3, EnumProto3.UNKNOWN);
    }

    @Override
    protected EnumProto3 fromValue(int value) {
      return EnumProto3.fromValue(value);
    }
  }
}
