// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: squareup/proto3/java/interop/type/interop_types.proto
// Protobuf Java Version: 4.36.1

package squareup.proto3.java.interop.type;

@com.google.protobuf.Generated
public final class InteropTypes extends com.google.protobuf.GeneratedFile {
  private InteropTypes() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "InteropTypes");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code squareup.proto3.java.interop.type.EnumProto3}
   */
  public enum EnumProto3
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>A = 1;</code>
     */
    A(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "EnumProto3");
    }
    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>A = 1;</code>
     */
    public static final int A_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumProto3 valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumProto3 forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return A;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumProto3>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumProto3> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumProto3>() {
            public EnumProto3 findValueByNumber(int number) {
              return EnumProto3.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return squareup.proto3.java.interop.type.InteropTypes.getDescriptor().getEnumType(0);
    }

    private static final EnumProto3[] VALUES = values();

    public static EnumProto3 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumProto3(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:squareup.proto3.java.interop.type.EnumProto3)
  }

  public interface MessageProto3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:squareup.proto3.java.interop.type.MessageProto3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     * @return The a.
     */
    int getA();

    /**
     * <code>string b = 2;</code>
     * @return The b.
     */
    java.lang.String getB();
    /**
     * <code>string b = 2;</code>
     * @return The bytes for b.
     */
    com.google.protobuf.ByteString
        getBBytes();
  }
  /**
   * Protobuf type {@code squareup.proto3.java.interop.type.MessageProto3}
   */
  public static final class MessageProto3 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:squareup.proto3.java.interop.type.MessageProto3)
      MessageProto3OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "MessageProto3");
    }
    // Use MessageProto3.newBuilder() to construct.
    private MessageProto3(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MessageProto3() {
      b_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return squareup.proto3.java.interop.type.InteropTypes.internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return squareup.proto3.java.interop.type.InteropTypes.internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return squareup.proto3.java.interop.type.InteropTypes.internal_static_squareup_proto3_java_interop_type_MessageProto3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              squareup.proto3.java.interop.type.InteropTypes.MessageProto3.class, squareup.proto3.java.interop.type.InteropTypes.MessageProto3.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_ = 0;
    /**
     * <code>int32 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object b_ = "";
    /**
     * <code>string b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public java.lang.String getB() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        b_ = s;
        return s;
      }
    }
    /**
     * <code>string b = 2;</code>
     * @return The bytes for b.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBBytes() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        b_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(b_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, b_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(b_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, b_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof squareup.proto3.java.interop.type.InteropTypes.MessageProto3)) {
        return super.equals(obj);
      }
      squareup.proto3.java.interop.type.InteropTypes.MessageProto3 other = (squareup.proto3.java.interop.type.InteropTypes.MessageProto3) obj;

      if (getA()
          != other.getA()) return false;
      if (!getB()
          .equals(other.getB())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(squareup.proto3.java.interop.type.InteropTypes.MessageProto3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code squareup.proto3.java.interop.type.MessageProto3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:squareup.proto3.java.interop.type.MessageProto3)
        squareup.proto3.java.interop.type.InteropTypes.MessageProto3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return squareup.proto3.java.interop.type.InteropTypes.internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return squareup.proto3.java.interop.type.InteropTypes.internal_static_squareup_proto3_java_interop_type_MessageProto3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                squareup.proto3.java.interop.type.InteropTypes.MessageProto3.class, squareup.proto3.java.interop.type.InteropTypes.MessageProto3.Builder.class);
      }

      // Construct using squareup.proto3.java.interop.type.InteropTypes.MessageProto3.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = 0;
        b_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return squareup.proto3.java.interop.type.InteropTypes.internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor;
      }

      @java.lang.Override
      public squareup.proto3.java.interop.type.InteropTypes.MessageProto3 getDefaultInstanceForType() {
        return squareup.proto3.java.interop.type.InteropTypes.MessageProto3.getDefaultInstance();
      }

      @java.lang.Override
      public squareup.proto3.java.interop.type.InteropTypes.MessageProto3 build() {
        squareup.proto3.java.interop.type.InteropTypes.MessageProto3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public squareup.proto3.java.interop.type.InteropTypes.MessageProto3 buildPartial() {
        squareup.proto3.java.interop.type.InteropTypes.MessageProto3 result = new squareup.proto3.java.interop.type.InteropTypes.MessageProto3(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(squareup.proto3.java.interop.type.InteropTypes.MessageProto3 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = a_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.b_ = b_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof squareup.proto3.java.interop.type.InteropTypes.MessageProto3) {
          return mergeFrom((squareup.proto3.java.interop.type.InteropTypes.MessageProto3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(squareup.proto3.java.interop.type.InteropTypes.MessageProto3 other) {
        if (other == squareup.proto3.java.interop.type.InteropTypes.MessageProto3.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (!other.getB().isEmpty()) {
          b_ = other.b_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                a_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                b_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       * @return The a.
       */
      @java.lang.Override
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(int value) {

        a_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object b_ = "";
      /**
       * <code>string b = 2;</code>
       * @return The b.
       */
      public java.lang.String getB() {
        java.lang.Object ref = b_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          b_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string b = 2;</code>
       * @return The bytes for b.
       */
      public com.google.protobuf.ByteString
          getBBytes() {
        java.lang.Object ref = b_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          b_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string b = 2;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string b = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        b_ = getDefaultInstance().getB();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string b = 2;</code>
       * @param value The bytes for b to set.
       * @return This builder for chaining.
       */
      public Builder setBBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:squareup.proto3.java.interop.type.MessageProto3)
    }

    // @@protoc_insertion_point(class_scope:squareup.proto3.java.interop.type.MessageProto3)
    private static final squareup.proto3.java.interop.type.InteropTypes.MessageProto3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new squareup.proto3.java.interop.type.InteropTypes.MessageProto3();
    }

    public static squareup.proto3.java.interop.type.InteropTypes.MessageProto3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProto3>
        PARSER = new com.google.protobuf.AbstractParser<MessageProto3>() {
      @java.lang.Override
      public MessageProto3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageProto3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageProto3> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public squareup.proto3.java.interop.type.InteropTypes.MessageProto3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_squareup_proto3_java_interop_type_MessageProto3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5squareup/proto3/java/interop/type/inte" +
      "rop_types.proto\022!squareup.proto3.java.in" +
      "terop.type\"%\n\rMessageProto3\022\t\n\001a\030\001 \001(\005\022\t" +
      "\n\001b\030\002 \001(\t* \n\nEnumProto3\022\013\n\007UNKNOWN\020\000\022\005\n\001" +
      "A\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_squareup_proto3_java_interop_type_MessageProto3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_squareup_proto3_java_interop_type_MessageProto3_descriptor,
        new java.lang.String[] { "A", "B", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
