// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.java.interop.InteropOptional in squareup/proto3/java/interop/test_proto3_optional.proto
package squareup.proto3.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * The name of this file must contain `test_proto3_optional`. From: the protobuf site,
 * https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md
 *
 * > There are two options for getting around this error:
 * >
 * > 1. Pass --experimental_allow_proto3_optional to protoc.
 * > 2. Make your filename (or a directory name) contain the string test_proto3_optional. This
 * >    indicates that the proto file is specifically for testing proto3 optional support, so the
 * >    check is suppressed.
 */
public final class InteropOptional extends Message<InteropOptional, InteropOptional.Builder> {
  public static final ProtoAdapter<InteropOptional> ADAPTER = new ProtoAdapter_InteropOptional();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_VALUE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String value;

  public InteropOptional(String value) {
    this(value, ByteString.EMPTY);
  }

  public InteropOptional(String value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropOptional)) return false;
    InteropOptional o = (InteropOptional) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (value != null ? value.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (value != null) builder.append(", value=").append(Internal.sanitize(value));
    return builder.replace(0, 2, "InteropOptional{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropOptional, Builder> {
    public String value;

    public Builder() {
    }

    public Builder value(String value) {
      this.value = value;
      return this;
    }

    @Override
    public InteropOptional build() {
      return new InteropOptional(value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropOptional extends ProtoAdapter<InteropOptional> {
    public ProtoAdapter_InteropOptional() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropOptional.class, "type.googleapis.com/squareup.proto3.java.interop.InteropOptional", Syntax.PROTO_3, null, "squareup/proto3/java/interop/test_proto3_optional.proto");
    }

    @Override
    public int encodedSize(InteropOptional value) {
      int result = 0;
      result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.value);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropOptional value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropOptional value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.value);
    }

    @Override
    public InteropOptional decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.value(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropOptional redact(InteropOptional value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
