// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.java.interop.InteropDuration in squareup/proto3/java/interop/interop_test.proto
package squareup.proto3.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.time.Duration;
import java.util.Objects;
import okio.ByteString;

public final class InteropDuration extends Message<InteropDuration, InteropDuration.Builder> {
  public static final ProtoAdapter<InteropDuration> ADAPTER = new ProtoAdapter_InteropDuration();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#DURATION",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final Duration value;

  public InteropDuration(Duration value) {
    this(value, ByteString.EMPTY);
  }

  public InteropDuration(Duration value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropDuration)) return false;
    InteropDuration o = (InteropDuration) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (value != null ? value.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (value != null) builder.append(", value=").append(value);
    return builder.replace(0, 2, "InteropDuration{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropDuration, Builder> {
    public Duration value;

    public Builder() {
    }

    public Builder value(Duration value) {
      this.value = value;
      return this;
    }

    @Override
    public InteropDuration build() {
      return new InteropDuration(value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropDuration extends ProtoAdapter<InteropDuration> {
    public ProtoAdapter_InteropDuration() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropDuration.class, "type.googleapis.com/squareup.proto3.java.interop.InteropDuration", Syntax.PROTO_3, null, "squareup/proto3/java/interop/interop_test.proto");
    }

    @Override
    public int encodedSize(InteropDuration value) {
      int result = 0;
      if (!Objects.equals(value.value, null)) {
        result += ProtoAdapter.DURATION.encodedSizeWithTag(1, value.value);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropDuration value) throws IOException {
      if (!Objects.equals(value.value, null)) ProtoAdapter.DURATION.encodeWithTag(writer, 1, value.value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropDuration value) throws IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.value, null)) ProtoAdapter.DURATION.encodeWithTag(writer, 1, value.value);
    }

    @Override
    public InteropDuration decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.value(Internal.decodeMessageOrMerge(ProtoAdapter.DURATION, reader, builder.value)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropDuration redact(InteropDuration value) {
      Builder builder = value.newBuilder();
      if (builder.value != null) builder.value = ProtoAdapter.DURATION.redact(builder.value);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
