// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.java.interop.InteropMessage in squareup/proto3/java/interop/interop_message.proto
package squareup.proto3.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import okio.ByteString;
import squareup.proto2.java.interop.type.MessageProto2;
import squareup.proto3.java.interop.type.EnumProto3;
import squareup.proto3.java.interop.type.MessageProto3;

public final class InteropMessage extends Message<InteropMessage, InteropMessage.Builder> {
  public static final ProtoAdapter<InteropMessage> ADAPTER = new ProtoAdapter_InteropMessage();

  private static final long serialVersionUID = 0L;

  public static final EnumProto3 DEFAULT_ONEOF_PROTO3_ENUM = EnumProto3.UNKNOWN;

  @WireField(
      tag = 2,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "proto2Message"
  )
  public final MessageProto2 proto2_message;

  @WireField(
      tag = 3,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "proto3Enum"
  )
  public final EnumProto3 proto3_enum;

  @WireField(
      tag = 4,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "proto3Message"
  )
  public final MessageProto3 proto3_message;

  @WireField(
      tag = 202,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      label = WireField.Label.REPEATED,
      jsonName = "repProto2Message"
  )
  public final List<MessageProto2> rep_proto2_message;

  @WireField(
      tag = 203,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.REPEATED,
      jsonName = "repProto3Enum"
  )
  public final List<EnumProto3> rep_proto3_enum;

  @WireField(
      tag = 204,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      label = WireField.Label.REPEATED,
      jsonName = "repProto3Message"
  )
  public final List<MessageProto3> rep_proto3_message;

  @WireField(
      tag = 303,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      label = WireField.Label.PACKED,
      jsonName = "packProto3Enum"
  )
  public final List<EnumProto3> pack_proto3_enum;

  @WireField(
      tag = 502,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      jsonName = "mapStringProto2Message"
  )
  public final Map<String, MessageProto2> map_string_proto2_message;

  @WireField(
      tag = 503,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      jsonName = "mapStringProto3Enum"
  )
  public final Map<String, EnumProto3> map_string_proto3_enum;

  @WireField(
      tag = 504,
      keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      jsonName = "mapStringProto3Message"
  )
  public final Map<String, MessageProto3> map_string_proto3_message;

  @WireField(
      tag = 602,
      adapter = "squareup.proto2.java.interop.type.MessageProto2#ADAPTER",
      jsonName = "oneofProto2Message",
      oneofName = "choice"
  )
  public final MessageProto2 oneof_proto2_message;

  @WireField(
      tag = 603,
      adapter = "squareup.proto3.java.interop.type.EnumProto3#ADAPTER",
      jsonName = "oneofProto3Enum",
      oneofName = "choice"
  )
  public final EnumProto3 oneof_proto3_enum;

  @WireField(
      tag = 604,
      adapter = "squareup.proto3.java.interop.type.MessageProto3#ADAPTER",
      jsonName = "oneofProto3Message",
      oneofName = "choice"
  )
  public final MessageProto3 oneof_proto3_message;

  public InteropMessage(MessageProto2 proto2_message, EnumProto3 proto3_enum,
      MessageProto3 proto3_message, List<MessageProto2> rep_proto2_message,
      List<EnumProto3> rep_proto3_enum, List<MessageProto3> rep_proto3_message,
      List<EnumProto3> pack_proto3_enum, Map<String, MessageProto2> map_string_proto2_message,
      Map<String, EnumProto3> map_string_proto3_enum,
      Map<String, MessageProto3> map_string_proto3_message, MessageProto2 oneof_proto2_message,
      EnumProto3 oneof_proto3_enum, MessageProto3 oneof_proto3_message) {
    this(proto2_message, proto3_enum, proto3_message, rep_proto2_message, rep_proto3_enum, rep_proto3_message, pack_proto3_enum, map_string_proto2_message, map_string_proto3_enum, map_string_proto3_message, oneof_proto2_message, oneof_proto3_enum, oneof_proto3_message, ByteString.EMPTY);
  }

  public InteropMessage(MessageProto2 proto2_message, EnumProto3 proto3_enum,
      MessageProto3 proto3_message, List<MessageProto2> rep_proto2_message,
      List<EnumProto3> rep_proto3_enum, List<MessageProto3> rep_proto3_message,
      List<EnumProto3> pack_proto3_enum, Map<String, MessageProto2> map_string_proto2_message,
      Map<String, EnumProto3> map_string_proto3_enum,
      Map<String, MessageProto3> map_string_proto3_message, MessageProto2 oneof_proto2_message,
      EnumProto3 oneof_proto3_enum, MessageProto3 oneof_proto3_message, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (Internal.countNonNull(oneof_proto2_message, oneof_proto3_enum, oneof_proto3_message) > 1) {
      throw new IllegalArgumentException("at most one of oneof_proto2_message, oneof_proto3_enum, oneof_proto3_message may be non-null");
    }
    this.proto2_message = proto2_message;
    if (proto3_enum == null) {
      throw new IllegalArgumentException("proto3_enum == null");
    }
    this.proto3_enum = proto3_enum;
    this.proto3_message = proto3_message;
    this.rep_proto2_message = Internal.immutableCopyOf("rep_proto2_message", rep_proto2_message);
    this.rep_proto3_enum = Internal.immutableCopyOf("rep_proto3_enum", rep_proto3_enum);
    this.rep_proto3_message = Internal.immutableCopyOf("rep_proto3_message", rep_proto3_message);
    this.pack_proto3_enum = Internal.immutableCopyOf("pack_proto3_enum", pack_proto3_enum);
    this.map_string_proto2_message = Internal.immutableCopyOf("map_string_proto2_message", map_string_proto2_message);
    this.map_string_proto3_enum = Internal.immutableCopyOf("map_string_proto3_enum", map_string_proto3_enum);
    this.map_string_proto3_message = Internal.immutableCopyOf("map_string_proto3_message", map_string_proto3_message);
    this.oneof_proto2_message = oneof_proto2_message;
    this.oneof_proto3_enum = oneof_proto3_enum;
    this.oneof_proto3_message = oneof_proto3_message;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.proto2_message = proto2_message;
    builder.proto3_enum = proto3_enum;
    builder.proto3_message = proto3_message;
    builder.rep_proto2_message = Internal.copyOf(rep_proto2_message);
    builder.rep_proto3_enum = Internal.copyOf(rep_proto3_enum);
    builder.rep_proto3_message = Internal.copyOf(rep_proto3_message);
    builder.pack_proto3_enum = Internal.copyOf(pack_proto3_enum);
    builder.map_string_proto2_message = Internal.copyOf(map_string_proto2_message);
    builder.map_string_proto3_enum = Internal.copyOf(map_string_proto3_enum);
    builder.map_string_proto3_message = Internal.copyOf(map_string_proto3_message);
    builder.oneof_proto2_message = oneof_proto2_message;
    builder.oneof_proto3_enum = oneof_proto3_enum;
    builder.oneof_proto3_message = oneof_proto3_message;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropMessage)) return false;
    InteropMessage o = (InteropMessage) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(proto2_message, o.proto2_message)
        && Internal.equals(proto3_enum, o.proto3_enum)
        && Internal.equals(proto3_message, o.proto3_message)
        && rep_proto2_message.equals(o.rep_proto2_message)
        && rep_proto3_enum.equals(o.rep_proto3_enum)
        && rep_proto3_message.equals(o.rep_proto3_message)
        && pack_proto3_enum.equals(o.pack_proto3_enum)
        && map_string_proto2_message.equals(o.map_string_proto2_message)
        && map_string_proto3_enum.equals(o.map_string_proto3_enum)
        && map_string_proto3_message.equals(o.map_string_proto3_message)
        && Internal.equals(oneof_proto2_message, o.oneof_proto2_message)
        && Internal.equals(oneof_proto3_enum, o.oneof_proto3_enum)
        && Internal.equals(oneof_proto3_message, o.oneof_proto3_message);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (proto2_message != null ? proto2_message.hashCode() : 0);
      result = result * 37 + (proto3_enum != null ? proto3_enum.hashCode() : 0);
      result = result * 37 + (proto3_message != null ? proto3_message.hashCode() : 0);
      result = result * 37 + rep_proto2_message.hashCode();
      result = result * 37 + rep_proto3_enum.hashCode();
      result = result * 37 + rep_proto3_message.hashCode();
      result = result * 37 + pack_proto3_enum.hashCode();
      result = result * 37 + map_string_proto2_message.hashCode();
      result = result * 37 + map_string_proto3_enum.hashCode();
      result = result * 37 + map_string_proto3_message.hashCode();
      result = result * 37 + (oneof_proto2_message != null ? oneof_proto2_message.hashCode() : 0);
      result = result * 37 + (oneof_proto3_enum != null ? oneof_proto3_enum.hashCode() : 0);
      result = result * 37 + (oneof_proto3_message != null ? oneof_proto3_message.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (proto2_message != null) builder.append(", proto2_message=").append(proto2_message);
    if (proto3_enum != null) builder.append(", proto3_enum=").append(proto3_enum);
    if (proto3_message != null) builder.append(", proto3_message=").append(proto3_message);
    if (!rep_proto2_message.isEmpty()) builder.append(", rep_proto2_message=").append(rep_proto2_message);
    if (!rep_proto3_enum.isEmpty()) builder.append(", rep_proto3_enum=").append(rep_proto3_enum);
    if (!rep_proto3_message.isEmpty()) builder.append(", rep_proto3_message=").append(rep_proto3_message);
    if (!pack_proto3_enum.isEmpty()) builder.append(", pack_proto3_enum=").append(pack_proto3_enum);
    if (!map_string_proto2_message.isEmpty()) builder.append(", map_string_proto2_message=").append(map_string_proto2_message);
    if (!map_string_proto3_enum.isEmpty()) builder.append(", map_string_proto3_enum=").append(map_string_proto3_enum);
    if (!map_string_proto3_message.isEmpty()) builder.append(", map_string_proto3_message=").append(map_string_proto3_message);
    if (oneof_proto2_message != null) builder.append(", oneof_proto2_message=").append(oneof_proto2_message);
    if (oneof_proto3_enum != null) builder.append(", oneof_proto3_enum=").append(oneof_proto3_enum);
    if (oneof_proto3_message != null) builder.append(", oneof_proto3_message=").append(oneof_proto3_message);
    return builder.replace(0, 2, "InteropMessage{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropMessage, Builder> {
    public MessageProto2 proto2_message;

    public EnumProto3 proto3_enum;

    public MessageProto3 proto3_message;

    public List<MessageProto2> rep_proto2_message;

    public List<EnumProto3> rep_proto3_enum;

    public List<MessageProto3> rep_proto3_message;

    public List<EnumProto3> pack_proto3_enum;

    public Map<String, MessageProto2> map_string_proto2_message;

    public Map<String, EnumProto3> map_string_proto3_enum;

    public Map<String, MessageProto3> map_string_proto3_message;

    public MessageProto2 oneof_proto2_message;

    public EnumProto3 oneof_proto3_enum;

    public MessageProto3 oneof_proto3_message;

    public Builder() {
      proto3_enum = EnumProto3.UNKNOWN;
      rep_proto2_message = Internal.newMutableList();
      rep_proto3_enum = Internal.newMutableList();
      rep_proto3_message = Internal.newMutableList();
      pack_proto3_enum = Internal.newMutableList();
      map_string_proto2_message = Internal.newMutableMap();
      map_string_proto3_enum = Internal.newMutableMap();
      map_string_proto3_message = Internal.newMutableMap();
    }

    public Builder proto2_message(MessageProto2 proto2_message) {
      this.proto2_message = proto2_message;
      return this;
    }

    public Builder proto3_enum(EnumProto3 proto3_enum) {
      this.proto3_enum = proto3_enum;
      return this;
    }

    public Builder proto3_message(MessageProto3 proto3_message) {
      this.proto3_message = proto3_message;
      return this;
    }

    public Builder rep_proto2_message(List<MessageProto2> rep_proto2_message) {
      Internal.checkElementsNotNull(rep_proto2_message);
      this.rep_proto2_message = rep_proto2_message;
      return this;
    }

    public Builder rep_proto3_enum(List<EnumProto3> rep_proto3_enum) {
      Internal.checkElementsNotNull(rep_proto3_enum);
      this.rep_proto3_enum = rep_proto3_enum;
      return this;
    }

    public Builder rep_proto3_message(List<MessageProto3> rep_proto3_message) {
      Internal.checkElementsNotNull(rep_proto3_message);
      this.rep_proto3_message = rep_proto3_message;
      return this;
    }

    public Builder pack_proto3_enum(List<EnumProto3> pack_proto3_enum) {
      Internal.checkElementsNotNull(pack_proto3_enum);
      this.pack_proto3_enum = pack_proto3_enum;
      return this;
    }

    public Builder map_string_proto2_message(Map<String, MessageProto2> map_string_proto2_message) {
      Internal.checkElementsNotNull(map_string_proto2_message);
      this.map_string_proto2_message = map_string_proto2_message;
      return this;
    }

    public Builder map_string_proto3_enum(Map<String, EnumProto3> map_string_proto3_enum) {
      Internal.checkElementsNotNull(map_string_proto3_enum);
      this.map_string_proto3_enum = map_string_proto3_enum;
      return this;
    }

    public Builder map_string_proto3_message(Map<String, MessageProto3> map_string_proto3_message) {
      Internal.checkElementsNotNull(map_string_proto3_message);
      this.map_string_proto3_message = map_string_proto3_message;
      return this;
    }

    public Builder oneof_proto2_message(MessageProto2 oneof_proto2_message) {
      this.oneof_proto2_message = oneof_proto2_message;
      this.oneof_proto3_enum = null;
      this.oneof_proto3_message = null;
      return this;
    }

    public Builder oneof_proto3_enum(EnumProto3 oneof_proto3_enum) {
      this.oneof_proto3_enum = oneof_proto3_enum;
      this.oneof_proto2_message = null;
      this.oneof_proto3_message = null;
      return this;
    }

    public Builder oneof_proto3_message(MessageProto3 oneof_proto3_message) {
      this.oneof_proto3_message = oneof_proto3_message;
      this.oneof_proto2_message = null;
      this.oneof_proto3_enum = null;
      return this;
    }

    @Override
    public InteropMessage build() {
      return new InteropMessage(proto2_message, proto3_enum, proto3_message, rep_proto2_message, rep_proto3_enum, rep_proto3_message, pack_proto3_enum, map_string_proto2_message, map_string_proto3_enum, map_string_proto3_message, oneof_proto2_message, oneof_proto3_enum, oneof_proto3_message, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropMessage extends ProtoAdapter<InteropMessage> {
    private ProtoAdapter<Map<String, MessageProto2>> map_string_proto2_message;

    private ProtoAdapter<Map<String, EnumProto3>> map_string_proto3_enum;

    private ProtoAdapter<Map<String, MessageProto3>> map_string_proto3_message;

    public ProtoAdapter_InteropMessage() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropMessage.class, "type.googleapis.com/squareup.proto3.java.interop.InteropMessage", Syntax.PROTO_3, null, "squareup/proto3/java/interop/interop_message.proto");
    }

    @Override
    public int encodedSize(InteropMessage value) {
      int result = 0;
      if (!Objects.equals(value.proto2_message, null)) {
        result += MessageProto2.ADAPTER.encodedSizeWithTag(2, value.proto2_message);
      }
      if (!Objects.equals(value.proto3_enum, EnumProto3.UNKNOWN)) {
        result += EnumProto3.ADAPTER.encodedSizeWithTag(3, value.proto3_enum);
      }
      if (!Objects.equals(value.proto3_message, null)) {
        result += MessageProto3.ADAPTER.encodedSizeWithTag(4, value.proto3_message);
      }
      result += MessageProto2.ADAPTER.asRepeated().encodedSizeWithTag(202, value.rep_proto2_message);
      result += EnumProto3.ADAPTER.asRepeated().encodedSizeWithTag(203, value.rep_proto3_enum);
      result += MessageProto3.ADAPTER.asRepeated().encodedSizeWithTag(204, value.rep_proto3_message);
      result += EnumProto3.ADAPTER.asPacked().encodedSizeWithTag(303, value.pack_proto3_enum);
      result += map_string_proto2_messageAdapter().encodedSizeWithTag(502, value.map_string_proto2_message);
      result += map_string_proto3_enumAdapter().encodedSizeWithTag(503, value.map_string_proto3_enum);
      result += map_string_proto3_messageAdapter().encodedSizeWithTag(504, value.map_string_proto3_message);
      result += MessageProto2.ADAPTER.encodedSizeWithTag(602, value.oneof_proto2_message);
      result += EnumProto3.ADAPTER.encodedSizeWithTag(603, value.oneof_proto3_enum);
      result += MessageProto3.ADAPTER.encodedSizeWithTag(604, value.oneof_proto3_message);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropMessage value) throws IOException {
      if (!Objects.equals(value.proto2_message, null)) MessageProto2.ADAPTER.encodeWithTag(writer, 2, value.proto2_message);
      if (!Objects.equals(value.proto3_enum, EnumProto3.UNKNOWN)) EnumProto3.ADAPTER.encodeWithTag(writer, 3, value.proto3_enum);
      if (!Objects.equals(value.proto3_message, null)) MessageProto3.ADAPTER.encodeWithTag(writer, 4, value.proto3_message);
      MessageProto2.ADAPTER.asRepeated().encodeWithTag(writer, 202, value.rep_proto2_message);
      EnumProto3.ADAPTER.asRepeated().encodeWithTag(writer, 203, value.rep_proto3_enum);
      MessageProto3.ADAPTER.asRepeated().encodeWithTag(writer, 204, value.rep_proto3_message);
      EnumProto3.ADAPTER.asPacked().encodeWithTag(writer, 303, value.pack_proto3_enum);
      map_string_proto2_messageAdapter().encodeWithTag(writer, 502, value.map_string_proto2_message);
      map_string_proto3_enumAdapter().encodeWithTag(writer, 503, value.map_string_proto3_enum);
      map_string_proto3_messageAdapter().encodeWithTag(writer, 504, value.map_string_proto3_message);
      MessageProto2.ADAPTER.encodeWithTag(writer, 602, value.oneof_proto2_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 603, value.oneof_proto3_enum);
      MessageProto3.ADAPTER.encodeWithTag(writer, 604, value.oneof_proto3_message);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropMessage value) throws IOException {
      writer.writeBytes(value.unknownFields());
      MessageProto3.ADAPTER.encodeWithTag(writer, 604, value.oneof_proto3_message);
      EnumProto3.ADAPTER.encodeWithTag(writer, 603, value.oneof_proto3_enum);
      MessageProto2.ADAPTER.encodeWithTag(writer, 602, value.oneof_proto2_message);
      map_string_proto3_messageAdapter().encodeWithTag(writer, 504, value.map_string_proto3_message);
      map_string_proto3_enumAdapter().encodeWithTag(writer, 503, value.map_string_proto3_enum);
      map_string_proto2_messageAdapter().encodeWithTag(writer, 502, value.map_string_proto2_message);
      EnumProto3.ADAPTER.asPacked().encodeWithTag(writer, 303, value.pack_proto3_enum);
      MessageProto3.ADAPTER.asRepeated().encodeWithTag(writer, 204, value.rep_proto3_message);
      EnumProto3.ADAPTER.asRepeated().encodeWithTag(writer, 203, value.rep_proto3_enum);
      MessageProto2.ADAPTER.asRepeated().encodeWithTag(writer, 202, value.rep_proto2_message);
      if (!Objects.equals(value.proto3_message, null)) MessageProto3.ADAPTER.encodeWithTag(writer, 4, value.proto3_message);
      if (!Objects.equals(value.proto3_enum, EnumProto3.UNKNOWN)) EnumProto3.ADAPTER.encodeWithTag(writer, 3, value.proto3_enum);
      if (!Objects.equals(value.proto2_message, null)) MessageProto2.ADAPTER.encodeWithTag(writer, 2, value.proto2_message);
    }

    @Override
    public InteropMessage decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 2: builder.proto2_message(Internal.decodeMessageOrMerge(MessageProto2.ADAPTER, reader, builder.proto2_message)); break;
          case 3: {
            try {
              builder.proto3_enum(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 4: builder.proto3_message(Internal.decodeMessageOrMerge(MessageProto3.ADAPTER, reader, builder.proto3_message)); break;
          case 202: builder.rep_proto2_message.add(MessageProto2.ADAPTER.decode(reader)); break;
          case 203: {
            try {
              builder.rep_proto3_enum.add(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 204: builder.rep_proto3_message.add(MessageProto3.ADAPTER.decode(reader)); break;
          case 303: {
            try {
              EnumProto3.ADAPTER.tryDecode(reader, builder.pack_proto3_enum);
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 502: builder.map_string_proto2_message.putAll(map_string_proto2_messageAdapter().decode(reader)); break;
          case 503: builder.map_string_proto3_enum.putAll(map_string_proto3_enumAdapter().decode(reader)); break;
          case 504: builder.map_string_proto3_message.putAll(map_string_proto3_messageAdapter().decode(reader)); break;
          case 602: builder.oneof_proto2_message(Internal.decodeMessageOrMerge(MessageProto2.ADAPTER, reader, builder.oneof_proto2_message)); break;
          case 603: {
            try {
              builder.oneof_proto3_enum(EnumProto3.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 604: builder.oneof_proto3_message(Internal.decodeMessageOrMerge(MessageProto3.ADAPTER, reader, builder.oneof_proto3_message)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropMessage redact(InteropMessage value) {
      Builder builder = value.newBuilder();
      if (builder.proto2_message != null) builder.proto2_message = MessageProto2.ADAPTER.redact(builder.proto2_message);
      if (builder.proto3_message != null) builder.proto3_message = MessageProto3.ADAPTER.redact(builder.proto3_message);
      Internal.redactElements(builder.rep_proto2_message, MessageProto2.ADAPTER);
      Internal.redactElements(builder.rep_proto3_message, MessageProto3.ADAPTER);
      Internal.redactElements(builder.map_string_proto2_message, MessageProto2.ADAPTER);
      Internal.redactElements(builder.map_string_proto3_message, MessageProto3.ADAPTER);
      if (builder.oneof_proto2_message != null) builder.oneof_proto2_message = MessageProto2.ADAPTER.redact(builder.oneof_proto2_message);
      if (builder.oneof_proto3_message != null) builder.oneof_proto3_message = MessageProto3.ADAPTER.redact(builder.oneof_proto3_message);
      builder.clearUnknownFields();
      return builder.build();
    }

    private ProtoAdapter<Map<String, MessageProto2>> map_string_proto2_messageAdapter() {
      ProtoAdapter<Map<String, MessageProto2>> result = map_string_proto2_message;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, MessageProto2.ADAPTER);
        map_string_proto2_message = result;
      }
      return result;
    }

    private ProtoAdapter<Map<String, EnumProto3>> map_string_proto3_enumAdapter() {
      ProtoAdapter<Map<String, EnumProto3>> result = map_string_proto3_enum;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, EnumProto3.ADAPTER);
        map_string_proto3_enum = result;
      }
      return result;
    }

    private ProtoAdapter<Map<String, MessageProto3>> map_string_proto3_messageAdapter() {
      ProtoAdapter<Map<String, MessageProto3>> result = map_string_proto3_message;
      if (result == null) {
        result = ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, MessageProto3.ADAPTER);
        map_string_proto3_message = result;
      }
      return result;
    }
  }
}
