// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.java.interop.InteropWrappers in squareup/proto3/java/interop/interop_test.proto
package squareup.proto3.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Float;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

public final class InteropWrappers extends Message<InteropWrappers, InteropWrappers.Builder> {
  public static final ProtoAdapter<InteropWrappers> ADAPTER = new ProtoAdapter_InteropWrappers();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE_VALUE",
      jsonName = "doubleValue"
  )
  public final Double double_value;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#FLOAT_VALUE",
      jsonName = "floatValue"
  )
  public final Float float_value;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT64_VALUE",
      jsonName = "int64Value"
  )
  public final Long int64_value;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64_VALUE",
      jsonName = "uint64Value"
  )
  public final Long uint64_value;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INT32_VALUE",
      jsonName = "int32Value"
  )
  public final Integer int32_value;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32_VALUE",
      jsonName = "uint32Value"
  )
  public final Integer uint32_value;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL_VALUE",
      jsonName = "boolValue"
  )
  public final Boolean bool_value;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#STRING_VALUE",
      jsonName = "stringValue"
  )
  public final String string_value;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES_VALUE",
      jsonName = "bytesValue"
  )
  public final ByteString bytes_value;

  public InteropWrappers(Double double_value, Float float_value, Long int64_value,
      Long uint64_value, Integer int32_value, Integer uint32_value, Boolean bool_value,
      String string_value, ByteString bytes_value) {
    this(double_value, float_value, int64_value, uint64_value, int32_value, uint32_value, bool_value, string_value, bytes_value, ByteString.EMPTY);
  }

  public InteropWrappers(Double double_value, Float float_value, Long int64_value,
      Long uint64_value, Integer int32_value, Integer uint32_value, Boolean bool_value,
      String string_value, ByteString bytes_value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.double_value = double_value;
    this.float_value = float_value;
    this.int64_value = int64_value;
    this.uint64_value = uint64_value;
    this.int32_value = int32_value;
    this.uint32_value = uint32_value;
    this.bool_value = bool_value;
    this.string_value = string_value;
    this.bytes_value = bytes_value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.double_value = double_value;
    builder.float_value = float_value;
    builder.int64_value = int64_value;
    builder.uint64_value = uint64_value;
    builder.int32_value = int32_value;
    builder.uint32_value = uint32_value;
    builder.bool_value = bool_value;
    builder.string_value = string_value;
    builder.bytes_value = bytes_value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropWrappers)) return false;
    InteropWrappers o = (InteropWrappers) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(double_value, o.double_value)
        && Internal.equals(float_value, o.float_value)
        && Internal.equals(int64_value, o.int64_value)
        && Internal.equals(uint64_value, o.uint64_value)
        && Internal.equals(int32_value, o.int32_value)
        && Internal.equals(uint32_value, o.uint32_value)
        && Internal.equals(bool_value, o.bool_value)
        && Internal.equals(string_value, o.string_value)
        && Internal.equals(bytes_value, o.bytes_value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (double_value != null ? double_value.hashCode() : 0);
      result = result * 37 + (float_value != null ? float_value.hashCode() : 0);
      result = result * 37 + (int64_value != null ? int64_value.hashCode() : 0);
      result = result * 37 + (uint64_value != null ? uint64_value.hashCode() : 0);
      result = result * 37 + (int32_value != null ? int32_value.hashCode() : 0);
      result = result * 37 + (uint32_value != null ? uint32_value.hashCode() : 0);
      result = result * 37 + (bool_value != null ? bool_value.hashCode() : 0);
      result = result * 37 + (string_value != null ? string_value.hashCode() : 0);
      result = result * 37 + (bytes_value != null ? bytes_value.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (double_value != null) builder.append(", double_value=").append(double_value);
    if (float_value != null) builder.append(", float_value=").append(float_value);
    if (int64_value != null) builder.append(", int64_value=").append(int64_value);
    if (uint64_value != null) builder.append(", uint64_value=").append(uint64_value);
    if (int32_value != null) builder.append(", int32_value=").append(int32_value);
    if (uint32_value != null) builder.append(", uint32_value=").append(uint32_value);
    if (bool_value != null) builder.append(", bool_value=").append(bool_value);
    if (string_value != null) builder.append(", string_value=").append(string_value);
    if (bytes_value != null) builder.append(", bytes_value=").append(bytes_value);
    return builder.replace(0, 2, "InteropWrappers{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropWrappers, Builder> {
    public Double double_value;

    public Float float_value;

    public Long int64_value;

    public Long uint64_value;

    public Integer int32_value;

    public Integer uint32_value;

    public Boolean bool_value;

    public String string_value;

    public ByteString bytes_value;

    public Builder() {
    }

    public Builder double_value(Double double_value) {
      this.double_value = double_value;
      return this;
    }

    public Builder float_value(Float float_value) {
      this.float_value = float_value;
      return this;
    }

    public Builder int64_value(Long int64_value) {
      this.int64_value = int64_value;
      return this;
    }

    public Builder uint64_value(Long uint64_value) {
      this.uint64_value = uint64_value;
      return this;
    }

    public Builder int32_value(Integer int32_value) {
      this.int32_value = int32_value;
      return this;
    }

    public Builder uint32_value(Integer uint32_value) {
      this.uint32_value = uint32_value;
      return this;
    }

    public Builder bool_value(Boolean bool_value) {
      this.bool_value = bool_value;
      return this;
    }

    public Builder string_value(String string_value) {
      this.string_value = string_value;
      return this;
    }

    public Builder bytes_value(ByteString bytes_value) {
      this.bytes_value = bytes_value;
      return this;
    }

    @Override
    public InteropWrappers build() {
      return new InteropWrappers(double_value, float_value, int64_value, uint64_value, int32_value, uint32_value, bool_value, string_value, bytes_value, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropWrappers extends ProtoAdapter<InteropWrappers> {
    public ProtoAdapter_InteropWrappers() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropWrappers.class, "type.googleapis.com/squareup.proto3.java.interop.InteropWrappers", Syntax.PROTO_3, null, "squareup/proto3/java/interop/interop_test.proto");
    }

    @Override
    public int encodedSize(InteropWrappers value) {
      int result = 0;
      if (!Objects.equals(value.double_value, null)) {
        result += ProtoAdapter.DOUBLE_VALUE.encodedSizeWithTag(1, value.double_value);
      }
      if (!Objects.equals(value.float_value, null)) {
        result += ProtoAdapter.FLOAT_VALUE.encodedSizeWithTag(2, value.float_value);
      }
      if (!Objects.equals(value.int64_value, null)) {
        result += ProtoAdapter.INT64_VALUE.encodedSizeWithTag(3, value.int64_value);
      }
      if (!Objects.equals(value.uint64_value, null)) {
        result += ProtoAdapter.UINT64_VALUE.encodedSizeWithTag(4, value.uint64_value);
      }
      if (!Objects.equals(value.int32_value, null)) {
        result += ProtoAdapter.INT32_VALUE.encodedSizeWithTag(5, value.int32_value);
      }
      if (!Objects.equals(value.uint32_value, null)) {
        result += ProtoAdapter.UINT32_VALUE.encodedSizeWithTag(6, value.uint32_value);
      }
      if (!Objects.equals(value.bool_value, null)) {
        result += ProtoAdapter.BOOL_VALUE.encodedSizeWithTag(7, value.bool_value);
      }
      if (!Objects.equals(value.string_value, null)) {
        result += ProtoAdapter.STRING_VALUE.encodedSizeWithTag(8, value.string_value);
      }
      if (!Objects.equals(value.bytes_value, null)) {
        result += ProtoAdapter.BYTES_VALUE.encodedSizeWithTag(9, value.bytes_value);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropWrappers value) throws IOException {
      if (!Objects.equals(value.double_value, null)) ProtoAdapter.DOUBLE_VALUE.encodeWithTag(writer, 1, value.double_value);
      if (!Objects.equals(value.float_value, null)) ProtoAdapter.FLOAT_VALUE.encodeWithTag(writer, 2, value.float_value);
      if (!Objects.equals(value.int64_value, null)) ProtoAdapter.INT64_VALUE.encodeWithTag(writer, 3, value.int64_value);
      if (!Objects.equals(value.uint64_value, null)) ProtoAdapter.UINT64_VALUE.encodeWithTag(writer, 4, value.uint64_value);
      if (!Objects.equals(value.int32_value, null)) ProtoAdapter.INT32_VALUE.encodeWithTag(writer, 5, value.int32_value);
      if (!Objects.equals(value.uint32_value, null)) ProtoAdapter.UINT32_VALUE.encodeWithTag(writer, 6, value.uint32_value);
      if (!Objects.equals(value.bool_value, null)) ProtoAdapter.BOOL_VALUE.encodeWithTag(writer, 7, value.bool_value);
      if (!Objects.equals(value.string_value, null)) ProtoAdapter.STRING_VALUE.encodeWithTag(writer, 8, value.string_value);
      if (!Objects.equals(value.bytes_value, null)) ProtoAdapter.BYTES_VALUE.encodeWithTag(writer, 9, value.bytes_value);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropWrappers value) throws IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.bytes_value, null)) ProtoAdapter.BYTES_VALUE.encodeWithTag(writer, 9, value.bytes_value);
      if (!Objects.equals(value.string_value, null)) ProtoAdapter.STRING_VALUE.encodeWithTag(writer, 8, value.string_value);
      if (!Objects.equals(value.bool_value, null)) ProtoAdapter.BOOL_VALUE.encodeWithTag(writer, 7, value.bool_value);
      if (!Objects.equals(value.uint32_value, null)) ProtoAdapter.UINT32_VALUE.encodeWithTag(writer, 6, value.uint32_value);
      if (!Objects.equals(value.int32_value, null)) ProtoAdapter.INT32_VALUE.encodeWithTag(writer, 5, value.int32_value);
      if (!Objects.equals(value.uint64_value, null)) ProtoAdapter.UINT64_VALUE.encodeWithTag(writer, 4, value.uint64_value);
      if (!Objects.equals(value.int64_value, null)) ProtoAdapter.INT64_VALUE.encodeWithTag(writer, 3, value.int64_value);
      if (!Objects.equals(value.float_value, null)) ProtoAdapter.FLOAT_VALUE.encodeWithTag(writer, 2, value.float_value);
      if (!Objects.equals(value.double_value, null)) ProtoAdapter.DOUBLE_VALUE.encodeWithTag(writer, 1, value.double_value);
    }

    @Override
    public InteropWrappers decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.double_value(Internal.decodeMessageOrMerge(ProtoAdapter.DOUBLE_VALUE, reader, builder.double_value)); break;
          case 2: builder.float_value(Internal.decodeMessageOrMerge(ProtoAdapter.FLOAT_VALUE, reader, builder.float_value)); break;
          case 3: builder.int64_value(Internal.decodeMessageOrMerge(ProtoAdapter.INT64_VALUE, reader, builder.int64_value)); break;
          case 4: builder.uint64_value(Internal.decodeMessageOrMerge(ProtoAdapter.UINT64_VALUE, reader, builder.uint64_value)); break;
          case 5: builder.int32_value(Internal.decodeMessageOrMerge(ProtoAdapter.INT32_VALUE, reader, builder.int32_value)); break;
          case 6: builder.uint32_value(Internal.decodeMessageOrMerge(ProtoAdapter.UINT32_VALUE, reader, builder.uint32_value)); break;
          case 7: builder.bool_value(Internal.decodeMessageOrMerge(ProtoAdapter.BOOL_VALUE, reader, builder.bool_value)); break;
          case 8: builder.string_value(Internal.decodeMessageOrMerge(ProtoAdapter.STRING_VALUE, reader, builder.string_value)); break;
          case 9: builder.bytes_value(Internal.decodeMessageOrMerge(ProtoAdapter.BYTES_VALUE, reader, builder.bytes_value)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropWrappers redact(InteropWrappers value) {
      Builder builder = value.newBuilder();
      if (builder.double_value != null) builder.double_value = ProtoAdapter.DOUBLE_VALUE.redact(builder.double_value);
      if (builder.float_value != null) builder.float_value = ProtoAdapter.FLOAT_VALUE.redact(builder.float_value);
      if (builder.int64_value != null) builder.int64_value = ProtoAdapter.INT64_VALUE.redact(builder.int64_value);
      if (builder.uint64_value != null) builder.uint64_value = ProtoAdapter.UINT64_VALUE.redact(builder.uint64_value);
      if (builder.int32_value != null) builder.int32_value = ProtoAdapter.INT32_VALUE.redact(builder.int32_value);
      if (builder.uint32_value != null) builder.uint32_value = ProtoAdapter.UINT32_VALUE.redact(builder.uint32_value);
      if (builder.bool_value != null) builder.bool_value = ProtoAdapter.BOOL_VALUE.redact(builder.bool_value);
      if (builder.string_value != null) builder.string_value = ProtoAdapter.STRING_VALUE.redact(builder.string_value);
      if (builder.bytes_value != null) builder.bytes_value = ProtoAdapter.BYTES_VALUE.redact(builder.bytes_value);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
