// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto3.java.interop.InteropBoxOneOf in squareup/proto3/java/interop/interop_test.proto
package squareup.proto3.java.interop;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class InteropBoxOneOf extends Message<InteropBoxOneOf, InteropBoxOneOf.Builder> {
  public static final ProtoAdapter<InteropBoxOneOf> ADAPTER = new ProtoAdapter_InteropBoxOneOf();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_A = "";

  public static final Integer DEFAULT_B = 0;

  public static final Boolean DEFAULT_C = false;

  public static final Long DEFAULT_D = 0L;

  public static final ByteString DEFAULT_E = ByteString.EMPTY;

  public static final Integer DEFAULT_F = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      oneofName = "option"
  )
  public final String a;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      oneofName = "option"
  )
  public final Integer b;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL",
      oneofName = "option"
  )
  public final Boolean c;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT64",
      oneofName = "option"
  )
  public final Long d;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES",
      oneofName = "option"
  )
  public final ByteString e;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#SINT32",
      oneofName = "option"
  )
  public final Integer f;

  public InteropBoxOneOf(String a, Integer b, Boolean c, Long d, ByteString e, Integer f) {
    this(a, b, c, d, e, f, ByteString.EMPTY);
  }

  public InteropBoxOneOf(String a, Integer b, Boolean c, Long d, ByteString e, Integer f,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (Internal.countNonNull(a, b, c, d, e, f) > 1) {
      throw new IllegalArgumentException("at most one of a, b, c, d, e, f may be non-null");
    }
    this.a = a;
    this.b = b;
    this.c = c;
    this.d = d;
    this.e = e;
    this.f = f;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.a = a;
    builder.b = b;
    builder.c = c;
    builder.d = d;
    builder.e = e;
    builder.f = f;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InteropBoxOneOf)) return false;
    InteropBoxOneOf o = (InteropBoxOneOf) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(a, o.a)
        && Internal.equals(b, o.b)
        && Internal.equals(c, o.c)
        && Internal.equals(d, o.d)
        && Internal.equals(e, o.e)
        && Internal.equals(f, o.f);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (a != null ? a.hashCode() : 0);
      result = result * 37 + (b != null ? b.hashCode() : 0);
      result = result * 37 + (c != null ? c.hashCode() : 0);
      result = result * 37 + (d != null ? d.hashCode() : 0);
      result = result * 37 + (e != null ? e.hashCode() : 0);
      result = result * 37 + (f != null ? f.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (a != null) builder.append(", a=").append(Internal.sanitize(a));
    if (b != null) builder.append(", b=").append(b);
    if (c != null) builder.append(", c=").append(c);
    if (d != null) builder.append(", d=").append(d);
    if (e != null) builder.append(", e=").append(e);
    if (f != null) builder.append(", f=").append(f);
    return builder.replace(0, 2, "InteropBoxOneOf{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InteropBoxOneOf, Builder> {
    public String a;

    public Integer b;

    public Boolean c;

    public Long d;

    public ByteString e;

    public Integer f;

    public Builder() {
    }

    public Builder a(String a) {
      this.a = a;
      this.b = null;
      this.c = null;
      this.d = null;
      this.e = null;
      this.f = null;
      return this;
    }

    public Builder b(Integer b) {
      this.b = b;
      this.a = null;
      this.c = null;
      this.d = null;
      this.e = null;
      this.f = null;
      return this;
    }

    public Builder c(Boolean c) {
      this.c = c;
      this.a = null;
      this.b = null;
      this.d = null;
      this.e = null;
      this.f = null;
      return this;
    }

    public Builder d(Long d) {
      this.d = d;
      this.a = null;
      this.b = null;
      this.c = null;
      this.e = null;
      this.f = null;
      return this;
    }

    public Builder e(ByteString e) {
      this.e = e;
      this.a = null;
      this.b = null;
      this.c = null;
      this.d = null;
      this.f = null;
      return this;
    }

    public Builder f(Integer f) {
      this.f = f;
      this.a = null;
      this.b = null;
      this.c = null;
      this.d = null;
      this.e = null;
      return this;
    }

    @Override
    public InteropBoxOneOf build() {
      return new InteropBoxOneOf(a, b, c, d, e, f, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InteropBoxOneOf extends ProtoAdapter<InteropBoxOneOf> {
    public ProtoAdapter_InteropBoxOneOf() {
      super(FieldEncoding.LENGTH_DELIMITED, InteropBoxOneOf.class, "type.googleapis.com/squareup.proto3.java.interop.InteropBoxOneOf", Syntax.PROTO_3, null, "squareup/proto3/java/interop/interop_test.proto");
    }

    @Override
    public int encodedSize(InteropBoxOneOf value) {
      int result = 0;
      result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.a);
      result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.b);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.c);
      result += ProtoAdapter.INT64.encodedSizeWithTag(4, value.d);
      result += ProtoAdapter.BYTES.encodedSizeWithTag(5, value.e);
      result += ProtoAdapter.SINT32.encodedSizeWithTag(6, value.f);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, InteropBoxOneOf value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.a);
      ProtoAdapter.INT32.encodeWithTag(writer, 2, value.b);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.c);
      ProtoAdapter.INT64.encodeWithTag(writer, 4, value.d);
      ProtoAdapter.BYTES.encodeWithTag(writer, 5, value.e);
      ProtoAdapter.SINT32.encodeWithTag(writer, 6, value.f);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, InteropBoxOneOf value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.SINT32.encodeWithTag(writer, 6, value.f);
      ProtoAdapter.BYTES.encodeWithTag(writer, 5, value.e);
      ProtoAdapter.INT64.encodeWithTag(writer, 4, value.d);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.c);
      ProtoAdapter.INT32.encodeWithTag(writer, 2, value.b);
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.a);
    }

    @Override
    public InteropBoxOneOf decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.a(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.b(ProtoAdapter.INT32.decode(reader)); break;
          case 3: builder.c(ProtoAdapter.BOOL.decode(reader)); break;
          case 4: builder.d(ProtoAdapter.INT64.decode(reader)); break;
          case 5: builder.e(ProtoAdapter.BYTES.decode(reader)); break;
          case 6: builder.f(ProtoAdapter.SINT32.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public InteropBoxOneOf redact(InteropBoxOneOf value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
