// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: squareup/proto3/java/interop/test_proto3_optional.proto
// Protobuf Java Version: 4.36.1

package squareup.proto3.java.interop;

@com.google.protobuf.Generated
public final class TestProto3Optional extends com.google.protobuf.GeneratedFile {
  private TestProto3Optional() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "TestProto3Optional");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InteropOptionalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:squareup.proto3.java.interop.InteropOptional)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value = 1;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>optional string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * <pre>
   *
   * The name of this file must contain `test_proto3_optional`. From: the protobuf site,
   * https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md
   *
   * &gt; There are two options for getting around this error:
   * &gt;
   * &gt; 1. Pass --experimental_allow_proto3_optional to protoc.
   * &gt; 2. Make your filename (or a directory name) contain the string test_proto3_optional. This
   * &gt;    indicates that the proto file is specifically for testing proto3 optional support, so the
   * &gt;    check is suppressed.
   * </pre>
   *
   * Protobuf type {@code squareup.proto3.java.interop.InteropOptional}
   */
  public static final class InteropOptional extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:squareup.proto3.java.interop.InteropOptional)
      InteropOptionalOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "InteropOptional");
    }
    // Use InteropOptional.newBuilder() to construct.
    private InteropOptional(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InteropOptional() {
      value_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return squareup.proto3.java.interop.TestProto3Optional.internal_static_squareup_proto3_java_interop_InteropOptional_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return squareup.proto3.java.interop.TestProto3Optional.internal_static_squareup_proto3_java_interop_InteropOptional_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return squareup.proto3.java.interop.TestProto3Optional.internal_static_squareup_proto3_java_interop_InteropOptional_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              squareup.proto3.java.interop.TestProto3Optional.InteropOptional.class, squareup.proto3.java.interop.TestProto3Optional.InteropOptional.Builder.class);
    }

    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>optional string value = 1;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>optional string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, value_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, value_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof squareup.proto3.java.interop.TestProto3Optional.InteropOptional)) {
        return super.equals(obj);
      }
      squareup.proto3.java.interop.TestProto3Optional.InteropOptional other = (squareup.proto3.java.interop.TestProto3Optional.InteropOptional) obj;

      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(squareup.proto3.java.interop.TestProto3Optional.InteropOptional prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *
     * The name of this file must contain `test_proto3_optional`. From: the protobuf site,
     * https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md
     *
     * &gt; There are two options for getting around this error:
     * &gt;
     * &gt; 1. Pass --experimental_allow_proto3_optional to protoc.
     * &gt; 2. Make your filename (or a directory name) contain the string test_proto3_optional. This
     * &gt;    indicates that the proto file is specifically for testing proto3 optional support, so the
     * &gt;    check is suppressed.
     * </pre>
     *
     * Protobuf type {@code squareup.proto3.java.interop.InteropOptional}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:squareup.proto3.java.interop.InteropOptional)
        squareup.proto3.java.interop.TestProto3Optional.InteropOptionalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return squareup.proto3.java.interop.TestProto3Optional.internal_static_squareup_proto3_java_interop_InteropOptional_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return squareup.proto3.java.interop.TestProto3Optional.internal_static_squareup_proto3_java_interop_InteropOptional_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                squareup.proto3.java.interop.TestProto3Optional.InteropOptional.class, squareup.proto3.java.interop.TestProto3Optional.InteropOptional.Builder.class);
      }

      // Construct using squareup.proto3.java.interop.TestProto3Optional.InteropOptional.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return squareup.proto3.java.interop.TestProto3Optional.internal_static_squareup_proto3_java_interop_InteropOptional_descriptor;
      }

      @java.lang.Override
      public squareup.proto3.java.interop.TestProto3Optional.InteropOptional getDefaultInstanceForType() {
        return squareup.proto3.java.interop.TestProto3Optional.InteropOptional.getDefaultInstance();
      }

      @java.lang.Override
      public squareup.proto3.java.interop.TestProto3Optional.InteropOptional build() {
        squareup.proto3.java.interop.TestProto3Optional.InteropOptional result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public squareup.proto3.java.interop.TestProto3Optional.InteropOptional buildPartial() {
        squareup.proto3.java.interop.TestProto3Optional.InteropOptional result = new squareup.proto3.java.interop.TestProto3Optional.InteropOptional(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(squareup.proto3.java.interop.TestProto3Optional.InteropOptional result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof squareup.proto3.java.interop.TestProto3Optional.InteropOptional) {
          return mergeFrom((squareup.proto3.java.interop.TestProto3Optional.InteropOptional)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(squareup.proto3.java.interop.TestProto3Optional.InteropOptional other) {
        if (other == squareup.proto3.java.interop.TestProto3Optional.InteropOptional.getDefaultInstance()) return this;
        if (other.hasValue()) {
          value_ = other.value_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 1;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:squareup.proto3.java.interop.InteropOptional)
    }

    // @@protoc_insertion_point(class_scope:squareup.proto3.java.interop.InteropOptional)
    private static final squareup.proto3.java.interop.TestProto3Optional.InteropOptional DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new squareup.proto3.java.interop.TestProto3Optional.InteropOptional();
    }

    public static squareup.proto3.java.interop.TestProto3Optional.InteropOptional getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InteropOptional>
        PARSER = new com.google.protobuf.AbstractParser<InteropOptional>() {
      @java.lang.Override
      public InteropOptional parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InteropOptional> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InteropOptional> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public squareup.proto3.java.interop.TestProto3Optional.InteropOptional getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_squareup_proto3_java_interop_InteropOptional_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_squareup_proto3_java_interop_InteropOptional_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7squareup/proto3/java/interop/test_prot" +
      "o3_optional.proto\022\034squareup.proto3.java." +
      "interop\"/\n\017InteropOptional\022\022\n\005value\030\001 \001(" +
      "\tH\000\210\001\001B\010\n\006_valueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_squareup_proto3_java_interop_InteropOptional_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_squareup_proto3_java_interop_InteropOptional_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_squareup_proto3_java_interop_InteropOptional_descriptor,
        new java.lang.String[] { "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
