/*
 * Copyright (C) 2015 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.squareup.wire;

import com.squareup.wire.internal.Internal;
import com.squareup.wire.internal.Rethrow;
import java.io.IOException;
import java.util.Objects;

/**
 * A oneof's value and the key that identifies which field holds it. Wire has two generation
 * mechanisms for oneofs: boxed, using this class, and flat, where every oneof field is declared
 * inline in the message and at most one is non-null. Boxed suits oneofs with many choices.
 */
public final class OneOf<K extends OneOf.Key<T>, T> {
  private final K key;

  public K getKey() {
    return key;
  }

  private final T value;

  public T getValue() {
    return value;
  }

  public OneOf(K key, T value) {
    this.key = key;
    this.value = value;
  }

  public <X> X getOrNull(Key<X> key) {
    if (this.key == key) return (X) value;
    return null;
  }

  @Override public String toString() {
    // TODO(Benoit) What if the field is redacted?
    String valueAsString;
    if (key.getAdapter() == ProtoAdapter.STRING || key.getAdapter() == ProtoAdapter.STRING_VALUE) {
      valueAsString = Internal.sanitize(String.valueOf(value));
    } else {
      valueAsString = String.valueOf(value);
    }
    return key.getDeclaredName() + "=" + valueAsString;
  }

  public int encodedSizeWithTag() {
    return key.getAdapter().encodedSizeWithTag(key.getTag(), value);
  }

  public void encodeWithTag(ProtoWriter writer) {
    try {
      key.getAdapter().encodeWithTag(writer, key.getTag(), value);
    } catch (IOException e) {
      throw Rethrow.unchecked(e);
    }
  }

  public void encodeWithTag(ReverseProtoWriter writer) {
    try {
      key.getAdapter().encodeWithTag(writer, key.getTag(), value);
    } catch (IOException e) {
      throw Rethrow.unchecked(e);
    }
  }

  @Override public boolean equals(Object other) {
    if (this == other) return true;
    if (!(other instanceof OneOf)) return false;
    OneOf<?, ?> that = (OneOf<?, ?>) other;
    return key.equals(that.key) && value.equals(that.value);
  }

  @Override public int hashCode() {
    return 37 * (37 * 17 + key.hashCode()) + value.hashCode();
  }

  /**
   * Identifies a field in a OneOf. Typically subclasses are generated by the Wire compiler and
   * instances are declared as members of the referencing message class.
   */
  public abstract static class Key<T> {
    private final int tag;

    public int getTag() {
      return tag;
    }

    private final ProtoAdapter<T> adapter;

    public ProtoAdapter<T> getAdapter() {
      return adapter;
    }

    private final String declaredName;

    public String getDeclaredName() {
      return declaredName;
    }

    private final boolean redacted;

    public boolean getRedacted() {
      return redacted;
    }

    private final String jsonName;

    public String getJsonName() {
      return jsonName;
    }

    public Key(int tag, ProtoAdapter<T> adapter, String declaredName, boolean redacted,
        String jsonName) {
      this.tag = tag;
      this.adapter = adapter;
      this.declaredName = declaredName;
      this.redacted = redacted;
      this.jsonName = jsonName;
    }

    public Key(int tag, ProtoAdapter<T> adapter, String declaredName, boolean redacted) {
      this(tag, adapter, declaredName, redacted, "");
    }

    public Key(int tag, ProtoAdapter<T> adapter, String declaredName) {
      this(tag, adapter, declaredName, false, "");
    }

    @Override public boolean equals(Object other) {
      return this == other;
    }

    @Override public int hashCode() {
      return tag;
    }

    @Override public String toString() {
      return declaredName;
    }
  }
}
