/*
 * Copyright (C) 2015 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.squareup.wire;

import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.util.Objects;

/**
 * A oneof's value and the key that identifies which field holds it. Wire has two generation
 * mechanisms for oneofs: boxed, using this class, and flat, where every oneof field is declared
 * inline in the message and at most one is non-null. Boxed suits oneofs with many choices.
 */
public final class OneOf<K extends OneOf.Key<T>, T> {
  public final K key;
  public final T value;

  public OneOf(K key, T value) {
    this.key = key;
    this.value = value;
  }

  public <X> X getOrNull(Key<X> key) {
    if (this.key == key) return (X) value;
    return null;
  }

  @Override public String toString() {
    // TODO(Benoit) What if the field is redacted?
    String valueAsString;
    if (key.adapter == ProtoAdapter.STRING || key.adapter == ProtoAdapter.STRING_VALUE) {
      valueAsString = Internal.sanitize(String.valueOf(value));
    } else {
      valueAsString = String.valueOf(value);
    }
    return key.declaredName + "=" + valueAsString;
  }

  public int encodedSizeWithTag() {
    return key.adapter.encodedSizeWithTag(key.tag, value);
  }

  public void encodeWithTag(ProtoWriter writer) throws IOException {
    key.adapter.encodeWithTag(writer, key.tag, value);
  }

  public void encodeWithTag(ReverseProtoWriter writer) throws IOException {
    key.adapter.encodeWithTag(writer, key.tag, value);
  }

  @Override public boolean equals(Object other) {
    if (this == other) return true;
    if (!(other instanceof OneOf)) return false;
    OneOf<?, ?> that = (OneOf<?, ?>) other;
    return key.equals(that.key) && value.equals(that.value);
  }

  @Override public int hashCode() {
    return 37 * (37 * 17 + key.hashCode()) + value.hashCode();
  }

  /**
   * Identifies a field in a OneOf. Typically subclasses are generated by the Wire compiler and
   * instances are declared as members of the referencing message class.
   */
  public abstract static class Key<T> {
    public final int tag;
    public final ProtoAdapter<T> adapter;
    public final String declaredName;
    public final boolean redacted;
    public final String jsonName;

    protected Key(int tag, ProtoAdapter<T> adapter, String declaredName, boolean redacted,
        String jsonName) {
      this.tag = tag;
      this.adapter = adapter;
      this.declaredName = declaredName;
      this.redacted = redacted;
      this.jsonName = jsonName;
    }

    protected Key(int tag, ProtoAdapter<T> adapter, String declaredName, boolean redacted) {
      this(tag, adapter, declaredName, redacted, "");
    }

    protected Key(int tag, ProtoAdapter<T> adapter, String declaredName) {
      this(tag, adapter, declaredName, false, "");
    }

    @Override public boolean equals(Object other) {
      return this == other;
    }

    @Override public int hashCode() {
      return tag;
    }

    @Override public String toString() {
      return declaredName;
    }
  }
}
