/**
 * Pure-Java port of Wire's runtime at the pinned upstream tag (DEC-1 in docs/decisions.md).
 *
 * <p>Package and type names intentionally match upstream so that upstream test sources run
 * with minimal adaptation against this artifact and code generated by Wire 6/7 remains
 * source-compatible. M0 state: the vendored okio buffer subset (package {@code okio}) and
 * the encoding core; the remainder lands with TASK-6 through TASK-8.
 */
package com.squareup.wire;
