/**
 * Pure-Java port of Wire's runtime (upstream: square/wire, at the pinned tag recorded in
 * docs/decisions.md D8).
 *
 * <p>Package and type names intentionally match upstream so that upstream test sources run
 * unmodified against this artifact and code generated by Wire 6/7 remains binary-compatible.
 */
package com.squareup.wire;
