// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto2.java.interop.type.EnumProto2 in squareup/proto2/java/interop/type/interop_types.proto
package squareup.proto2.java.interop.type;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum EnumProto2 implements WireEnum {
  UNKNOWN(0),

  A(1);

  public static final ProtoAdapter<EnumProto2> ADAPTER = new ProtoAdapter_EnumProto2();

  private final int value;

  EnumProto2(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static EnumProto2 fromValue(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return A;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_EnumProto2 extends EnumAdapter<EnumProto2> {
    ProtoAdapter_EnumProto2() {
      super(EnumProto2.class, Syntax.PROTO_2, EnumProto2.UNKNOWN);
    }

    @Override
    protected EnumProto2 fromValue(int value) {
      return EnumProto2.fromValue(value);
    }
  }
}
