// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: squareup/proto2/java/interop/type/interop_types.proto
// Protobuf Java Version: 4.36.1

package squareup.proto2.java.interop.type;

@com.google.protobuf.Generated
public final class InteropTypes extends com.google.protobuf.GeneratedFile {
  private InteropTypes() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "InteropTypes");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code squareup.proto2.java.interop.type.EnumProto2}
   */
  public enum EnumProto2
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>A = 1;</code>
     */
    A(1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "EnumProto2");
    }
    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>A = 1;</code>
     */
    public static final int A_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumProto2 valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumProto2 forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return A;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumProto2>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumProto2> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumProto2>() {
            public EnumProto2 findValueByNumber(int number) {
              return EnumProto2.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return squareup.proto2.java.interop.type.InteropTypes.getDescriptor().getEnumType(0);
    }

    private static final EnumProto2[] VALUES = values();

    public static EnumProto2 valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumProto2(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:squareup.proto2.java.interop.type.EnumProto2)
  }

  public interface MessageProto2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:squareup.proto2.java.interop.type.MessageProto2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 a = 1;</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>optional int32 a = 1;</code>
     * @return The a.
     */
    int getA();

    /**
     * <code>required string b = 2;</code>
     * @return Whether the b field is set.
     */
    boolean hasB();
    /**
     * <code>required string b = 2;</code>
     * @return The b.
     */
    java.lang.String getB();
    /**
     * <code>required string b = 2;</code>
     * @return The bytes for b.
     */
    com.google.protobuf.ByteString
        getBBytes();
  }
  /**
   * Protobuf type {@code squareup.proto2.java.interop.type.MessageProto2}
   */
  public static final class MessageProto2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:squareup.proto2.java.interop.type.MessageProto2)
      MessageProto2OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "MessageProto2");
    }
    // Use MessageProto2.newBuilder() to construct.
    private MessageProto2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MessageProto2() {
      b_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return squareup.proto2.java.interop.type.InteropTypes.internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return squareup.proto2.java.interop.type.InteropTypes.internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return squareup.proto2.java.interop.type.InteropTypes.internal_static_squareup_proto2_java_interop_type_MessageProto2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              squareup.proto2.java.interop.type.InteropTypes.MessageProto2.class, squareup.proto2.java.interop.type.InteropTypes.MessageProto2.Builder.class);
    }

    private int bitField0_;
    public static final int A_FIELD_NUMBER = 1;
    private int a_ = 0;
    /**
     * <code>optional int32 a = 1;</code>
     * @return Whether the a field is set.
     */
    @java.lang.Override
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object b_ = "";
    /**
     * <code>required string b = 2;</code>
     * @return Whether the b field is set.
     */
    @java.lang.Override
    public boolean hasB() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public java.lang.String getB() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          b_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string b = 2;</code>
     * @return The bytes for b.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBBytes() {
      java.lang.Object ref = b_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        b_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasB()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, a_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, b_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, b_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof squareup.proto2.java.interop.type.InteropTypes.MessageProto2)) {
        return super.equals(obj);
      }
      squareup.proto2.java.interop.type.InteropTypes.MessageProto2 other = (squareup.proto2.java.interop.type.InteropTypes.MessageProto2) obj;

      if (hasA() != other.hasA()) return false;
      if (hasA()) {
        if (getA()
            != other.getA()) return false;
      }
      if (hasB() != other.hasB()) return false;
      if (hasB()) {
        if (!getB()
            .equals(other.getB())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA();
      }
      if (hasB()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(squareup.proto2.java.interop.type.InteropTypes.MessageProto2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code squareup.proto2.java.interop.type.MessageProto2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:squareup.proto2.java.interop.type.MessageProto2)
        squareup.proto2.java.interop.type.InteropTypes.MessageProto2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return squareup.proto2.java.interop.type.InteropTypes.internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return squareup.proto2.java.interop.type.InteropTypes.internal_static_squareup_proto2_java_interop_type_MessageProto2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                squareup.proto2.java.interop.type.InteropTypes.MessageProto2.class, squareup.proto2.java.interop.type.InteropTypes.MessageProto2.Builder.class);
      }

      // Construct using squareup.proto2.java.interop.type.InteropTypes.MessageProto2.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = 0;
        b_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return squareup.proto2.java.interop.type.InteropTypes.internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor;
      }

      @java.lang.Override
      public squareup.proto2.java.interop.type.InteropTypes.MessageProto2 getDefaultInstanceForType() {
        return squareup.proto2.java.interop.type.InteropTypes.MessageProto2.getDefaultInstance();
      }

      @java.lang.Override
      public squareup.proto2.java.interop.type.InteropTypes.MessageProto2 build() {
        squareup.proto2.java.interop.type.InteropTypes.MessageProto2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public squareup.proto2.java.interop.type.InteropTypes.MessageProto2 buildPartial() {
        squareup.proto2.java.interop.type.InteropTypes.MessageProto2 result = new squareup.proto2.java.interop.type.InteropTypes.MessageProto2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(squareup.proto2.java.interop.type.InteropTypes.MessageProto2 result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = a_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.b_ = b_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof squareup.proto2.java.interop.type.InteropTypes.MessageProto2) {
          return mergeFrom((squareup.proto2.java.interop.type.InteropTypes.MessageProto2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(squareup.proto2.java.interop.type.InteropTypes.MessageProto2 other) {
        if (other == squareup.proto2.java.interop.type.InteropTypes.MessageProto2.getDefaultInstance()) return this;
        if (other.hasA()) {
          setA(other.getA());
        }
        if (other.hasB()) {
          b_ = other.b_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasB()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                a_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                b_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int a_ ;
      /**
       * <code>optional int32 a = 1;</code>
       * @return Whether the a field is set.
       */
      @java.lang.Override
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 a = 1;</code>
       * @return The a.
       */
      @java.lang.Override
      public int getA() {
        return a_;
      }
      /**
       * <code>optional int32 a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(int value) {

        a_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object b_ = "";
      /**
       * <code>required string b = 2;</code>
       * @return Whether the b field is set.
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string b = 2;</code>
       * @return The b.
       */
      public java.lang.String getB() {
        java.lang.Object ref = b_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            b_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string b = 2;</code>
       * @return The bytes for b.
       */
      public com.google.protobuf.ByteString
          getBBytes() {
        java.lang.Object ref = b_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          b_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string b = 2;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string b = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        b_ = getDefaultInstance().getB();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string b = 2;</code>
       * @param value The bytes for b to set.
       * @return This builder for chaining.
       */
      public Builder setBBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:squareup.proto2.java.interop.type.MessageProto2)
    }

    // @@protoc_insertion_point(class_scope:squareup.proto2.java.interop.type.MessageProto2)
    private static final squareup.proto2.java.interop.type.InteropTypes.MessageProto2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new squareup.proto2.java.interop.type.InteropTypes.MessageProto2();
    }

    public static squareup.proto2.java.interop.type.InteropTypes.MessageProto2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProto2>
        PARSER = new com.google.protobuf.AbstractParser<MessageProto2>() {
      @java.lang.Override
      public MessageProto2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageProto2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageProto2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public squareup.proto2.java.interop.type.InteropTypes.MessageProto2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_squareup_proto2_java_interop_type_MessageProto2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5squareup/proto2/java/interop/type/inte" +
      "rop_types.proto\022!squareup.proto2.java.in" +
      "terop.type\"%\n\rMessageProto2\022\t\n\001a\030\001 \001(\005\022\t" +
      "\n\001b\030\002 \002(\t* \n\nEnumProto2\022\013\n\007UNKNOWN\020\000\022\005\n\001" +
      "A\020\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_squareup_proto2_java_interop_type_MessageProto2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_squareup_proto2_java_interop_type_MessageProto2_descriptor,
        new java.lang.String[] { "A", "B", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
