// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: squareup/proto3/java/alltypes/all_empty.proto
// Protobuf Java Version: 4.36.1

package squareup.proto3.java.alltypes;

@com.google.protobuf.Generated
public final class AllEmptyOuterClass extends com.google.protobuf.GeneratedFile {
  private AllEmptyOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "AllEmptyOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AllEmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:squareup.proto3.java.alltypes.AllEmpty)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return Whether the empty field is set.
     */
    boolean hasEmpty();
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return The empty.
     */
    com.google.protobuf.Empty getEmpty();
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     */
    com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder();

    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    java.util.List<com.google.protobuf.Empty> 
        getRepEmptyList();
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    com.google.protobuf.Empty getRepEmpty(int index);
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    int getRepEmptyCount();
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    java.util.List<? extends com.google.protobuf.EmptyOrBuilder> 
        getRepEmptyOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    com.google.protobuf.EmptyOrBuilder getRepEmptyOrBuilder(
        int index);

    /**
     * <code>.google.protobuf.Empty oneof_empty = 402;</code>
     * @return Whether the oneofEmpty field is set.
     */
    boolean hasOneofEmpty();
    /**
     * <code>.google.protobuf.Empty oneof_empty = 402;</code>
     * @return The oneofEmpty.
     */
    com.google.protobuf.Empty getOneofEmpty();
    /**
     * <code>.google.protobuf.Empty oneof_empty = 402;</code>
     */
    com.google.protobuf.EmptyOrBuilder getOneofEmptyOrBuilder();

    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    int getMapInt32EmptyCount();
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    boolean containsMapInt32Empty(
        int key);
    /**
     * Use {@link #getMapInt32EmptyMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.google.protobuf.Empty>
    getMapInt32Empty();
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    java.util.Map<java.lang.Integer, com.google.protobuf.Empty>
    getMapInt32EmptyMap();
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    /* nullable */
com.google.protobuf.Empty getMapInt32EmptyOrDefault(
        int key,
        /* nullable */
com.google.protobuf.Empty defaultValue);
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    com.google.protobuf.Empty getMapInt32EmptyOrThrow(
        int key);

    squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.ChoiceCase getChoiceCase();
  }
  /**
   * Protobuf type {@code squareup.proto3.java.alltypes.AllEmpty}
   */
  public static final class AllEmpty extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:squareup.proto3.java.alltypes.AllEmpty)
      AllEmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "AllEmpty");
    }
    // Use AllEmpty.newBuilder() to construct.
    private AllEmpty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AllEmpty() {
      repEmpty_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 501:
          return internalGetMapInt32Empty();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.class, squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.Builder.class);
    }

    private int bitField0_;
    private int choiceCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object choice_;
    public enum ChoiceCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      ONEOF_EMPTY(402),
      CHOICE_NOT_SET(0);
      private final int value;
      private ChoiceCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ChoiceCase valueOf(int value) {
        return forNumber(value);
      }

      public static ChoiceCase forNumber(int value) {
        switch (value) {
          case 402: return ONEOF_EMPTY;
          case 0: return CHOICE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ChoiceCase
    getChoiceCase() {
      return ChoiceCase.forNumber(
          choiceCase_);
    }

    public static final int EMPTY_FIELD_NUMBER = 1;
    private com.google.protobuf.Empty empty_;
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return Whether the empty field is set.
     */
    @java.lang.Override
    public boolean hasEmpty() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     * @return The empty.
     */
    @java.lang.Override
    public com.google.protobuf.Empty getEmpty() {
      return empty_ == null ? com.google.protobuf.Empty.getDefaultInstance() : empty_;
    }
    /**
     * <code>.google.protobuf.Empty empty = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder() {
      return empty_ == null ? com.google.protobuf.Empty.getDefaultInstance() : empty_;
    }

    public static final int REP_EMPTY_FIELD_NUMBER = 201;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.Empty> repEmpty_;
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Empty> getRepEmptyList() {
      return repEmpty_;
    }
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.EmptyOrBuilder> 
        getRepEmptyOrBuilderList() {
      return repEmpty_;
    }
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    @java.lang.Override
    public int getRepEmptyCount() {
      return repEmpty_.size();
    }
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Empty getRepEmpty(int index) {
      return repEmpty_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
     */
    @java.lang.Override
    public com.google.protobuf.EmptyOrBuilder getRepEmptyOrBuilder(
        int index) {
      return repEmpty_.get(index);
    }

    public static final int ONEOF_EMPTY_FIELD_NUMBER = 402;
    /**
     * <code>.google.protobuf.Empty oneof_empty = 402;</code>
     * @return Whether the oneofEmpty field is set.
     */
    @java.lang.Override
    public boolean hasOneofEmpty() {
      return choiceCase_ == 402;
    }
    /**
     * <code>.google.protobuf.Empty oneof_empty = 402;</code>
     * @return The oneofEmpty.
     */
    @java.lang.Override
    public com.google.protobuf.Empty getOneofEmpty() {
      if (choiceCase_ == 402) {
         return (com.google.protobuf.Empty) choice_;
      }
      return com.google.protobuf.Empty.getDefaultInstance();
    }
    /**
     * <code>.google.protobuf.Empty oneof_empty = 402;</code>
     */
    @java.lang.Override
    public com.google.protobuf.EmptyOrBuilder getOneofEmptyOrBuilder() {
      if (choiceCase_ == 402) {
         return (com.google.protobuf.Empty) choice_;
      }
      return com.google.protobuf.Empty.getDefaultInstance();
    }

    public static final int MAP_INT32_EMPTY_FIELD_NUMBER = 501;
    private static final class MapInt32EmptyDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.google.protobuf.Empty> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.google.protobuf.Empty>newDefaultInstance(
                  squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_MapInt32EmptyEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Empty.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.google.protobuf.Empty> mapInt32Empty_;
    private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.Empty>
    internalGetMapInt32Empty() {
      if (mapInt32Empty_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapInt32EmptyDefaultEntryHolder.defaultEntry);
      }
      return mapInt32Empty_;
    }
    public int getMapInt32EmptyCount() {
      return internalGetMapInt32Empty().getMap().size();
    }
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    @java.lang.Override
    public boolean containsMapInt32Empty(
        int key) {

      return internalGetMapInt32Empty().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapInt32EmptyMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.google.protobuf.Empty> getMapInt32Empty() {
      return getMapInt32EmptyMap();
    }
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.google.protobuf.Empty> getMapInt32EmptyMap() {
      return internalGetMapInt32Empty().getMap();
    }
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.Empty getMapInt32EmptyOrDefault(
        int key,
        /* nullable */
com.google.protobuf.Empty defaultValue) {

      java.util.Map<java.lang.Integer, com.google.protobuf.Empty> map =
          internalGetMapInt32Empty().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Empty getMapInt32EmptyOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, com.google.protobuf.Empty> map =
          internalGetMapInt32Empty().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getEmpty());
      }
      for (int i = 0; i < repEmpty_.size(); i++) {
        output.writeMessage(201, repEmpty_.get(i));
      }
      if (choiceCase_ == 402) {
        output.writeMessage(402, (com.google.protobuf.Empty) choice_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetMapInt32Empty(),
          MapInt32EmptyDefaultEntryHolder.defaultEntry,
          501);
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEmpty());
      }

          {
            final int count = repEmpty_.size();
            for (int i = 0; i < count; i++) {
              size += com.google.protobuf.CodedOutputStream
                .computeMessageSizeNoTag(repEmpty_.get(i));
            }
            size += 2 * count;
          }
      if (choiceCase_ == 402) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(402, (com.google.protobuf.Empty) choice_);
      }
      for (java.util.Map.Entry<java.lang.Integer, com.google.protobuf.Empty> entry
           : internalGetMapInt32Empty().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.Empty>
        mapInt32Empty__ = MapInt32EmptyDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .buildPartial();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(501, mapInt32Empty__);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty)) {
        return super.equals(obj);
      }
      squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty other = (squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty) obj;

      if (hasEmpty() != other.hasEmpty()) return false;
      if (hasEmpty()) {
        if (!getEmpty()
            .equals(other.getEmpty())) return false;
      }
      if (!getRepEmptyList()
          .equals(other.getRepEmptyList())) return false;
      if (!internalGetMapInt32Empty().equals(
          other.internalGetMapInt32Empty())) return false;
      if (!getChoiceCase().equals(other.getChoiceCase())) return false;
      switch (choiceCase_) {
        case 402:
          if (!getOneofEmpty()
              .equals(other.getOneofEmpty())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEmpty()) {
        hash = (37 * hash) + EMPTY_FIELD_NUMBER;
        hash = (53 * hash) + getEmpty().hashCode();
      }
      if (getRepEmptyCount() > 0) {
        hash = (37 * hash) + REP_EMPTY_FIELD_NUMBER;
        hash = (53 * hash) + getRepEmptyList().hashCode();
      }
      if (!internalGetMapInt32Empty().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_INT32_EMPTY_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMapInt32Empty().hashCode();
      }
      switch (choiceCase_) {
        case 402:
          hash = (37 * hash) + ONEOF_EMPTY_FIELD_NUMBER;
          hash = (53 * hash) + getOneofEmpty().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code squareup.proto3.java.alltypes.AllEmpty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:squareup.proto3.java.alltypes.AllEmpty)
        squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 501:
            return internalGetMapInt32Empty();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 501:
            return internalGetMutableMapInt32Empty();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.class, squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.Builder.class);
      }

      // Construct using squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetEmptyFieldBuilder();
          internalGetRepEmptyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        empty_ = null;
        if (emptyBuilder_ != null) {
          emptyBuilder_.dispose();
          emptyBuilder_ = null;
        }
        if (repEmptyBuilder_ == null) {
          repEmpty_ = java.util.Collections.emptyList();
        } else {
          repEmpty_ = null;
          repEmptyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (oneofEmptyBuilder_ != null) {
          oneofEmptyBuilder_.clear();
        }
        internalGetMutableMapInt32Empty().clear();
        choiceCase_ = 0;
        choice_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return squareup.proto3.java.alltypes.AllEmptyOuterClass.internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor;
      }

      @java.lang.Override
      public squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty getDefaultInstanceForType() {
        return squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.getDefaultInstance();
      }

      @java.lang.Override
      public squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty build() {
        squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty buildPartial() {
        squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty result = new squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty result) {
        if (repEmptyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            repEmpty_ = java.util.Collections.unmodifiableList(repEmpty_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.repEmpty_ = repEmpty_;
        } else {
          result.repEmpty_ = repEmptyBuilder_.build();
        }
      }

      private void buildPartial0(squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.empty_ = emptyBuilder_ == null
              ? empty_
              : emptyBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.mapInt32Empty_ = internalGetMapInt32Empty().build(MapInt32EmptyDefaultEntryHolder.defaultEntry);
        }
        result.bitField0_ |= to_bitField0_;
      }

      private void buildPartialOneofs(squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty result) {
        result.choiceCase_ = choiceCase_;
        result.choice_ = this.choice_;
        if (choiceCase_ == 402 &&
            oneofEmptyBuilder_ != null) {
          result.choice_ = oneofEmptyBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty) {
          return mergeFrom((squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty other) {
        if (other == squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty.getDefaultInstance()) return this;
        if (other.hasEmpty()) {
          mergeEmpty(other.getEmpty());
        }
        if (repEmptyBuilder_ == null) {
          if (!other.repEmpty_.isEmpty()) {
            if (repEmpty_.isEmpty()) {
              repEmpty_ = other.repEmpty_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRepEmptyIsMutable();
              repEmpty_.addAll(other.repEmpty_);
            }
            onChanged();
          }
        } else {
          if (!other.repEmpty_.isEmpty()) {
            if (repEmptyBuilder_.isEmpty()) {
              repEmptyBuilder_.dispose();
              repEmptyBuilder_ = null;
              repEmpty_ = other.repEmpty_;
              bitField0_ = (bitField0_ & ~0x00000002);
              repEmptyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetRepEmptyFieldBuilder() : null;
            } else {
              repEmptyBuilder_.addAllMessages(other.repEmpty_);
            }
          }
        }
        internalGetMutableMapInt32Empty().mergeFrom(
            other.internalGetMapInt32Empty());
        bitField0_ |= 0x00000008;
        switch (other.getChoiceCase()) {
          case ONEOF_EMPTY: {
            mergeOneofEmpty(other.getOneofEmpty());
            break;
          }
          case CHOICE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetEmptyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 1610: {
                com.google.protobuf.Empty m =
                    input.readMessage(
                        com.google.protobuf.Empty.parser(),
                        extensionRegistry);
                if (repEmptyBuilder_ == null) {
                  ensureRepEmptyIsMutable();
                  repEmpty_.add(m);
                } else {
                  repEmptyBuilder_.addMessage(m);
                }
                break;
              } // case 1610
              case 3218: {
                input.readMessage(
                    internalGetOneofEmptyFieldBuilder().getBuilder(),
                    extensionRegistry);
                choiceCase_ = 402;
                break;
              } // case 3218
              case 4010: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.Empty>
                mapInt32Empty__ = input.readMessage(
                    MapInt32EmptyDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableMapInt32Empty().ensureBuilderMap().put(
                    mapInt32Empty__.getKey(), mapInt32Empty__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 4010
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int choiceCase_ = 0;
      private java.lang.Object choice_;
      public ChoiceCase
          getChoiceCase() {
        return ChoiceCase.forNumber(
            choiceCase_);
      }

      public Builder clearChoice() {
        choiceCase_ = 0;
        choice_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.Empty empty_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> emptyBuilder_;
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       * @return Whether the empty field is set.
       */
      public boolean hasEmpty() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       * @return The empty.
       */
      public com.google.protobuf.Empty getEmpty() {
        if (emptyBuilder_ == null) {
          return empty_ == null ? com.google.protobuf.Empty.getDefaultInstance() : empty_;
        } else {
          return emptyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder setEmpty(com.google.protobuf.Empty value) {
        if (emptyBuilder_ == null) {
          java.util.Objects.requireNonNull(value);
          empty_ = value;
        } else {
          emptyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder setEmpty(
          com.google.protobuf.Empty.Builder builderForValue) {
        if (emptyBuilder_ == null) {
          empty_ = builderForValue.build();
        } else {
          emptyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder mergeEmpty(com.google.protobuf.Empty value) {
        if (emptyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            empty_ != null &&
            empty_ != com.google.protobuf.Empty.getDefaultInstance()) {
            getEmptyBuilder().mergeFrom(value);
          } else {
            empty_ = value;
          }
        } else {
          emptyBuilder_.mergeFrom(value);
        }
        if (empty_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public Builder clearEmpty() {
        bitField0_ = (bitField0_ & ~0x00000001);
        empty_ = null;
        if (emptyBuilder_ != null) {
          emptyBuilder_.dispose();
          emptyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public com.google.protobuf.Empty.Builder getEmptyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetEmptyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      public com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder() {
        if (emptyBuilder_ != null) {
          return emptyBuilder_.getMessageOrBuilder();
        } else {
          return empty_ == null ?
              com.google.protobuf.Empty.getDefaultInstance() : empty_;
        }
      }
      /**
       * <code>.google.protobuf.Empty empty = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> 
          internalGetEmptyFieldBuilder() {
        if (emptyBuilder_ == null) {
          emptyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                  getEmpty(),
                  getParentForChildren(),
                  isClean());
          empty_ = null;
        }
        return emptyBuilder_;
      }

      private java.util.List<com.google.protobuf.Empty> repEmpty_ =
        java.util.Collections.emptyList();
      private void ensureRepEmptyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          repEmpty_ = new java.util.ArrayList<com.google.protobuf.Empty>(repEmpty_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> repEmptyBuilder_;

      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public java.util.List<com.google.protobuf.Empty> getRepEmptyList() {
        if (repEmptyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(repEmpty_);
        } else {
          return repEmptyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public int getRepEmptyCount() {
        if (repEmptyBuilder_ == null) {
          return repEmpty_.size();
        } else {
          return repEmptyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public com.google.protobuf.Empty getRepEmpty(int index) {
        if (repEmptyBuilder_ == null) {
          return repEmpty_.get(index);
        } else {
          return repEmptyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder setRepEmpty(
          int index, com.google.protobuf.Empty value) {
        if (repEmptyBuilder_ == null) {
          java.util.Objects.requireNonNull(value);
          ensureRepEmptyIsMutable();
          repEmpty_.set(index, value);
          onChanged();
        } else {
          repEmptyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder setRepEmpty(
          int index, com.google.protobuf.Empty.Builder builderForValue) {
        if (repEmptyBuilder_ == null) {
          ensureRepEmptyIsMutable();
          repEmpty_.set(index, builderForValue.build());
          onChanged();
        } else {
          repEmptyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder addRepEmpty(com.google.protobuf.Empty value) {
        if (repEmptyBuilder_ == null) {
          java.util.Objects.requireNonNull(value);
          ensureRepEmptyIsMutable();
          repEmpty_.add(value);
          onChanged();
        } else {
          repEmptyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder addRepEmpty(
          int index, com.google.protobuf.Empty value) {
        if (repEmptyBuilder_ == null) {
          java.util.Objects.requireNonNull(value);
          ensureRepEmptyIsMutable();
          repEmpty_.add(index, value);
          onChanged();
        } else {
          repEmptyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder addRepEmpty(
          com.google.protobuf.Empty.Builder builderForValue) {
        if (repEmptyBuilder_ == null) {
          ensureRepEmptyIsMutable();
          repEmpty_.add(builderForValue.build());
          onChanged();
        } else {
          repEmptyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder addRepEmpty(
          int index, com.google.protobuf.Empty.Builder builderForValue) {
        if (repEmptyBuilder_ == null) {
          ensureRepEmptyIsMutable();
          repEmpty_.add(index, builderForValue.build());
          onChanged();
        } else {
          repEmptyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder addAllRepEmpty(
          java.lang.Iterable<? extends com.google.protobuf.Empty> values) {
        if (repEmptyBuilder_ == null) {
          ensureRepEmptyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, repEmpty_);
          onChanged();
        } else {
          repEmptyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder clearRepEmpty() {
        if (repEmptyBuilder_ == null) {
          repEmpty_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          repEmptyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public Builder removeRepEmpty(int index) {
        if (repEmptyBuilder_ == null) {
          ensureRepEmptyIsMutable();
          repEmpty_.remove(index);
          onChanged();
        } else {
          repEmptyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public com.google.protobuf.Empty.Builder getRepEmptyBuilder(
          int index) {
        return internalGetRepEmptyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public com.google.protobuf.EmptyOrBuilder getRepEmptyOrBuilder(
          int index) {
        if (repEmptyBuilder_ == null) {
          return repEmpty_.get(index);  } else {
          return repEmptyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public java.util.List<? extends com.google.protobuf.EmptyOrBuilder> 
           getRepEmptyOrBuilderList() {
        if (repEmptyBuilder_ != null) {
          return repEmptyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(repEmpty_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public com.google.protobuf.Empty.Builder addRepEmptyBuilder() {
        return internalGetRepEmptyFieldBuilder().addBuilder(
            com.google.protobuf.Empty.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public com.google.protobuf.Empty.Builder addRepEmptyBuilder(
          int index) {
        return internalGetRepEmptyFieldBuilder().addBuilder(
            index, com.google.protobuf.Empty.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Empty rep_empty = 201;</code>
       */
      public java.util.List<com.google.protobuf.Empty.Builder> 
           getRepEmptyBuilderList() {
        return internalGetRepEmptyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> 
          internalGetRepEmptyFieldBuilder() {
        if (repEmptyBuilder_ == null) {
          repEmptyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                  repEmpty_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          repEmpty_ = null;
        }
        return repEmptyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> oneofEmptyBuilder_;
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       * @return Whether the oneofEmpty field is set.
       */
      @java.lang.Override
      public boolean hasOneofEmpty() {
        return choiceCase_ == 402;
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       * @return The oneofEmpty.
       */
      @java.lang.Override
      public com.google.protobuf.Empty getOneofEmpty() {
        if (oneofEmptyBuilder_ == null) {
          if (choiceCase_ == 402) {
            return (com.google.protobuf.Empty) choice_;
          }
          return com.google.protobuf.Empty.getDefaultInstance();
        } else {
          if (choiceCase_ == 402) {
            return oneofEmptyBuilder_.getMessage();
          }
          return com.google.protobuf.Empty.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      public Builder setOneofEmpty(com.google.protobuf.Empty value) {
        if (oneofEmptyBuilder_ == null) {
          java.util.Objects.requireNonNull(value);
          choice_ = value;
          onChanged();
        } else {
          oneofEmptyBuilder_.setMessage(value);
        }
        choiceCase_ = 402;
        return this;
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      public Builder setOneofEmpty(
          com.google.protobuf.Empty.Builder builderForValue) {
        if (oneofEmptyBuilder_ == null) {
          choice_ = builderForValue.build();
          onChanged();
        } else {
          oneofEmptyBuilder_.setMessage(builderForValue.build());
        }
        choiceCase_ = 402;
        return this;
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      public Builder mergeOneofEmpty(com.google.protobuf.Empty value) {
        if (oneofEmptyBuilder_ == null) {
          if (choiceCase_ == 402 &&
              choice_ != com.google.protobuf.Empty.getDefaultInstance()) {
            choice_ = com.google.protobuf.Empty.newBuilder((com.google.protobuf.Empty) choice_)
                .mergeFrom(value).buildPartial();
          } else {
            choice_ = value;
          }
          onChanged();
        } else {
          if (choiceCase_ == 402) {
            oneofEmptyBuilder_.mergeFrom(value);
          } else {
            oneofEmptyBuilder_.setMessage(value);
          }
        }
        choiceCase_ = 402;
        return this;
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      public Builder clearOneofEmpty() {
        if (oneofEmptyBuilder_ == null) {
          if (choiceCase_ == 402) {
            choiceCase_ = 0;
            choice_ = null;
            onChanged();
          }
        } else {
          if (choiceCase_ == 402) {
            choiceCase_ = 0;
            choice_ = null;
          }
          oneofEmptyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      public com.google.protobuf.Empty.Builder getOneofEmptyBuilder() {
        return internalGetOneofEmptyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      @java.lang.Override
      public com.google.protobuf.EmptyOrBuilder getOneofEmptyOrBuilder() {
        if ((choiceCase_ == 402) && (oneofEmptyBuilder_ != null)) {
          return oneofEmptyBuilder_.getMessageOrBuilder();
        } else {
          if (choiceCase_ == 402) {
            return (com.google.protobuf.Empty) choice_;
          }
          return com.google.protobuf.Empty.getDefaultInstance();
        }
      }
      /**
       * <code>.google.protobuf.Empty oneof_empty = 402;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder> 
          internalGetOneofEmptyFieldBuilder() {
        if (oneofEmptyBuilder_ == null) {
          if (!(choiceCase_ == 402)) {
            choice_ = com.google.protobuf.Empty.getDefaultInstance();
          }
          oneofEmptyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Empty, com.google.protobuf.Empty.Builder, com.google.protobuf.EmptyOrBuilder>(
                  (com.google.protobuf.Empty) choice_,
                  getParentForChildren(),
                  isClean());
          choice_ = null;
        }
        choiceCase_ = 402;
        onChanged();
        return oneofEmptyBuilder_;
      }

      private static final class MapInt32EmptyConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.Integer, com.google.protobuf.EmptyOrBuilder, com.google.protobuf.Empty> {
        @java.lang.Override
        public com.google.protobuf.Empty build(com.google.protobuf.EmptyOrBuilder val) {
          if (val instanceof com.google.protobuf.Empty) { return (com.google.protobuf.Empty) val; }
          return ((com.google.protobuf.Empty.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.Empty> defaultEntry() {
          return MapInt32EmptyDefaultEntryHolder.defaultEntry;
        }
      };
      private static final MapInt32EmptyConverter mapInt32EmptyConverter = new MapInt32EmptyConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.Integer, com.google.protobuf.EmptyOrBuilder, com.google.protobuf.Empty, com.google.protobuf.Empty.Builder> mapInt32Empty_;
      private com.google.protobuf.MapFieldBuilder<java.lang.Integer, com.google.protobuf.EmptyOrBuilder, com.google.protobuf.Empty, com.google.protobuf.Empty.Builder>
          internalGetMapInt32Empty() {
        if (mapInt32Empty_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(mapInt32EmptyConverter);
        }
        return mapInt32Empty_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.Integer, com.google.protobuf.EmptyOrBuilder, com.google.protobuf.Empty, com.google.protobuf.Empty.Builder>
          internalGetMutableMapInt32Empty() {
        if (mapInt32Empty_ == null) {
          mapInt32Empty_ = new com.google.protobuf.MapFieldBuilder<>(mapInt32EmptyConverter);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return mapInt32Empty_;
      }
      public int getMapInt32EmptyCount() {
        return internalGetMapInt32Empty().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      @java.lang.Override
      public boolean containsMapInt32Empty(
          int key) {

        return internalGetMapInt32Empty().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getMapInt32EmptyMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.protobuf.Empty> getMapInt32Empty() {
        return getMapInt32EmptyMap();
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.google.protobuf.Empty> getMapInt32EmptyMap() {
        return internalGetMapInt32Empty().getImmutableMap();
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.Empty getMapInt32EmptyOrDefault(
          int key,
          /* nullable */
com.google.protobuf.Empty defaultValue) {

        java.util.Map<java.lang.Integer, com.google.protobuf.EmptyOrBuilder> map = internalGetMutableMapInt32Empty().ensureBuilderMap();
        return map.containsKey(key) ? mapInt32EmptyConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Empty getMapInt32EmptyOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, com.google.protobuf.EmptyOrBuilder> map = internalGetMutableMapInt32Empty().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return mapInt32EmptyConverter.build(map.get(key));
      }
      public Builder clearMapInt32Empty() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableMapInt32Empty().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      public Builder removeMapInt32Empty(
          int key) {

        internalGetMutableMapInt32Empty().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.protobuf.Empty>
          getMutableMapInt32Empty() {
        bitField0_ |= 0x00000008;
        return internalGetMutableMapInt32Empty().ensureMessageMap();
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      public Builder putMapInt32Empty(
          int key,
          com.google.protobuf.Empty value) {

        java.util.Objects.requireNonNull(value, "map value");
        internalGetMutableMapInt32Empty().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      public Builder putAllMapInt32Empty(
          java.util.Map<java.lang.Integer, com.google.protobuf.Empty> values) {
        for (java.util.Map.Entry<java.lang.Integer, com.google.protobuf.Empty> e : values.entrySet()) {
          java.util.Objects.requireNonNull(e.getKey());
          java.util.Objects.requireNonNull(e.getValue());
        }
        internalGetMutableMapInt32Empty().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;int32, .google.protobuf.Empty&gt; map_int32_empty = 501;</code>
       */
      public com.google.protobuf.Empty.Builder putMapInt32EmptyBuilderIfAbsent(
          int key) {
        java.util.Map<java.lang.Integer, com.google.protobuf.EmptyOrBuilder> builderMap = internalGetMutableMapInt32Empty().ensureBuilderMap();
        com.google.protobuf.EmptyOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.google.protobuf.Empty.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.google.protobuf.Empty) {
          entry = ((com.google.protobuf.Empty) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.google.protobuf.Empty.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:squareup.proto3.java.alltypes.AllEmpty)
    }

    // @@protoc_insertion_point(class_scope:squareup.proto3.java.alltypes.AllEmpty)
    private static final squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty();
    }

    public static squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllEmpty>
        PARSER = new com.google.protobuf.AbstractParser<AllEmpty>() {
      @java.lang.Override
      public AllEmpty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AllEmpty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllEmpty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public squareup.proto3.java.alltypes.AllEmptyOuterClass.AllEmpty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_squareup_proto3_java_alltypes_AllEmpty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_squareup_proto3_java_alltypes_AllEmpty_MapInt32EmptyEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_squareup_proto3_java_alltypes_AllEmpty_MapInt32EmptyEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-squareup/proto3/java/alltypes/all_empt" +
      "y.proto\022\035squareup.proto3.java.alltypes\032\033" +
      "google/protobuf/empty.proto\"\273\002\n\010AllEmpty" +
      "\022%\n\005empty\030\001 \001(\0132\026.google.protobuf.Empty\022" +
      "*\n\trep_empty\030\311\001 \003(\0132\026.google.protobuf.Em" +
      "pty\022.\n\013oneof_empty\030\222\003 \001(\0132\026.google.proto" +
      "buf.EmptyH\000\022T\n\017map_int32_empty\030\365\003 \003(\0132:." +
      "squareup.proto3.java.alltypes.AllEmpty.M" +
      "apInt32EmptyEntry\032L\n\022MapInt32EmptyEntry\022" +
      "\013\n\003key\030\001 \001(\005\022%\n\005value\030\002 \001(\0132\026.google.pro" +
      "tobuf.Empty:\0028\001B\010\n\006choiceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_squareup_proto3_java_alltypes_AllEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor,
        new java.lang.String[] { "Empty", "RepEmpty", "OneofEmpty", "MapInt32Empty", "Choice", });
    internal_static_squareup_proto3_java_alltypes_AllEmpty_MapInt32EmptyEntry_descriptor =
      internal_static_squareup_proto3_java_alltypes_AllEmpty_descriptor.getNestedType(0);
    internal_static_squareup_proto3_java_alltypes_AllEmpty_MapInt32EmptyEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_squareup_proto3_java_alltypes_AllEmpty_MapInt32EmptyEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
