/*
 * Copyright (C) 2026 the antiwire authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.squareup.wire;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Constructor;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import org.junit.jupiter.api.Test;

/**
 * Checks the {@link ProtoAdapter} constructors that Java subclasses can call against the pinned
 * upstream, using the relocated copy in wire-upstream-shaded.
 *
 * <p>Hand-written adapters and adapters generated by older Wire versions call the short
 * {@code (FieldEncoding, Class)} and {@code (FieldEncoding, Class, String)} forms. A missing
 * overload breaks their compilation, and a missing descriptor breaks already-compiled classes
 * with {@code NoSuchMethodError}. Found by the Retrofit converter-wire drop-in test.
 */
public class ProtoAdapterConstructorParityTest {
  private static final String UPSTREAM_PACKAGE = "io.apicurio.antiwire.parity.wire.";
  private static final String PORT_PACKAGE = "com.squareup.wire.";

  @Test
  public void everyJavaCallableUpstreamConstructorExists() {
    Set<String> port = new TreeSet<>();
    for (Constructor<?> c : ProtoAdapter.class.getDeclaredConstructors()) {
      if (Modifier.isPublic(c.getModifiers()) || Modifier.isProtected(c.getModifiers())) {
        port.add(signature(c, ""));
      }
    }

    List<String> missing = new ArrayList<>();
    int checked = 0;
    for (Constructor<?> c :
        io.apicurio.antiwire.parity.wire.ProtoAdapter.class.getDeclaredConstructors()) {
      boolean accessible =
          Modifier.isPublic(c.getModifiers()) || Modifier.isProtected(c.getModifiers());
      if (!accessible || c.isSynthetic() || usesKotlinType(c)) continue;
      checked++;
      String expected = signature(c, UPSTREAM_PACKAGE);
      if (!port.contains(expected)) missing.add(expected);
    }

    // Pinned 7.1.0 has five Class-typed constructors (2 to 6 arguments).
    assertEquals(5, checked, "upstream Java-callable constructor count changed");
    assertTrue(missing.isEmpty(), "constructors missing from the port: " + missing);
  }

  @Test
  public void twoArgumentConstructorMatchesUpstreamDefaults() {
    ProtoAdapter<String> ours = new PortAdapter(FieldEncoding.LENGTH_DELIMITED, String.class);
    io.apicurio.antiwire.parity.wire.ProtoAdapter<String> theirs = new UpstreamAdapter(
        io.apicurio.antiwire.parity.wire.FieldEncoding.LENGTH_DELIMITED, String.class);

    assertSameDefaults(ours, theirs);
    assertNull(ours.typeUrl);
    assertEquals(Syntax.PROTO_2, ours.syntax);
  }

  @Test
  public void threeArgumentConstructorMatchesUpstreamDefaults() {
    String typeUrl = "type.googleapis.com/example.Phone";
    ProtoAdapter<String> ours =
        new PortAdapter(FieldEncoding.LENGTH_DELIMITED, String.class, typeUrl);
    io.apicurio.antiwire.parity.wire.ProtoAdapter<String> theirs = new UpstreamAdapter(
        io.apicurio.antiwire.parity.wire.FieldEncoding.LENGTH_DELIMITED, String.class, typeUrl);

    assertSameDefaults(ours, theirs);
    assertEquals(typeUrl, ours.typeUrl);
  }

  @Test
  public void shortConstructorsStillBuildPackedAndRepeatedAdapters() throws Exception {
    ProtoAdapter<String> adapter = new PortAdapter(FieldEncoding.VARINT, String.class);
    assertEquals(String.class, adapter.type);
    assertTrue(adapter.asPacked() != null);
    assertTrue(adapter.asRepeated() != null);
  }

  private static void assertSameDefaults(
      ProtoAdapter<?> ours, io.apicurio.antiwire.parity.wire.ProtoAdapter<?> theirs) {
    assertEquals(theirs.getTypeUrl(), ours.typeUrl, "typeUrl");
    assertEquals(theirs.getSyntax().name(), ours.syntax.name(), "syntax");
    assertEquals(theirs.getIdentity(), ours.identity, "identity");
    assertEquals(theirs.getSourceFile(), ours.sourceFile, "sourceFile");
  }

  private static boolean usesKotlinType(Constructor<?> c) {
    for (Class<?> p : c.getParameterTypes()) {
      if (p.getName().startsWith("kotlin.")) return true;
    }
    return false;
  }

  /** Renders parameter types, mapping the relocated upstream package onto the port's. */
  private static String signature(Constructor<?> c, String relocatedPrefix) {
    StringBuilder sb = new StringBuilder("<init>(");
    Class<?>[] params = c.getParameterTypes();
    for (int i = 0; i < params.length; i++) {
      String name = params[i].getName();
      if (!relocatedPrefix.isEmpty() && name.startsWith(relocatedPrefix)) {
        name = PORT_PACKAGE + name.substring(relocatedPrefix.length());
      }
      if (i > 0) sb.append(',');
      sb.append(name);
    }
    return sb.append(')').toString();
  }

  /** A minimal subclass using only the short constructors under test. */
  private static final class PortAdapter extends ProtoAdapter<String> {
    PortAdapter(FieldEncoding fieldEncoding, Class<?> type) {
      super(fieldEncoding, type);
    }

    PortAdapter(FieldEncoding fieldEncoding, Class<?> type, String typeUrl) {
      super(fieldEncoding, type, typeUrl);
    }

    @Override public String redact(String value) {
      return value;
    }

    @Override public int encodedSize(String value) {
      return 0;
    }

    @Override public void encode(ProtoWriter writer, String value) {
    }

    @Override public String decode(ProtoReader reader) {
      return "";
    }
  }

  private static final class UpstreamAdapter
      extends io.apicurio.antiwire.parity.wire.ProtoAdapter<String> {
    UpstreamAdapter(io.apicurio.antiwire.parity.wire.FieldEncoding fieldEncoding, Class<?> type) {
      super(fieldEncoding, type);
    }

    UpstreamAdapter(io.apicurio.antiwire.parity.wire.FieldEncoding fieldEncoding, Class<?> type,
        String typeUrl) {
      super(fieldEncoding, type, typeUrl);
    }

    @Override public String redact(String value) {
      return value;
    }

    @Override public int encodedSize(String value) {
      return 0;
    }

    @Override public void encode(io.apicurio.antiwire.parity.wire.ProtoWriter writer,
        String value) {
    }

    @Override public String decode(io.apicurio.antiwire.parity.wire.ProtoReader reader) {
      return "";
    }
  }
}
