// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: squareup/proto2/java/empty/empty_length.proto
// Protobuf Java Version: 4.36.1

package squareup.proto2.java.empty;

@com.google.protobuf.Generated
public final class EmptyLengthOuterClass extends com.google.protobuf.GeneratedFile {
  private EmptyLengthOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "EmptyLengthOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyLengthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:squareup.proto2.java.empty.EmptyLength)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint32 samples = 2 [packed = true];</code>
     * @return A list containing the samples.
     */
    java.util.List<java.lang.Integer> getSamplesList();
    /**
     * <code>repeated uint32 samples = 2 [packed = true];</code>
     * @return The count of samples.
     */
    int getSamplesCount();
    /**
     * <code>repeated uint32 samples = 2 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The samples at the given index.
     */
    int getSamples(int index);
  }
  /**
   * Protobuf type {@code squareup.proto2.java.empty.EmptyLength}
   */
  public static final class EmptyLength extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:squareup.proto2.java.empty.EmptyLength)
      EmptyLengthOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "EmptyLength");
    }
    // Use EmptyLength.newBuilder() to construct.
    private EmptyLength(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EmptyLength() {
      samples_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return squareup.proto2.java.empty.EmptyLengthOuterClass.internal_static_squareup_proto2_java_empty_EmptyLength_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return squareup.proto2.java.empty.EmptyLengthOuterClass.internal_static_squareup_proto2_java_empty_EmptyLength_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return squareup.proto2.java.empty.EmptyLengthOuterClass.internal_static_squareup_proto2_java_empty_EmptyLength_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.class, squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.Builder.class);
    }

    public static final int SAMPLES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList samples_ =
        emptyIntList();
    /**
     * <code>repeated uint32 samples = 2 [packed = true];</code>
     * @return A list containing the samples.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getSamplesList() {
      return samples_;
    }
    /**
     * <code>repeated uint32 samples = 2 [packed = true];</code>
     * @return The count of samples.
     */
    public int getSamplesCount() {
      return samples_.size();
    }
    /**
     * <code>repeated uint32 samples = 2 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The samples at the given index.
     */
    public int getSamples(int index) {
      return samples_.getInt(index);
    }
    private int samplesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getSamplesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(samplesMemoizedSerializedSize);
      }
      for (int i = 0; i < samples_.size(); i++) {
        output.writeUInt32NoTag(samples_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < samples_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(samples_.getInt(i));
        }
        size += dataSize;
        if (!getSamplesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        samplesMemoizedSerializedSize = dataSize;
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength)) {
        return super.equals(obj);
      }
      squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength other = (squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength) obj;

      if (!getSamplesList()
          .equals(other.getSamplesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSamplesCount() > 0) {
        hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
        hash = (53 * hash) + getSamplesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code squareup.proto2.java.empty.EmptyLength}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:squareup.proto2.java.empty.EmptyLength)
        squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLengthOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return squareup.proto2.java.empty.EmptyLengthOuterClass.internal_static_squareup_proto2_java_empty_EmptyLength_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return squareup.proto2.java.empty.EmptyLengthOuterClass.internal_static_squareup_proto2_java_empty_EmptyLength_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.class, squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.Builder.class);
      }

      // Construct using squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        samples_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return squareup.proto2.java.empty.EmptyLengthOuterClass.internal_static_squareup_proto2_java_empty_EmptyLength_descriptor;
      }

      @java.lang.Override
      public squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength getDefaultInstanceForType() {
        return squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.getDefaultInstance();
      }

      @java.lang.Override
      public squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength build() {
        squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength buildPartial() {
        squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength result = new squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          samples_.makeImmutable();
          result.samples_ = samples_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength) {
          return mergeFrom((squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength other) {
        if (other == squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength.getDefaultInstance()) return this;
        if (!other.samples_.isEmpty()) {
          if (samples_.isEmpty()) {
            samples_ = other.samples_;
            samples_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureSamplesIsMutable();
            samples_.addAll(other.samples_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 16: {
                int v = input.readUInt32();
                ensureSamplesIsMutable();
                samples_.addInt(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureSamplesIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  samples_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList samples_ = emptyIntList();
      private void ensureSamplesIsMutable() {
        if (!samples_.isModifiable()) {
          samples_ = makeMutableCopy(samples_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @return A list containing the samples.
       */
      public java.util.List<java.lang.Integer>
          getSamplesList() {
        samples_.makeImmutable();
        return samples_;
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @return The count of samples.
       */
      public int getSamplesCount() {
        return samples_.size();
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @param index The index of the element to return.
       * @return The samples at the given index.
       */
      public int getSamples(int index) {
        return samples_.getInt(index);
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @param index The index to set the value at.
       * @param value The samples to set.
       * @return This builder for chaining.
       */
      public Builder setSamples(
          int index, int value) {

        ensureSamplesIsMutable();
        samples_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @param value The samples to add.
       * @return This builder for chaining.
       */
      public Builder addSamples(int value) {

        ensureSamplesIsMutable();
        samples_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @param values The samples to add.
       * @return This builder for chaining.
       */
      public Builder addAllSamples(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSamplesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, samples_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 samples = 2 [packed = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearSamples() {
        samples_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:squareup.proto2.java.empty.EmptyLength)
    }

    // @@protoc_insertion_point(class_scope:squareup.proto2.java.empty.EmptyLength)
    private static final squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength();
    }

    public static squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyLength>
        PARSER = new com.google.protobuf.AbstractParser<EmptyLength>() {
      @java.lang.Override
      public EmptyLength parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EmptyLength> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyLength> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public squareup.proto2.java.empty.EmptyLengthOuterClass.EmptyLength getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_squareup_proto2_java_empty_EmptyLength_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_squareup_proto2_java_empty_EmptyLength_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-squareup/proto2/java/empty/empty_lengt" +
      "h.proto\022\032squareup.proto2.java.empty\"\"\n\013E" +
      "mptyLength\022\023\n\007samples\030\002 \003(\rB\002\020\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_squareup_proto2_java_empty_EmptyLength_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_squareup_proto2_java_empty_EmptyLength_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_squareup_proto2_java_empty_EmptyLength_descriptor,
        new java.lang.String[] { "Samples", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
