// Code generated by Wire protocol buffer compiler, do not edit.
// Source: squareup.proto2.java.empty.EmptyLength in squareup/proto2/java/empty/empty_length.proto
package squareup.proto2.java.empty;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class EmptyLength extends Message<EmptyLength, EmptyLength.Builder> {
  public static final ProtoAdapter<EmptyLength> ADAPTER = new ProtoAdapter_EmptyLength();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.PACKED
  )
  public final List<Integer> samples;

  public EmptyLength(List<Integer> samples) {
    this(samples, ByteString.EMPTY);
  }

  public EmptyLength(List<Integer> samples, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.samples = Internal.immutableCopyOf("samples", samples);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.samples = Internal.copyOf(samples);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EmptyLength)) return false;
    EmptyLength o = (EmptyLength) other;
    return unknownFields().equals(o.unknownFields())
        && samples.equals(o.samples);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + samples.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!samples.isEmpty()) builder.append(", samples=").append(samples);
    return builder.replace(0, 2, "EmptyLength{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<EmptyLength, Builder> {
    public List<Integer> samples;

    public Builder() {
      samples = Internal.newMutableList();
    }

    public Builder samples(List<Integer> samples) {
      Internal.checkElementsNotNull(samples);
      this.samples = samples;
      return this;
    }

    @Override
    public EmptyLength build() {
      return new EmptyLength(samples, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_EmptyLength extends ProtoAdapter<EmptyLength> {
    public ProtoAdapter_EmptyLength() {
      super(FieldEncoding.LENGTH_DELIMITED, EmptyLength.class, "type.googleapis.com/squareup.proto2.java.empty.EmptyLength", Syntax.PROTO_2, null, "squareup/proto2/java/empty/empty_length.proto");
    }

    @Override
    public int encodedSize(EmptyLength value) {
      int result = 0;
      result += ProtoAdapter.UINT32.asPacked().encodedSizeWithTag(2, value.samples);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, EmptyLength value) throws IOException {
      ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 2, value.samples);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, EmptyLength value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.UINT32.asPacked().encodeWithTag(writer, 2, value.samples);
    }

    @Override
    public EmptyLength decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 2: ProtoAdapter.UINT32.tryDecode(reader, builder.samples); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public EmptyLength redact(EmptyLength value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
