/*
 * Copyright (C) 2020 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.squareup.wire.schema;

import java.util.HashMap;
import java.util.Map;
import okio.Path;

/**
 * {@link ClaimedPaths} tracks generated files' {@link Path}s. Schema handlers who generate files
 * are to {@link #claim} each generated file's path. It is an error to generate different {@link
 * Type}s or {@link Service}s to the same file and {@link ClaimedPaths} will throw when generation
 * conflicts happen.
 */
public final class ClaimedPaths {
  private final Map<Path, String> paths = new HashMap<>();

  /** Tracks that {@code type} has been generated to {@code path}. */
  public void claim(Path path, Type type) {
    String errorMessage = asErrorMessage(type);
    String existingEntry = paths.get(path);
    if (existingEntry != null) {
      throw new IllegalStateException(
          "Same file " + path + " is getting generated by different messages:\n"
              + "  " + existingEntry + "\n"
              + "  " + asErrorMessage(type));
    }
    paths.put(path, errorMessage);
  }

  /** Tracks that {@code service} has been generated to {@code path}. */
  public void claim(Path path, Service service) {
    String errorMessage = asErrorMessage(service);
    String existingEntry = paths.get(path);
    if (existingEntry != null) {
      throw new IllegalStateException(
          "Same file " + path + " is getting generated by different services:\n"
              + "  " + existingEntry + "\n"
              + "  " + asErrorMessage(service));
    }
    paths.put(path, errorMessage);
  }

  /** Tracks that {@code extend} has been generated to {@code path}. */
  public void claim(Path path, Extend extend) {
    String errorMessage = asErrorMessage(extend);
    String existingEntry = paths.get(path);
    if (existingEntry != null) {
      throw new IllegalStateException(
          "Same file " + path + " is getting generated for different extends:\n"
              + "  " + existingEntry + "\n"
              + "  " + asErrorMessage(extend));
    }
    paths.put(path, errorMessage);
  }

  private static String asErrorMessage(Extend extend) {
    StringBuilder fields = new StringBuilder();
    for (Field field : extend.getFields()) {
      if (fields.length() > 0) fields.append(", ");
      fields.append(field);
    }
    return extend.getType().getSimpleName() + "." + fields + " at " + extend.getLocation();
  }

  private static String asErrorMessage(Type type) {
    return type.getType().getSimpleName() + " at " + type.getLocation();
  }

  private static String asErrorMessage(Service service) {
    return service.type().getSimpleName() + " at " + service.location();
  }
}
